import type { ThemeMeta } from "../types.js";

export const themeMetas: Record<string, ThemeMeta> = {
  _baseline: {
    name: "_baseline",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "80s-neon": { name: "80s-neon", modes: ["dark"], variations: [], fonts: [] },
  aaaa: { name: "aaaa", modes: ["dark", "light"], variations: [], fonts: [] },
  abate: {
    name: "abate",
    modes: ["light"],
    variations: [],
    fonts: ["noto-sans"],
  },
  abecedarium: {
    name: "abecedarium",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  absolutegruv: {
    name: "absolutegruv",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  abyssal: {
    name: "abyssal",
    modes: ["dark", "light"],
    variations: ["colorful-headings"],
    fonts: [],
  },
  adrenaline: {
    name: "adrenaline",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  adwaita: {
    name: "adwaita",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cantarell"],
  },
  agate: {
    name: "agate",
    modes: ["light"],
    variations: [],
    fonts: ["noto-serif", "pretendard", "noto-sans-kr", "itc-slimbach"],
  },
  "aged-whisky": {
    name: "aged-whisky",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  agora: { name: "agora", modes: ["dark"], variations: [], fonts: [] },
  "ak-sky-breeze": {
    name: "ak-sky-breeze",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  "al-dente": {
    name: "al-dente",
    modes: ["light"],
    variations: [],
    fonts: ["nunito-sans", "courier-prime", "bitter"],
  },
  alien: { name: "alien", modes: ["dark", "light"], variations: [], fonts: [] },
  allium: {
    name: "allium",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "amber-cathode": {
    name: "amber-cathode",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  amethyst: {
    name: "amethyst",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "amoled-serenity": {
    name: "amoled-serenity",
    modes: ["dark"],
    variations: [],
    fonts: ["bricolage-grotesque", "roboto", "montserrat"],
  },
  "antique-flowers": {
    name: "antique-flowers",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  anuppuccin: {
    name: "anuppuccin",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["noto-serif"],
  },
  apatheia: {
    name: "apatheia",
    modes: ["dark"],
    variations: [],
    fonts: ["roboto"],
  },
  apathy: { name: "apathy", modes: ["dark"], variations: [], fonts: [] },
  apex: { name: "apex", modes: ["dark", "light"], variations: [], fonts: [] },
  arcadia: {
    name: "arcadia",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  arcane: {
    name: "arcane",
    modes: ["dark"],
    variations: [],
    fonts: ["roboto"],
  },
  "ars-magna": {
    name: "ars-magna",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  arzaba: {
    name: "arzaba",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["open-sans"],
  },
  atom: { name: "atom", modes: ["dark", "light"], variations: [], fonts: [] },
  atomus: { name: "atomus", modes: ["dark"], variations: [], fonts: [] },
  aubade: {
    name: "aubade",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  auger: { name: "auger", modes: ["dark", "light"], variations: [], fonts: [] },
  aura: {
    name: "aura",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-mono", "ia-writer-duo", "ia-writer-quattro-s", "monaco"],
  },
  "aura-dark": {
    name: "aura-dark",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  aurora: { name: "aurora", modes: ["dark"], variations: [], fonts: [] },
  "aurora-twilight": {
    name: "aurora-twilight",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cabin", "quicksand"],
  },
  autotape: {
    name: "autotape",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  avatar: {
    name: "avatar",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono", "kalam"],
  },
  ayu: { name: "ayu", modes: ["dark", "light"], variations: [], fonts: [] },
  "ayu-dark": { name: "ayu-dark", modes: ["dark"], variations: [], fonts: [] },
  "ayu-light-mirage": {
    name: "ayu-light-mirage",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lora", "monaspace-neon"],
  },
  "ayu-mirage": {
    name: "ayu-mirage",
    modes: ["dark"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco", "source-sans-pro"],
  },
  "ayu-palette": {
    name: "ayu-palette",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  azure: { name: "azure", modes: ["dark", "light"], variations: [], fonts: [] },
  base16: {
    name: "base16",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "base16-default-dark": {
    name: "base16-default-dark",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  base2tone: { name: "base2tone", modes: ["dark"], variations: [], fonts: [] },
  baseline: {
    name: "baseline",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "behave-dark": {
    name: "behave-dark",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "big-bold": {
    name: "big-bold",
    modes: ["dark", "light"],
    variations: [],
    fonts: [
      "eb-garamond",
      "fira-code",
      "merriweather-sans",
      "noto-serif",
      "noto-color-emoji",
      "noto-emoji",
      "nunito-sans",
    ],
  },
  "big-sur-aesthetic": {
    name: "big-sur-aesthetic",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  biggs: { name: "biggs", modes: ["dark", "light"], variations: [], fonts: [] },
  black: { name: "black", modes: ["dark"], variations: [], fonts: [] },
  blackbird: { name: "blackbird", modes: ["dark"], variations: [], fonts: [] },
  blobob: {
    name: "blobob",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "blood-rush": {
    name: "blood-rush",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  blossom: { name: "blossom", modes: ["dark"], variations: [], fonts: [] },
  "blue-topaz": {
    name: "blue-topaz",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lucida-handwriting", "icons/boxicons"],
  },
  blur: { name: "blur", modes: ["dark", "light"], variations: [], fonts: [] },
  bolt: {
    name: "bolt",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["formular"],
  },
  border: {
    name: "border",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  borealis: {
    name: "borealis",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  bossidian: { name: "bossidian", modes: ["dark"], variations: [], fonts: [] },
  brainhack: {
    name: "brainhack",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cascadia-mono"],
  },
  "brutal-gum": {
    name: "brutal-gum",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  brutalism: {
    name: "brutalism",
    modes: ["dark"],
    variations: [],
    fonts: ["archivo"],
  },
  brutalist: {
    name: "brutalist",
    modes: ["dark", "light"],
    variations: [],
    fonts: [
      "ai-writer-duo",
      "ai-writer-quattro",
      "ai-writer-mono",
      "libre-baskerville",
      "literata",
      "marcellus",
      "montserrat",
      "sen",
    ],
  },
  "bubble-space": {
    name: "bubble-space",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "buena-vista": {
    name: "buena-vista",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  bureau: {
    name: "bureau",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "california-coast": {
    name: "california-coast",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "calm-nights": {
    name: "calm-nights",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  camena: {
    name: "camena",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["avenir", "cascadia-code"],
  },
  carbon: {
    name: "carbon",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono", "ibm-plex-sans"],
  },
  cardinal: {
    name: "cardinal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  cardstock: {
    name: "cardstock",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  carnelian: {
    name: "carnelian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "carpe-noctem": {
    name: "carpe-noctem",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  catppuccin: {
    name: "catppuccin",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nunito-sans", "vollkorn"],
  },
  "catppuccin.frappe": {
    name: "catppuccin.frappe",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nunito-sans", "vollkorn"],
  },
  "catppuccin.macchiato": {
    name: "catppuccin.macchiato",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nunito-sans", "vollkorn"],
  },
  catthode: { name: "catthode", modes: ["dark"], variations: [], fonts: [] },
  "celestial-night": {
    name: "celestial-night",
    modes: ["dark"],
    variations: [],
    fonts: ["bookerly", "hatolie", "merienda"],
  },
  charcoal: {
    name: "charcoal",
    modes: ["dark"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco", "source-sans-pro"],
  },
  chiaroscuroflow: {
    name: "chiaroscuroflow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["manrope", "nunito-sans"],
  },
  chime: {
    name: "chime",
    modes: ["dark", "light"],
    variations: [],
    fonts: [
      "archivo",
      "arima",
      "ibm-plex-sans",
      "linux-libertine",
      "icons/noto-sans-symbols-2",
    ],
  },
  christmas: { name: "christmas", modes: ["dark"], variations: [], fonts: [] },
  "cidreira-coast": {
    name: "cidreira-coast",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  cinderpaper: {
    name: "cinderpaper",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "citrus-neo": {
    name: "citrus-neo",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "clair-de-lune": {
    name: "clair-de-lune",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  claude: { name: "claude", modes: ["dark"], variations: [], fonts: [] },
  "claude-warm": {
    name: "claude-warm",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "cloud-dancer": {
    name: "cloud-dancer",
    modes: ["light", "dark"],
    variations: [],
    fonts: [],
  },
  "cobalt-peacock": {
    name: "cobalt-peacock",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  cocoa: {
    name: "cocoa",
    modes: ["dark"],
    variations: [],
    fonts: ["palatino"],
  },
  "cocoa-nook": {
    name: "cocoa-nook",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  codeazur: { name: "codeazur", modes: ["dark"], variations: [], fonts: [] },
  coffee: {
    name: "coffee",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "cognia-noir": {
    name: "cognia-noir",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "colored-candy": {
    name: "colored-candy",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  colours: {
    name: "colours",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  comfort: { name: "comfort", modes: ["light"], variations: [], fonts: [] },
  "comfort-color-dark": {
    name: "comfort-color-dark",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "comfort-dark": {
    name: "comfort-dark",
    modes: ["dark"],
    variations: [],
    fonts: ["iosevka-web", "jetbrains-mono"],
  },
  "comfort-smooth": {
    name: "comfort-smooth",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  compline: {
    name: "compline",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  composer: {
    name: "composer",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  consolas: {
    name: "consolas",
    modes: ["dark"],
    variations: [],
    fonts: ["inconsolata"],
  },
  "cosmic-events": {
    name: "cosmic-events",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  cosmical: {
    name: "cosmical",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  covert: { name: "covert", modes: ["dark"], variations: [], fonts: [] },
  crafted: {
    name: "crafted",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "cranky-goblin": {
    name: "cranky-goblin",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  creature: {
    name: "creature",
    modes: ["dark"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "creme-brulee": {
    name: "creme-brulee",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["merriweather-sans"],
  },
  crestfall: { name: "crestfall", modes: ["dark"], variations: [], fonts: [] },
  cupertino: {
    name: "cupertino",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-pro-display"],
  },
  "cyber-glow": {
    name: "cyber-glow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ballet", "oxanium", "space-wham", "orbitron"],
  },
  cyberglow: {
    name: "cyberglow",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  cybertron: {
    name: "cybertron",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "cybertron-shifted": {
    name: "cybertron-shifted",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  cybrcore: { name: "cybrcore", modes: ["dark"], variations: [], fonts: [] },
  "dark-castle": {
    name: "dark-castle",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "dark-clarity": {
    name: "dark-clarity",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["noto-sans", "jetbrains-mono"],
  },
  "dark-graphite": {
    name: "dark-graphite",
    modes: ["dark"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco"],
  },
  "dark-graphite-pie": {
    name: "dark-graphite-pie",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "dark-knight": {
    name: "dark-knight",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "dark-moss": {
    name: "dark-moss",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  darkember: {
    name: "darkember",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  darkyan: { name: "darkyan", modes: ["dark"], variations: [], fonts: [] },
  dashboard: { name: "dashboard", modes: ["light"], variations: [], fonts: [] },
  dawn: { name: "dawn", modes: ["dark", "light"], variations: [], fonts: [] },
  dayspring: {
    name: "dayspring",
    modes: ["light"],
    variations: [],
    fonts: ["crimson-pro", "figtree"],
  },
  dedication: {
    name: "dedication",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "dedication-2": {
    name: "dedication-2",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "deep-submerge": {
    name: "deep-submerge",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "deeper-work": {
    name: "deeper-work",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  default: {
    name: "default",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["flow-circular"],
  },
  dekurai: { name: "dekurai", modes: ["dark"], variations: [], fonts: [] },
  delightful: {
    name: "delightful",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  densy: { name: "densy", modes: ["light"], variations: [], fonts: [] },
  desserts: {
    name: "desserts",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  discordian: {
    name: "discordian",
    modes: ["dark"],
    variations: [],
    fonts: ["catamaran"],
  },
  doctorfree: {
    name: "doctorfree",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  dolch: { name: "dolch", modes: ["dark"], variations: [], fonts: [] },
  "dracula-for-obsidian": {
    name: "dracula-for-obsidian",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "dracula-gemini": {
    name: "dracula-gemini",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "dracula-lyt": {
    name: "dracula-lyt",
    modes: ["dark"],
    variations: [],
    fonts: ["monaco", "sf-mono"],
  },
  "dracula-official": {
    name: "dracula-official",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "dracula-plus": {
    name: "dracula-plus",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono", "monaco"],
  },
  "dracula-slim": {
    name: "dracula-slim",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  duality: {
    name: "duality",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  dune: { name: "dune", modes: ["dark", "light"], variations: [], fonts: [] },
  dunite: {
    name: "dunite",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  dust: {
    name: "dust",
    modes: ["dark"],
    variations: [],
    fonts: ["icons/material-icons", "fira-code"],
  },
  "dynamic-color": {
    name: "dynamic-color",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ebullientworks: {
    name: "ebullientworks",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  eldritch: { name: "eldritch", modes: ["dark"], variations: [], fonts: [] },
  elegance: {
    name: "elegance",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["monaco"],
  },
  elysian: {
    name: "elysian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  emerald: {
    name: "emerald",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "emerald-echo": {
    name: "emerald-echo",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "emerald-synth": {
    name: "emerald-synth",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  emrald: {
    name: "emrald",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  encore: {
    name: "encore",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "enhanced-file-explorer-tree": {
    name: "enhanced-file-explorer-tree",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ethereon: {
    name: "ethereon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  evangelion: {
    name: "evangelion",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  everblush: { name: "everblush", modes: ["dark"], variations: [], fonts: [] },
  everforest: {
    name: "everforest",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["hack"],
  },
  "everforest-enchanted": {
    name: "everforest-enchanted",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "everforest-spruce": {
    name: "everforest-spruce",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "evergreen-shadow": {
    name: "evergreen-shadow",
    modes: ["dark"],
    variations: [],
    fonts: ["noto-sans-old-persian", "noto-serif-kr"],
  },
  evilred: {
    name: "evilred",
    modes: ["dark"],
    variations: [],
    fonts: ["hack"],
  },
  exotic: { name: "exotic", modes: ["dark"], variations: [], fonts: [] },
  faded: { name: "faded", modes: ["dark"], variations: [], fonts: [] },
  "fancy-a-story": {
    name: "fancy-a-story",
    modes: ["dark", "light"],
    variations: [],
    fonts: [
      "chakra-petch",
      "limelight",
      "noto-serif",
      "orbitron",
      "playfair-display",
      "walter-turncoat",
    ],
  },
  fastppuccin: {
    name: "fastppuccin",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["noto-serif"],
  },
  feather: {
    name: "feather",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  firefly: { name: "firefly", modes: ["dark"], variations: [], fonts: [] },
  fjord: { name: "fjord", modes: ["dark", "light"], variations: [], fonts: [] },
  "flamingo-noir": {
    name: "flamingo-noir",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  flatcap: { name: "flatcap", modes: ["dark"], variations: [], fonts: [] },
  flexcyon: {
    name: "flexcyon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "flexcyon.tui": {
    name: "flexcyon.tui",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  flexoki: {
    name: "flexoki",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "flexoki-warm": {
    name: "flexoki-warm",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  focus: {
    name: "focus",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  folio: { name: "folio", modes: ["dark", "light"], variations: [], fonts: [] },
  "forest-phosphor": {
    name: "forest-phosphor",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  framer: {
    name: "framer",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  freecolors: {
    name: "freecolors",
    modes: ["light", "dark"],
    variations: [],
    fonts: [],
  },
  friendly: {
    name: "friendly",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  frost: {
    name: "frost",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "roboto"],
  },
  fusion: {
    name: "fusion",
    modes: ["light", "light"],
    variations: [],
    fonts: [],
  },
  future: {
    name: "future",
    modes: ["light", "light"],
    variations: [],
    fonts: [],
  },
  "garden-gnome-adwaita-gtk": {
    name: "garden-gnome-adwaita-gtk",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  gastown: { name: "gastown", modes: ["light"], variations: [], fonts: [] },
  gdct: {
    name: "gdct",
    modes: ["light"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco"],
  },
  "gdct-dark": {
    name: "gdct-dark",
    modes: ["dark"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco"],
  },
  "github-dark-dimmed": {
    name: "github-dark-dimmed",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "github-flavored-markdown": {
    name: "github-flavored-markdown",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "github-theme": {
    name: "github-theme",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  githubdhc: {
    name: "githubdhc",
    modes: ["dark"],
    variations: [],
    fonts: ["fira-code", "noto-sans"],
  },
  gitsidian: {
    name: "gitsidian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "glass-robo": {
    name: "glass-robo",
    modes: ["dark"],
    variations: [],
    fonts: ["figtree", "jetbrains-mono"],
  },
  glassmind: {
    name: "glassmind",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "golden-coffee": {
    name: "golden-coffee",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "golden-topaz": {
    name: "golden-topaz",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lucida-handwriting", "monaco"],
  },
  "green-holiday": {
    name: "green-holiday",
    modes: ["light", "dark"],
    variations: [],
    fonts: [],
  },
  "green-nightmare": {
    name: "green-nightmare",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "grounded-tierra": {
    name: "grounded-tierra",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "gruber-darker": {
    name: "gruber-darker",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  gummy: { name: "gummy", modes: ["dark"], variations: [], fonts: [] },
  "gummy-revived": {
    name: "gummy-revived",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["peace-sans", "space-grotesk"],
  },
  hackthebox: {
    name: "hackthebox",
    modes: ["dark"],
    variations: [],
    fonts: ["open-sans"],
  },
  halcyon: { name: "halcyon", modes: ["dark"], variations: [], fonts: [] },
  "half-life": {
    name: "half-life",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  hanabi: {
    name: "hanabi",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "handwriting-kalam": {
    name: "handwriting-kalam",
    modes: ["light"],
    variations: [],
    fonts: ["courier-prime", "kalam"],
  },
  "happy-coding": {
    name: "happy-coding",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "harbor-dark": {
    name: "harbor-dark",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  harmonic: {
    name: "harmonic",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  heboric: {
    name: "heboric",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto": {
    name: "hidden-grotto",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.absol": {
    name: "hidden-grotto.absol",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.aegislash": {
    name: "hidden-grotto.aegislash",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.aggron": {
    name: "hidden-grotto.aggron",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.arcanine": {
    name: "hidden-grotto.arcanine",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.aromatisse": {
    name: "hidden-grotto.aromatisse",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.calyrex": {
    name: "hidden-grotto.calyrex",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.cryogonal": {
    name: "hidden-grotto.cryogonal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.darkrai": {
    name: "hidden-grotto.darkrai",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.diancie": {
    name: "hidden-grotto.diancie",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.hisuian-typhlosion": {
    name: "hidden-grotto.hisuian-typhlosion",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.manectric": {
    name: "hidden-grotto.manectric",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.mareep": {
    name: "hidden-grotto.mareep",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.mega-lucario": {
    name: "hidden-grotto.mega-lucario",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.meloetta": {
    name: "hidden-grotto.meloetta",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.necrozma": {
    name: "hidden-grotto.necrozma",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.pirouette-meloetta": {
    name: "hidden-grotto.pirouette-meloetta",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.poltchageist": {
    name: "hidden-grotto.poltchageist",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.scolipede": {
    name: "hidden-grotto.scolipede",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.swampert": {
    name: "hidden-grotto.swampert",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "hidden-grotto.ursaluna": {
    name: "hidden-grotto.ursaluna",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  higlighter: {
    name: "higlighter",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  hipstersmoothie: {
    name: "hipstersmoothie",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  hojicha: { name: "hojicha", modes: ["dark"], variations: [], fonts: [] },
  horizon: { name: "horizon", modes: ["dark"], variations: [], fonts: [] },
  hoverpopup: {
    name: "hoverpopup",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  hulk: { name: "hulk", modes: ["dark"], variations: [], fonts: ["monaco"] },
  "hydra-pressure": {
    name: "hydra-pressure",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "ia-writer": {
    name: "ia-writer",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-duo"],
  },
  "ib-writer": {
    name: "ib-writer",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-quattro"],
  },
  iceberg: { name: "iceberg", modes: ["dark"], variations: [], fonts: [] },
  "improved-potato": {
    name: "improved-potato",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "infosecwarrior-ui": {
    name: "infosecwarrior-ui",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ink: { name: "ink", modes: ["light"], variations: [], fonts: [] },
  ion: { name: "ion", modes: ["dark"], variations: [], fonts: [] },
  iridium: {
    name: "iridium",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "its-theme": {
    name: "its-theme",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.blue": {
    name: "its-theme.blue",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.drowned": {
    name: "its-theme.drowned",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.gray": {
    name: "its-theme.gray",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.its-dark": {
    name: "its-theme.its-dark",
    modes: ["dark"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.minimalist": {
    name: "its-theme.minimalist",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.nord": {
    name: "its-theme.nord",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.notion": {
    name: "its-theme.notion",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.rainbow": {
    name: "its-theme.rainbow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.school-days": {
    name: "its-theme.school-days",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.tangerine-dunes": {
    name: "its-theme.tangerine-dunes",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.ttrpg-dnd": {
    name: "its-theme.ttrpg-dnd",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.ttrpg-pathfinder": {
    name: "its-theme.ttrpg-pathfinder",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.ttrpg-pathfinder-remastered": {
    name: "its-theme.ttrpg-pathfinder-remastered",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "its-theme.ttrpg-wotc": {
    name: "its-theme.ttrpg-wotc",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  "jolly-holly": {
    name: "jolly-holly",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  jotter: {
    name: "jotter",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  kakano: {
    name: "kakano",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.black": {
    name: "kakano.black",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.cyan": {
    name: "kakano.cyan",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.green": {
    name: "kakano.green",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.grey": {
    name: "kakano.grey",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.orange": {
    name: "kakano.orange",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.pink": {
    name: "kakano.pink",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.purple": {
    name: "kakano.purple",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.red": {
    name: "kakano.red",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.white": {
    name: "kakano.white",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  "kakano.yellow": {
    name: "kakano.yellow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono"],
  },
  kanagawa: {
    name: "kanagawa",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["hack"],
  },
  "kanagawa-palette": {
    name: "kanagawa-palette",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "kanagawa-paper": {
    name: "kanagawa-paper",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["hack"],
  },
  karadigm: {
    name: "karadigm",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "kiwi-mono": {
    name: "kiwi-mono",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cascadia-mono"],
  },
  kurokula: {
    name: "kurokula",
    modes: ["dark"],
    variations: [],
    fonts: ["atkinson-hyperlegible", "jetbrains-mono"],
  },
  "kxc-cipher": {
    name: "kxc-cipher",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  lagom: {
    name: "lagom",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["formular"],
  },
  latex: {
    name: "latex",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["computer-modern-bright"],
  },
  latsidian: {
    name: "latsidian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "lavender-mist": {
    name: "lavender-mist",
    modes: ["light"],
    variations: [],
    fonts: ["noto-serif-kr"],
  },
  "lemons-theme": {
    name: "lemons-theme",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  lesswrong: {
    name: "lesswrong",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "light-bright": {
    name: "light-bright",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lato", "roboto", "work-sans"],
  },
  listive: {
    name: "listive",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["courgette", "karla", "open-sans"],
  },
  litos: { name: "litos", modes: ["dark", "light"], variations: [], fonts: [] },
  "lizardmen-zettelkasten": {
    name: "lizardmen-zettelkasten",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  lorens: { name: "lorens", modes: ["dark"], variations: [], fonts: [] },
  lumen: { name: "lumen", modes: ["dark", "light"], variations: [], fonts: [] },
  lumines: {
    name: "lumines",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "lyt-mode": {
    name: "lyt-mode",
    modes: ["dark"],
    variations: [],
    fonts: ["dm-mono", "dm-sans", "fira-code"],
  },
  macos: { name: "macos", modes: ["dark", "light"], variations: [], fonts: [] },
  "mado-11": {
    name: "mado-11",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "mado-miniflow": {
    name: "mado-miniflow",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  magicuser: {
    name: "magicuser",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  makinda: {
    name: "makinda",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  mammoth: { name: "mammoth", modes: ["dark"], variations: [], fonts: [] },
  manuscript: {
    name: "manuscript",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  maple: {
    name: "maple",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["maple-mono"],
  },
  "maple.default": {
    name: "maple.default",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["maple-mono"],
  },
  "maple.minimal": {
    name: "maple.minimal",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["maple-mono"],
  },
  marathon: {
    name: "marathon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "material-3": {
    name: "material-3",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto"],
  },
  "material-3-expressive": {
    name: "material-3-expressive",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "material-flat": {
    name: "material-flat",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "roboto-mono"],
  },
  "material-gruvbox": {
    name: "material-gruvbox",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "material-ocean": {
    name: "material-ocean",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  matrix: { name: "matrix", modes: ["dark"], variations: [], fonts: [] },
  meridian: {
    name: "meridian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "miami-wind": {
    name: "miami-wind",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "micro-mike": {
    name: "micro-mike",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  midnight: { name: "midnight", modes: ["dark"], variations: [], fonts: [] },
  "midnight-fjord": {
    name: "midnight-fjord",
    modes: ["dark"],
    variations: [],
    fonts: ["finlandica"],
  },
  "milk-tea": {
    name: "milk-tea",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  minimal: {
    name: "minimal",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto"],
  },
  "minimal-dark-coder": {
    name: "minimal-dark-coder",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "minimal-dracula": {
    name: "minimal-dracula",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "minimal-edge": {
    name: "minimal-edge",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto"],
  },
  "minimal-red": {
    name: "minimal-red",
    modes: ["dark"],
    variations: [],
    fonts: ["geist"],
  },
  "minimal-resources": {
    name: "minimal-resources",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "minimalist-studio": {
    name: "minimalist-studio",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "minimalists-paradise": {
    name: "minimalists-paradise",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["fira-code"],
  },
  "mint-breeze": {
    name: "mint-breeze",
    modes: ["light"],
    variations: [],
    fonts: ["noto-sans-old-persian", "noto-serif-kr"],
  },
  mistymauve: {
    name: "mistymauve",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["arvo", "permanent-marker"],
  },
  "modern-dark": {
    name: "modern-dark",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "modern-genz-vibedose": {
    name: "modern-genz-vibedose",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jost", "satoshi", "syne", "jetbrains-mono"],
  },
  molecule: { name: "molecule", modes: ["dark"], variations: [], fonts: [] },
  "monkey-king": {
    name: "monkey-king",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "mono-black-monochrome-charcoal": {
    name: "mono-black-monochrome-charcoal",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "mono-high-contrast": {
    name: "mono-high-contrast",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["fira-code"],
  },
  monochroyou: {
    name: "monochroyou",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  monokai: {
    name: "monokai",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "monokai-filtersun-spectrum": {
    name: "monokai-filtersun-spectrum",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "monokai-ristretto": {
    name: "monokai-ristretto",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "monokai-syntax": {
    name: "monokai-syntax",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  moonlight: {
    name: "moonlight",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "mulled-wine": {
    name: "mulled-wine",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "museifu-basic": {
    name: "museifu-basic",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  mushin: {
    name: "mushin",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "muted-blue": {
    name: "muted-blue",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  myst: {
    name: "myst",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/material-symbols-outlined", "s-core-dream-3-light"],
  },
  nebula: {
    name: "nebula",
    modes: ["dark"],
    variations: [],
    fonts: ["montserrat"],
  },
  nebulux: {
    name: "nebulux",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  neo: {
    name: "neo",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "neo-sploosh": {
    name: "neo-sploosh",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "neon-dracula": {
    name: "neon-dracula",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "neon-synthwave": {
    name: "neon-synthwave",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  neovim: {
    name: "neovim",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nerv: { name: "nerv", modes: ["dark", "light"], variations: [], fonts: [] },
  neuborder: { name: "neuborder", modes: ["light"], variations: [], fonts: [] },
  neumorphism: {
    name: "neumorphism",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "neutral-academia": {
    name: "neutral-academia",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cormorant", "manrope"],
  },
  nichneumor: {
    name: "nichneumor",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nier: { name: "nier", modes: ["dark"], variations: [], fonts: [] },
  "night-owl": {
    name: "night-owl",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nightfox: {
    name: "nightfox",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nightingale: {
    name: "nightingale",
    modes: ["dark"],
    variations: [],
    fonts: ["inconsolata", "noto-sans"],
  },
  "nightly-wolf": {
    name: "nightly-wolf",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nobb: { name: "nobb", modes: ["dark"], variations: [], fonts: [] },
  noctilux: { name: "noctilux", modes: ["dark"], variations: [], fonts: [] },
  noctis: { name: "noctis", modes: ["dark"], variations: [], fonts: [] },
  "noctis-family": {
    name: "noctis-family",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "noctis-viola": {
    name: "noctis-viola",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nord: { name: "nord", modes: ["dark", "light"], variations: [], fonts: [] },
  nordic: {
    name: "nordic",
    modes: ["light"],
    variations: [],
    fonts: ["deadhead-script", "gentium-book-basic", "norwester"],
  },
  "northern-sky": {
    name: "northern-sky",
    modes: ["light"],
    variations: [],
    fonts: ["finlandica"],
  },
  nostromo: {
    name: "nostromo",
    modes: ["dark"],
    variations: [],
    fonts: ["share-tech-mono", "vt323"],
  },
  "nota-limonada-light": {
    name: "nota-limonada-light",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  notation: {
    name: "notation",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "notation-2": {
    name: "notation-2",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lyons-serif", "ia-writer-duospace"],
  },
  nothing: {
    name: "nothing",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "notion-style": {
    name: "notion-style",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  notswift: {
    name: "notswift",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto", "sf-mono", "sf-pro-display"],
  },
  "nott-dagr": {
    name: "nott-dagr",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  nous: { name: "nous", modes: ["dark", "light"], variations: [], fonts: [] },
  novadust: { name: "novadust", modes: ["dark"], variations: [], fonts: [] },
  novel: { name: "novel", modes: ["dark", "light"], variations: [], fonts: [] },
  nyan: { name: "nyan", modes: ["dark", "light"], variations: [], fonts: [] },
  "obsdn-dark-rmx": {
    name: "obsdn-dark-rmx",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "obsiddy-in-terminal": {
    name: "obsiddy-in-terminal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  obsidian: {
    name: "obsidian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  obsidian_ia: {
    name: "obsidian_ia",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-mono", "ia-writer-quattro"],
  },
  obsidian_vibrant: {
    name: "obsidian_vibrant",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "obsidian-boom": {
    name: "obsidian-boom",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  "obsidian-gruvbox": {
    name: "obsidian-gruvbox",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "obsidian-nord": {
    name: "obsidian-nord",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "obsidian-nord-enhanced": {
    name: "obsidian-nord-enhanced",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "obsidian-windows-98-edition": {
    name: "obsidian-windows-98-edition",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "obsidian-you": {
    name: "obsidian-you",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  obsidianite: {
    name: "obsidianite",
    modes: ["dark"],
    variations: [],
    fonts: ["rubik", "space-mono"],
  },
  obsidianotion: {
    name: "obsidianotion",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["fira-code", "ia-writer-quattro", "ibm-plex-sans"],
  },
  obuntu: {
    name: "obuntu",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  oistnb: {
    name: "oistnb",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  okudagram: {
    name: "okudagram",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "old-world": {
    name: "old-world",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "oldsidian-purple": {
    name: "oldsidian-purple",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  oledblack: { name: "oledblack", modes: ["dark"], variations: [], fonts: [] },
  "oliviers-theme": {
    name: "oliviers-theme",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  omega: { name: "omega", modes: ["dark"], variations: [], fonts: [] },
  "one-oracle-developer": {
    name: "one-oracle-developer",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  onenice: {
    name: "onenice",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "ono-sendai": {
    name: "ono-sendai",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cairo", "fira-code"],
  },
  orange: {
    name: "orange",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  oreo: { name: "oreo", modes: ["dark", "light"], variations: [], fonts: [] },
  origami: {
    name: "origami",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.abaddon": {
    name: "origami.abaddon",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.dracula": {
    name: "origami.dracula",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.eidolon": {
    name: "origami.eidolon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.gruvbox": {
    name: "origami.gruvbox",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.heckhound": {
    name: "origami.heckhound",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.linking-your-thinking": {
    name: "origami.linking-your-thinking",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.minimum": {
    name: "origami.minimum",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.nano": {
    name: "origami.nano",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.shadow": {
    name: "origami.shadow",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.shark-time": {
    name: "origami.shark-time",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.siren": {
    name: "origami.siren",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "origami.soft": {
    name: "origami.soft",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.solarized": {
    name: "origami.solarized",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.sorcery": {
    name: "origami.sorcery",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "origami.umbra": {
    name: "origami.umbra",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  origin: {
    name: "origin",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "osaka-jade": {
    name: "osaka-jade",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  oscura: {
    name: "oscura",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  ouroboros: {
    name: "ouroboros",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  overcast: { name: "overcast", modes: ["dark"], variations: [], fonts: [] },
  "owen-graphite": {
    name: "owen-graphite",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  oxygen: {
    name: "oxygen",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  palatinate: {
    name: "palatinate",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  pale: { name: "pale", modes: ["dark", "light"], variations: [], fonts: [] },
  palenight: {
    name: "palenight",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "panda-syntax": {
    name: "panda-syntax",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "panic-mode": {
    name: "panic-mode",
    modes: ["dark"],
    variations: [],
    fonts: ["ia-writer-quattro-s", "monaco"],
  },
  panorama: {
    name: "panorama",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "papyrus-nox": {
    name: "papyrus-nox",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  parfait: { name: "parfait", modes: ["light"], variations: [], fonts: [] },
  "pastel-yumekawa": {
    name: "pastel-yumekawa",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  pensea: {
    name: "pensea",
    modes: ["light", "dark"],
    variations: [],
    fonts: [],
  },
  penumbra: {
    name: "penumbra",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  perso: { name: "perso", modes: ["light"], variations: [], fonts: [] },
  phoenix: {
    name: "phoenix",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "sf-pro-display"],
  },
  phosphor: {
    name: "phosphor",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "phosphor-crt": {
    name: "phosphor-crt",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "phosphor-mono": {
    name: "phosphor-mono",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "pine-forest-berry": {
    name: "pine-forest-berry",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["inconsolata"],
  },
  "pink-muted-rose": {
    name: "pink-muted-rose",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "pink-topaz": {
    name: "pink-topaz",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lucida-handwriting", "monaco"],
  },
  pisum: { name: "pisum", modes: ["dark"], variations: [], fonts: ["monaco"] },
  "pitch-black": {
    name: "pitch-black",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  planetary: {
    name: "planetary",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-sans"],
  },
  "planetz-roller": {
    name: "planetz-roller",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  playground: {
    name: "playground",
    modes: ["dark"],
    variations: [],
    fonts: ["bricolage-grotesque"],
  },
  pln: { name: "pln", modes: ["dark", "light"], variations: [], fonts: [] },
  poimandres: {
    name: "poimandres",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "poimandres-extended": {
    name: "poimandres-extended",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  polka: {
    name: "polka",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["rubik", "ibm-plex-mono"],
  },
  "pomme-notes": {
    name: "pomme-notes",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "powered-by-lancer": {
    name: "powered-by-lancer",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["arimo", "anonymous-pro"],
  },
  "powered-by-lancer-retouched": {
    name: "powered-by-lancer-retouched",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["arimo"],
  },
  primary: {
    name: "primary",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cascadia-code"],
  },
  prime: { name: "prime", modes: ["dark", "light"], variations: [], fonts: [] },
  prism: {
    name: "prism",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "source-sans-3"],
  },
  "proper-dark": {
    name: "proper-dark",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  prose: { name: "prose", modes: ["dark", "light"], variations: [], fonts: [] },
  protocolblue: {
    name: "protocolblue",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "prussian-blue": {
    name: "prussian-blue",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  publisher: {
    name: "publisher",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lato"],
  },
  pure: { name: "pure", modes: ["dark", "light"], variations: [], fonts: [] },
  "purple-aurora": {
    name: "purple-aurora",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "purple-owl": {
    name: "purple-owl",
    modes: ["dark"],
    variations: [],
    fonts: ["monaspace-argon"],
  },
  pxld: { name: "pxld", modes: ["dark", "light"], variations: [], fonts: [] },
  qlean: {
    name: "qlean",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-mono", "noto-sans-jp"],
  },
  "quest-journal": {
    name: "quest-journal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  quietus: {
    name: "quietus",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  quillcode: {
    name: "quillcode",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  radiance: {
    name: "radiance",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "rain-washed-sky": {
    name: "rain-washed-sky",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  rationale: {
    name: "rationale",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ravenloft: {
    name: "ravenloft",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["literata", "open-sans", "ruslan-display", "vollkorn"],
  },
  rbr: { name: "rbr", modes: ["dark"], variations: [], fonts: [] },
  "red-graphite": {
    name: "red-graphite",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "red-shadow": {
    name: "red-shadow",
    modes: ["dark"],
    variations: [],
    fonts: ["fira-code", "montserrat"],
  },
  "red-solitude": {
    name: "red-solitude",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "redshift-oled-blue-light-filter": {
    name: "redshift-oled-blue-light-filter",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "refined-default": {
    name: "refined-default",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  reshi: {
    name: "reshi",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "noto-sans"],
  },
  "retro-larper": {
    name: "retro-larper",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retro-terminal": {
    name: "retro-terminal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retro-windows": {
    name: "retro-windows",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  retroma: {
    name: "retroma",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.analogous-reversed": {
    name: "retroma.analogous-reversed",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.monochromatic": {
    name: "retroma.monochromatic",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.monochromatic-reversed": {
    name: "retroma.monochromatic-reversed",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.split-complementary": {
    name: "retroma.split-complementary",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.split-complementary-reversed": {
    name: "retroma.split-complementary-reversed",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.triadic": {
    name: "retroma.triadic",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "retroma.triadic-reversed": {
    name: "retroma.triadic-reversed",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  retronotes: {
    name: "retronotes",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retronotes.blueprint": {
    name: "retronotes.blueprint",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retronotes.carbon-ink": {
    name: "retronotes.carbon-ink",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retronotes.forest-green": {
    name: "retronotes.forest-green",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retronotes.misty-mirage": {
    name: "retronotes.misty-mirage",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retronotes.pinot-noir": {
    name: "retronotes.pinot-noir",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ibm-plex-mono"],
  },
  "retroos-98": {
    name: "retroos-98",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["libre-franklin"],
  },
  reverie: {
    name: "reverie",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  rezin: { name: "rezin", modes: ["dark"], variations: [], fonts: [] },
  ribbons: {
    name: "ribbons",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["icons/its"],
  },
  rift: { name: "rift", modes: ["dark"], variations: [], fonts: [] },
  rmaki: {
    name: "rmaki",
    modes: ["dark"],
    variations: [],
    fonts: ["fira-code"],
  },
  robsi: {
    name: "robsi",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "rose-pine": {
    name: "rose-pine",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "rose-pine-2": {
    name: "rose-pine-2",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "rose-pine-minimal": {
    name: "rose-pine-minimal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "rose-pine-moon": {
    name: "rose-pine-moon",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "rose-red": {
    name: "rose-red",
    modes: ["dark"],
    variations: [],
    fonts: ["hack"],
  },
  "royal-velvet": {
    name: "royal-velvet",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["fira-sans", "fira-code"],
  },
  ruby: { name: "ruby", modes: ["dark", "light"], variations: [], fonts: [] },
  "sacred-geometry-systems": {
    name: "sacred-geometry-systems",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "sad-machine-druid": {
    name: "sad-machine-druid",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["hack"],
  },
  "saint-red-paper": {
    name: "saint-red-paper",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  sakurajima: {
    name: "sakurajima",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  salem: { name: "salem", modes: ["dark", "light"], variations: [], fonts: [] },
  sanctum: {
    name: "sanctum",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn": {
    name: "sanctum-reborn",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.blue": {
    name: "sanctum-reborn.blue",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.cyan": {
    name: "sanctum-reborn.cyan",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.green": {
    name: "sanctum-reborn.green",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.lavender": {
    name: "sanctum-reborn.lavender",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.orange": {
    name: "sanctum-reborn.orange",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.pink": {
    name: "sanctum-reborn.pink",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.pistachio": {
    name: "sanctum-reborn.pistachio",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.red": {
    name: "sanctum-reborn.red",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.viridian": {
    name: "sanctum-reborn.viridian",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum-reborn.yellow": {
    name: "sanctum-reborn.yellow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.blue": {
    name: "sanctum.blue",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.cyan": {
    name: "sanctum.cyan",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.green": {
    name: "sanctum.green",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.lavender": {
    name: "sanctum.lavender",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.orange": {
    name: "sanctum.orange",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.pink": {
    name: "sanctum.pink",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.pistachio": {
    name: "sanctum.pistachio",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.red": {
    name: "sanctum.red",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.viridian": {
    name: "sanctum.viridian",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  "sanctum.yellow": {
    name: "sanctum.yellow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono"],
  },
  sandover: {
    name: "sandover",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["special-elite"],
  },
  sandstorm: {
    name: "sandstorm",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["flow-circular"],
  },
  sanguine: {
    name: "sanguine",
    modes: ["dark"],
    variations: [],
    fonts: ["slasher-film"],
  },
  scriptorium: {
    name: "scriptorium",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["slasher-film"],
  },
  "sea-glass": {
    name: "sea-glass",
    modes: ["dark"],
    variations: [],
    fonts: ["euclid-circular-a", "hack"],
  },
  "seamless-view": {
    name: "seamless-view",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  sei: { name: "sei", modes: ["dark", "light"], variations: [], fonts: [] },
  sequoia: {
    name: "sequoia",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  serendipity: {
    name: "serendipity",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  serenity: {
    name: "serenity",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-duo", "ia-writer-mono", "ia-writer-quattro-s"],
  },
  serif: { name: "serif", modes: ["dark", "light"], variations: [], fonts: [] },
  serika: {
    name: "serika",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "shade-sanctuary": {
    name: "shade-sanctuary",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["computer-modern-bright", "jetbrains-mono"],
  },
  shadeflow: {
    name: "shadeflow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["geist", "geist-mono"],
  },
  "shiba-inu": {
    name: "shiba-inu",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "shimmering-focus": {
    name: "shimmering-focus",
    modes: ["dark", "light"],
    variations: [],
    fonts: [
      "ia-writer-quattro-s",
      "eb-garamond",
      "optima",
      "recursive",
      "icons/material-icons",
    ],
  },
  silence: { name: "silence", modes: ["dark"], variations: [], fonts: [] },
  silver: {
    name: "silver",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  simple: {
    name: "simple",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-quattro", "fira-code", "ibm-plex-sans"],
  },
  "simple-color": {
    name: "simple-color",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  simplicity: {
    name: "simplicity",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "simply-colorful": {
    name: "simply-colorful",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto"],
  },
  slatewave: { name: "slatewave", modes: ["dark"], variations: [], fonts: [] },
  slytherin: { name: "slytherin", modes: ["dark"], variations: [], fonts: [] },
  sodalite: { name: "sodalite", modes: ["dark"], variations: [], fonts: [] },
  "soft-paper": {
    name: "soft-paper",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  solarized: {
    name: "solarized",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "soli-deo-gloria": {
    name: "soli-deo-gloria",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cormorant", "germania-one"],
  },
  solitude: {
    name: "solitude",
    modes: ["dark"],
    variations: [],
    fonts: ["fira-code"],
  },
  soloing: {
    name: "soloing",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  soothe: {
    name: "soothe",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  sora: { name: "sora", modes: ["dark"], variations: [], fonts: [] },
  space: {
    name: "space",
    modes: ["dark"],
    variations: [],
    fonts: ["bai-jamjuree", "orbitron", "unbounded"],
  },
  "sparkling-day": {
    name: "sparkling-day",
    modes: ["light"],
    variations: [],
    fonts: [],
  },
  "sparkling-night": {
    name: "sparkling-night",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "sparkling-wisdom": {
    name: "sparkling-wisdom",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["flow-circular", "open-sans"],
  },
  spectrum: {
    name: "spectrum",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "spectrum-blue": {
    name: "spectrum-blue",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono", "roboto"],
  },
  spectrumplus: {
    name: "spectrumplus",
    modes: ["dark"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  spring: {
    name: "spring",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["apercu-pro"],
  },
  "spy-terminal": {
    name: "spy-terminal",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["sf-mono", "roboto-mono"],
  },
  sqdthone: {
    name: "sqdthone",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cascadia-code", "source-sans-pro"],
  },
  "standard-plus": {
    name: "standard-plus",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "starlit-abyss": {
    name: "starlit-abyss",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  strict: { name: "strict", modes: ["dark"], variations: [], fonts: [] },
  subtlegold: {
    name: "subtlegold",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["flow-circular", "sf-mono"],
  },
  suddha: {
    name: "suddha",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["monaco", "roboto"],
  },
  sunbather: {
    name: "sunbather",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["roboto"],
  },
  superflat: {
    name: "superflat",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  synthwave: { name: "synthwave", modes: ["dark"], variations: [], fonts: [] },
  "synthwave-84": {
    name: "synthwave-84",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "synthwave-pro": {
    name: "synthwave-pro",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  tech001: {
    name: "tech001",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  terminal: {
    name: "terminal",
    modes: ["dark"],
    variations: [],
    fonts: ["fira-code"],
  },
  terminal2k: {
    name: "terminal2k",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  terraflow: {
    name: "terraflow",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "theme-that-shall-not-be-named": {
    name: "theme-that-shall-not-be-named",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  things: {
    name: "things",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "roboto"],
  },
  "things-3": {
    name: "things-3",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["formular"],
  },
  tiniri: {
    name: "tiniri",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "tokyo-night": {
    name: "tokyo-night",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono"],
  },
  "tokyo-night-simple": {
    name: "tokyo-night-simple",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "tokyo-night-storm": {
    name: "tokyo-night-storm",
    modes: ["dark"],
    variations: [],
    fonts: ["anonymous-pro", "jetbrains-mono"],
  },
  tomorrow: { name: "tomorrow", modes: ["dark"], variations: [], fonts: [] },
  "tomorrow-night-bright": {
    name: "tomorrow-night-bright",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "toms-theme": {
    name: "toms-theme",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "trace-labs": {
    name: "trace-labs",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "traffic-lights": {
    name: "traffic-lights",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  transient: { name: "transient", modes: ["dark"], variations: [], fonts: [] },
  transparent: {
    name: "transparent",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "true-black": {
    name: "true-black",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  typewriter: {
    name: "typewriter",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["ia-writer-mono", "ia-writer-quattro-s", "jetbrains-mono"],
  },
  typomagical: {
    name: "typomagical",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["alegreya", "amiri", "bitter", "playfair-display", "spectral"],
  },
  "typora-vue": {
    name: "typora-vue",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "tyrone-neon": {
    name: "tyrone-neon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ukiyo: {
    name: "ukiyo",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ukiyo.alchemy": {
    name: "ukiyo.alchemy",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ukiyo.golden-book": {
    name: "ukiyo.golden-book",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ukiyo.golden-coffee": {
    name: "ukiyo.golden-coffee",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ukiyo.rose-shadow": {
    name: "ukiyo.rose-shadow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ukiyo.ukiyo": {
    name: "ukiyo.ukiyo",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["cmu-typewriter-text", "jetbrains-mono"],
  },
  "ultra-lobster": {
    name: "ultra-lobster",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.abaddon": {
    name: "ultra-lobster.abaddon",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.abaddon-glass": {
    name: "ultra-lobster.abaddon-glass",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.architect": {
    name: "ultra-lobster.architect",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.blahaj": {
    name: "ultra-lobster.blahaj",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.blueprint": {
    name: "ultra-lobster.blueprint",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.bunny": {
    name: "ultra-lobster.bunny",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.chameleon": {
    name: "ultra-lobster.chameleon",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.control": {
    name: "ultra-lobster.control",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.creation": {
    name: "ultra-lobster.creation",
    modes: ["light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.cyan": {
    name: "ultra-lobster.cyan",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.demon-queen": {
    name: "ultra-lobster.demon-queen",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.dracula": {
    name: "ultra-lobster.dracula",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.eidolon": {
    name: "ultra-lobster.eidolon",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.green": {
    name: "ultra-lobster.green",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.gruvbox": {
    name: "ultra-lobster.gruvbox",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.linking-your-thinking": {
    name: "ultra-lobster.linking-your-thinking",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.lobster-time": {
    name: "ultra-lobster.lobster-time",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.orange": {
    name: "ultra-lobster.orange",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.pink": {
    name: "ultra-lobster.pink",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.purple": {
    name: "ultra-lobster.purple",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.red": {
    name: "ultra-lobster.red",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.shadow": {
    name: "ultra-lobster.shadow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.soft": {
    name: "ultra-lobster.soft",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.solarized": {
    name: "ultra-lobster.solarized",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.sorcery": {
    name: "ultra-lobster.sorcery",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.succubus": {
    name: "ultra-lobster.succubus",
    modes: ["dark"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.timberwolf": {
    name: "ultra-lobster.timberwolf",
    modes: ["light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.umbra": {
    name: "ultra-lobster.umbra",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.white": {
    name: "ultra-lobster.white",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  "ultra-lobster.yellow": {
    name: "ultra-lobster.yellow",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["nightingale", "monaspace-neon"],
  },
  underwater: {
    name: "underwater",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["lexend"],
  },
  universitario: {
    name: "universitario",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  ursa: { name: "ursa", modes: ["dark", "light"], variations: [], fonts: [] },
  "utility-materials": {
    name: "utility-materials",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-amoled": {
    name: "vanilla-amoled",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "vanilla-amoled-color": {
    name: "vanilla-amoled-color",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes": {
    name: "vanilla-palettes",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.atom-one": {
    name: "vanilla-palettes.atom-one",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.catppuccin-frappe": {
    name: "vanilla-palettes.catppuccin-frappe",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.catppuccin-macchiato": {
    name: "vanilla-palettes.catppuccin-macchiato",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.catppuccin-mocha": {
    name: "vanilla-palettes.catppuccin-mocha",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.dracula": {
    name: "vanilla-palettes.dracula",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.dracula-soft": {
    name: "vanilla-palettes.dracula-soft",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.gruvbox-hard": {
    name: "vanilla-palettes.gruvbox-hard",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.gruvbox-medium": {
    name: "vanilla-palettes.gruvbox-medium",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.gruvbox-soft": {
    name: "vanilla-palettes.gruvbox-soft",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.horizon": {
    name: "vanilla-palettes.horizon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.kanagawa-dragon": {
    name: "vanilla-palettes.kanagawa-dragon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.kanagawa-wave": {
    name: "vanilla-palettes.kanagawa-wave",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.rose-pine": {
    name: "vanilla-palettes.rose-pine",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.rose-pine-moon": {
    name: "vanilla-palettes.rose-pine-moon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.tokyo-night": {
    name: "vanilla-palettes.tokyo-night",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.tokyo-night-moon": {
    name: "vanilla-palettes.tokyo-night-moon",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vanilla-palettes.tokyo-night-storm": {
    name: "vanilla-palettes.tokyo-night-storm",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vaporwave-void": {
    name: "vaporwave-void",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  vauxhall: {
    name: "vauxhall",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.blue": {
    name: "vauxhall.blue",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.magenta": {
    name: "vauxhall.magenta",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.purple": {
    name: "vauxhall.purple",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.red": {
    name: "vauxhall.red",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.teal": {
    name: "vauxhall.teal",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vauxhall.white": {
    name: "vauxhall.white",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  vellum: {
    name: "vellum",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  velocity: {
    name: "velocity",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.british-racing-green": {
    name: "velocity.british-racing-green",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.jet-black-matte": {
    name: "velocity.jet-black-matte",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.midnight-purple": {
    name: "velocity.midnight-purple",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.nordblau-metalic": {
    name: "velocity.nordblau-metalic",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.obsidian-gray": {
    name: "velocity.obsidian-gray",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velocity.touring-bronze": {
    name: "velocity.touring-bronze",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "velvet-moon": {
    name: "velvet-moon",
    modes: ["dark"],
    variations: [],
    fonts: ["finlandica"],
  },
  venom: { name: "venom", modes: ["dark"], variations: [], fonts: [] },
  "vercel-geist": {
    name: "vercel-geist",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["geist", "geist-mono"],
  },
  vermilion: {
    name: "vermilion",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vesnea-vibe": {
    name: "vesnea-vibe",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["josefin-sans", "work-sans"],
  },
  vesper: {
    name: "vesper",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vesper-sandstorm": {
    name: "vesper-sandstorm",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  vibrant: { name: "vibrant", modes: ["dark"], variations: [], fonts: [] },
  vicious: {
    name: "vicious",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  vileplume: {
    name: "vileplume",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "vintage-theme": {
    name: "vintage-theme",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  "violet-evening": {
    name: "violet-evening",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  virgo: { name: "virgo", modes: ["dark", "light"], variations: [], fonts: [] },
  viridian: {
    name: "viridian",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  vision: {
    name: "vision",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  vortex: {
    name: "vortex",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["rubik"],
  },
  "vscode-dark-modern": {
    name: "vscode-dark-modern",
    modes: ["dark"],
    variations: [],
    fonts: [],
  },
  w95: { name: "w95", modes: ["light"], variations: [], fonts: [] },
  "warm-burnout": {
    name: "warm-burnout",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "warm-springs": {
    name: "warm-springs",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  warmth: { name: "warmth", modes: ["dark"], variations: [], fonts: [] },
  wasp: { name: "wasp", modes: ["dark", "light"], variations: [], fonts: [] },
  wikipedia: {
    name: "wikipedia",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["archivo", "linux-libertine"],
  },
  wilcoxone: {
    name: "wilcoxone",
    modes: ["dark"],
    variations: [],
    fonts: ["lato", "fira-code"],
  },
  willemstad: {
    name: "willemstad",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["crimson-pro", "dm-mono", "dm-sans", "manrope", "icons/remixicon"],
  },
  "winter-spices": {
    name: "winter-spices",
    modes: ["light"],
    variations: [],
    fonts: ["myriad-apple"],
  },
  wiselight: {
    name: "wiselight",
    modes: ["light"],
    variations: [],
    fonts: ["karla", "open-sans"],
  },
  wombat: { name: "wombat", modes: ["dark"], variations: [], fonts: [] },
  word_2019: {
    name: "word_2019",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  "wy-console": {
    name: "wy-console",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["audiowide", "dotgothic16"],
  },
  wyrd: {
    name: "wyrd",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["architects-daughter", "neucha", "space-mono"],
  },
  xscriptor: {
    name: "xscriptor",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["eb-garamond"],
  },
  "yin-and-yang": {
    name: "yin-and-yang",
    modes: ["dark", "light"],
    variations: [],
    fonts: [],
  },
  yue: {
    name: "yue",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "roboto"],
  },
  zario: {
    name: "zario",
    modes: ["dark", "light"],
    variations: [],
    fonts: ["jetbrains-mono", "roboto"],
  },
  zen: { name: "zen", modes: ["dark", "light"], variations: [], fonts: [] },
  zenburn: {
    name: "zenburn",
    modes: ["dark"],
    variations: [],
    fonts: ["inconsolata"],
  },
};
