import {
  Pencil,
  ClipboardList,
  Info,
  CircleCheck,
  Flame,
  Check,
  CircleHelp,
  AlertTriangle,
  X,
  Zap,
  Bug,
  List,
  Quote,
  AlertCircle,
  Star,
  Minus,
  Clock4,
  ArrowRight,
  HelpCircle,
  DollarSign,
  Bookmark,
  Scissors,
  CalendarClock,
  Lightbulb,
  Key,
  MapPin,
  Heart,
  ThumbsUp,
  Trophy,
} from "@lucide/icons";
import type { LucideIconData, LucideIconNode } from "@lucide/icons";
import { writeFileSync } from "fs";
import { join } from "path";

function renderNodes(nodes: LucideIconNode[]): string {
  return nodes
    .map((node) => {
      const [tag, attrs, children] = node;
      const attrStr = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${k}="${v}"`)
        .join(" ");
      if (children?.length) {
        return `<${tag} ${attrStr}>${renderNodes(children)}</${tag}>`;
      }
      return `<${tag} ${attrStr}/>`;
    })
    .join("");
}

function getIconSize(icon: LucideIconData): { width: number; height: number } {
  if ("size" in icon) return { width: icon.size, height: icon.size };
  return { width: icon.width, height: icon.height };
}

function toDataUri(icon: LucideIconData): string {
  const { width, height } = getIconSize(icon);
  const children = renderNodes(icon.node);
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" ` +
    `viewBox="0 0 ${width} ${height}" fill="none" stroke="currentColor" ` +
    `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">` +
    `${children}</svg>`;
  const encoded = svg
    .replace(/"/g, "'")
    .replace(/#/g, "%23")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E");
  return `url("data:image/svg+xml;utf8,${encoded}")`;
}

const CALLOUT_ICONS: Record<string, LucideIconData> = {
  note: Pencil,
  abstract: ClipboardList,
  info: Info,
  todo: CircleCheck,
  tip: Flame,
  success: Check,
  question: CircleHelp,
  warning: AlertTriangle,
  failure: X,
  danger: Zap,
  bug: Bug,
  example: List,
  quote: Quote,
};

const CHECKBOX_ICONS: Record<string, LucideIconData> = {
  "!": AlertCircle,
  "*": Star,
  "-": Minus,
  "/": Clock4,
  ">": ArrowRight,
  "?": HelpCircle,
  I: Info,
  S: DollarSign,
  b: Bookmark,
  c: Scissors,
  d: CalendarClock,
  f: Flame,
  i: Lightbulb,
  k: Key,
  l: MapPin,
  p: Heart,
  u: ThumbsUp,
  w: Trophy,
};

const calloutEntries = Object.entries(CALLOUT_ICONS)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(toDataUri(v))}`)
  .join(",\n");

const checkboxEntries = Object.entries(CHECKBOX_ICONS)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(toDataUri(v))}`)
  .join(",\n");

const output = `// AUTO-GENERATED by scripts/generate-icons.ts — do not edit manually
export const CALLOUT_ICON_URIS: Record<string, string> = {
${calloutEntries},
};

export const CALLOUT_ALIASES: Record<string, string> = {
  summary: "abstract",
  tldr: "abstract",
  hint: "tip",
  important: "tip",
  check: "success",
  done: "success",
  help: "question",
  faq: "question",
  caution: "warning",
  attention: "warning",
  fail: "failure",
  missing: "failure",
  error: "danger",
  cite: "quote",
};

export const CHECKBOX_ICON_URIS: Record<string, string> = {
${checkboxEntries},
};
`;

const outPath = join(
  import.meta.dirname!,
  "..",
  "src",
  "icons",
  "generated.ts",
);
writeFileSync(outPath, output, "utf-8");
console.log("Generated:", outPath);
