import {
  getValueFromDictionary,
  readJsonFileAsDictionary,
  getCurrentFolder,
} from "./util/util.mjs";

export const testMode = true;
export const staticMode = true;
export const themeToTest = "Sanguine";

export const themes = getValueFromDictionary(
  readJsonFileAsDictionary(getCurrentFolder(), "themes.json"),
  "themes",
);

export const usedRules = [
  // General
  ":root",
  "body",
  // Headings
  "h1 a",
  "h2 a",
  "h3 a",
  "h4 a",
  "h5 a",
  "h6 a",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  // Code blocks
  "pre",
  "code",
  "pre code",
  "button.copy-code-button",
  "button.copy-code-button:hover",
  // Callouts
  ".callout",
  ".callout-title",
  ".callout-title-inner",
  ".callout-content",
  '.callout[data-callout="tip"]',
  '.callout[data-callout="warning"]',
  '.callout[data-callout="danger"]',
  '.callout[data-callout="abstract"]',
  '.callout[data-callout="todo"]',
  '.callout[data-callout="question"]',
  '.callout[data-callout="info"]',
  '.callout[data-callout="success"]',
  '.callout[data-callout="quote"]',
  '.callout[data-callout="example"]',
  '.callout[data-callout="bug"]',
  '.callout[data-callout="summary"]',
  '.callout[data-callout="tldr"]',
  '.callout[data-callout="important"]',
  '.callout[data-callout="hint"]',
  '.callout[data-callout="check"]',
  '.callout[data-callout="done"]',
  '.callout[data-callout="help"]',
  '.callout[data-callout="faq"]',
  '.callout[data-callout="caution"]',
  '.callout[data-callout="attention"]',
  '.callout[data-callout="failure"]',
  '.callout[data-callout="error"]',
  '.callout[data-callout="fail"]',
  '.callout[data-callout="missing"]',
  '.callout[data-callout="cite"]',
  ".callout-content .callout",
  ".callout-icon",
  ".callout-icon .svg-icon",
  ".callout-icon::after",
  ".callout-fold",
  ".callout-fold::after",
  ".callout-fold .svg-icon",
  ".callout-fold.is-collapsed .svg-icon",
  // Popovers
  ".metadata-input-longtext",
  ".popover",
  // Search
  ".prompt",
  "input.prompt-input",
  ".suggestion-item.is-selected",
  ".suggestion-highlight",
  "mark",
  "a.tag",
  'input[type="search"]',
  // Explorer
  ".nav-files-container",
  ".nav-file-tag",
  ".nav-file-icon",
  ".nav-folder-title",
  ".nav-file-title",
  ".nav-file-title.is-active",
  ".nav-folder-title.is-active",
  ".nav-file-title.is-selected",
  ".nav-folder-title.is-selected",
  ".tree-item-self",
  ".tree-item-self:before",
  ".tree-item-self.mod-collapsible",
  ".tree-item-self.is-clickable",
  ".is-mobile .tree-item-self.is-clickable",
  ".tree-item-self.is-clickable.mobile-tap",
  ".tree-item-self.is-active",
  ".tree-item-self.is-selected",
  ".tree-item-self.is-being-dragged",
  ".tree-item-self .tree-item-icon",
  ".tree-item-self .tree-item-icon:before",
  ".tree-item-self .tree-item-icon .svg-icon:not(.right-triangle)",
  ".tree-item-flair-outer",
  ".tree-item-flair",
  ".tree-item-inner",
  ".tree-item-inner-text",
  ".tree-item-inner-subtext",
  ".tree-item-children",
  // Inline code(?)
  "kbd",
  // Icons
  "svg.svg-icon",
  ".clickable-icon.mod-warning",
  ".clickable-icon.mod-filled svg",
  ".setting-item-control .clickable-icon",
  '.clickable-icon[aria-disabled="true"]',
  ".clickable-icon.mobile-tap",
  ".is-mobile .clickable-icon",
  ".clickable-icon.is-active",
  ".clickable-icon",
  // Breadcrumbs
  ".view-header-title-parent .view-header-breadcrumb-separator",
  // Backlinks
  ".backlink-pane",
  ".backlink-pane .search-result-container",
  ".backlink-pane > .tree-item-self",
  ".backlink-pane > .tree-item-self .tree-item-inner",
  ".backlink-pane > .tree-item-self.is-clickable.is-collapsed",
  // Graph
  ".graph-view.color-fill",
  ".graph-view.color-fill-focused",
  ".graph-view.color-fill-tag",
  ".graph-view.color-fill-attachment",
  ".graph-view.color-fill-unresolved",
  ".graph-view.color-fill-1",
  ".graph-view.color-fill-2",
  ".graph-view.color-fill-3",
  ".graph-view.color-fill-4",
  ".graph-view.color-fill-5",
  ".graph-view.color-fill-6",
  ".graph-view.color-arrow",
  ".graph-view.color-circle",
  ".graph-view.color-line",
  ".graph-view.color-text",
  ".graph-view.color-fill-highlight",
  ".graph-view.color-line-highlight",
  ".graph-controls",
  // Themes
  ".theme-dark",
  ".theme-light",
  // Layout
  ".mod-sidedock",
  ".workspace-split",
  ".workspace-tabs.mod-top",
  ".workspace-tabs .workspace-leaf",
  ".workspace-split.mod-root",
  ".workspace-split.mod-root .view-content",
  // Borders
  ".workspace-leaf-resize-handle",
];
