import { getValueFromDictionary, readJsonFileAsDictionary, getCurrentFolder } from "./util/util.mjs"

export const themes = getValueFromDictionary(
  readJsonFileAsDictionary(getCurrentFolder(), "themes.json"),
  "themes",
)

export const usedRules = [
  ":root",
  "body",
  "h1 a",
  "h2 a",
  "h3 a",
  "h4 a",
  "h5 a",
  "h6 a",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  ".markdown-rendered pre",
  ".markdown-rendered code",
  ".markdown-rendered pre code",
  ".markdown-rendered button.copy-code-button",
  ".markdown-rendered button.copy-code-button:hover",
  ".callout",
  ".callout-title",
  ".callout-title-inner",
  ".callout-content",
  '.callout[data-callout="tip"]',
  '.callout[data-callout="warning"]',
  '.callout[data-callout="danger"]',
  '.callout[data-callout="abstract"]',
  '.callout[data-callout="todo"]',
  '.callout[data-callout="question"]',
  '.callout[data-callout="info"]',
  '.callout[data-callout="success"]',
  '.callout[data-callout="quote"]',
  '.callout[data-callout="example"]',
  '.callout[data-callout="bug"]',
  '.callout[data-callout="summary"]',
  '.callout[data-callout="tldr"]',
  '.callout[data-callout="important"]',
  '.callout[data-callout="hint"]',
  '.callout[data-callout="check"]',
  '.callout[data-callout="done"]',
  '.callout[data-callout="help"]',
  '.callout[data-callout="faq"]',
  '.callout[data-callout="caution"]',
  '.callout[data-callout="attention"]',
  '.callout[data-callout="failure"]',
  '.callout[data-callout="error"]',
  '.callout[data-callout="fail"]',
  '.callout[data-callout="missing"]',
  '.callout[data-callout="cite"]',
  ".metadata-input-longtext",
  ".popover",
  ".prompt",
  "input.prompt-input",
  ".suggestion-item.is-selected",
  ".suggestion-highlight",
  ".markdown-rendered mark",
  "a.tag",
  'input[type="search"]',
  ".theme-dark",
  ".theme-light",
]
