mode: replace
sections:
  - name: Typewriter
    id: obsidian-typewriter
    collapsed: false
    settings:
      - id: typewriter-editor
        title: Editor
        type: heading
        level: 2
      - id: theme-accent-sel
        title: Theme accent
        type: variable-themed-color
        opacity: false
        format: hex
        alt-format:
          - id: theme-accent-sel
            format: hsl-split
        default-light: '#519D5C'
        default-dark: '#519D5C'
