mode: replace
sections:
  - name: Editor
    id: viridian-editor
    collapsed: false
    settings:
      - id: vr-fonts
        title: Typefaces
        type: heading
        level: 1
        collapsed: true
