mode: replace
sections:
  - name: ｡ ₊°༺ ultra lobster ༻°₊ ｡
    id: ulu-theme-settings
    collapsed: false
    settings:
      - id: theme-info
        title: an intentional writing space
        description: |
          see an issue? want to suggest a feature? visit us on github: <https://github.com/7368697661/ultra-lobster> this theme was made with 💖 by kneecaps. 
        markdown: true
        type: info-text
        level: 0
      - id: ulu-subtheme
        title: 0️⃣ .𖥔 ݁ ˖ subthemes & colors ⊹ ࣪ ˖
        type: heading
        level: 1
        collapsed: true
      - id: ulu-interface
        title: 🖥️ .𖥔 ݁ ˖ interface & components ⊹ ࣪ ˖
        type: heading
        level: 1
        collapsed: true
      - id: ulu-interface-fancy
        title: ✨ .𖥔 ݁ ˖ fancy stuff ⊹ ࣪ ˖
        type: heading
        level: 2
        collapsed: true
      - id: ulu-enable-custom-bg
        title: enable custom workspace background
        description: ⚠️ currently only supported when using the 'abaddon glass' dark subtheme.
        type: class-toggle
      - id: ulu-custom-bg-url
        title: custom background image url
        description: 'paste a direct image link wrapped in url(""). example: url("https://i.imgur.com/image.png")'
        type: variable-text
        default: url("https://512pixels.net/downloads/macos-wallpapers/11-0-color-day.jpg")
      - id: ulu-grad
        title: halo gradient
        description: enable a wip background animation inspired by soft grainy gradients and angel numbers
        type: class-toggle
      - id: ulu-we1
        title: new-tab empty state (gradient + lobster)
        description: applies the “working edits” style empty state when no tabs are open
        type: class-toggle
      - id: ulu-interface-blur
        title: 🌫️ .𖥔 ݁ ˖ blur settings ⊹ ࣪ ˖
        type: heading
        level: 2
        collapsed: true
      - id: ulu-no-blur-callouts
        title: disable callout blur
        type: class-toggle
      - id: ulu-no-blur-mobile
        title: disable mobile nav blur
        type: class-toggle
      - id: ulu-blur-modal
        title: blur bg of settings pane
        type: class-toggle
      - id: ulu-blur-prompt
        title: blur prompt (cmd/search) bg
        type: class-toggle
      - id: ulu-blur-tooltip
        title: blur tooltip bg
        type: class-toggle
      - id: ulu-status-pills-blur
        title: blurred status-pills bg
        description: blurs bg of statusbar pill option
        type: class-toggle
      - id: ulu-blur-menu
        title: blur popup menu
        type: class-toggle
      - id: ulu-interface-other
        title: 🎛️ .𖥔 ݁ ˖ everything else ⊹ ࣪ ˖
        type: heading
        level: 2
        collapsed: true
      - id: ulu-minimal-properties
        title: minimal properties card
        description: removes the glass slab styling from the properties card
        type: class-toggle
        default: false
      - id: ulu-inline-property-tags
        title: match inline tags
        description: makes property tags look like standard inline wireframe tags
        type: class-toggle
        default: false
      - id: ulu-prop-card
        title: properties card
        type: class-toggle
      - id: ulu-active-line
        title: highlight active line
        type: class-toggle
      - id: ulu-status-pills
        title: island pill statusbar
        description: seperates statusbar items into pills
        type: class-toggle
      - id: ulu-accent-bold-italic
        title: make bold/italic different colors
        type: class-toggle
      - id: ulu-serif-italic
        title: make italic serif
        type: class-toggle
      - id: ulu-duo-tag
        title: make tags split
        type: class-toggle
      - id: ulu-justify
        title: justify paragraph text
        type: class-toggle
      - id: ulu-typography
        title: 📑 .𖥔 ݁ ˖ typography ⊹ ࣪ ˖
        type: heading
        level: 1
        collapsed: true
      - id: ulu-font-general
        title: editor font
        type: variable-select
        allowempty: false
        default: satoshi
        options:
          - label: satoshi ࣪ ִֶָ☾.sans
            value: satoshi
          - label: getai ࣪ ִֶָ☾.sans
            value: getai
          - label: aspekta ࣪ ִֶָ☾.sans
            value: aspekta
          - label: general sans ࣪ ִֶָ☾.sans
            value: general sans
          - label: inter ࣪ ִֶָ☾.sans
            value: inter
          - label: space grotesk ࣪ ִֶָ☾.sans
            value: space grotesk
          - label: lexend ࣪ ִֶָ☾.sans
            value: lexend
          - label: dobbintextsf-roman ࣪ ִֶָ☾.sans
            value: dobbintextsf-roman
          - label: eurostile ࣪ ִֶָ☾.sans
            value: eurostile
          - label: fraunces ✦ serif
            value: fraunces
          - label: nightingale ✦ serif
            value: nightingale
          - label: instrument ✦ serif
            value: instrument
          - label: monaspace ‪‪❤︎‬ mono
            value: monaspace
          - label: iawriter ‪‪❤︎‬ mono
            value: iawriter
          - label: martian mono ‪‪❤︎‬ mono
            value: martian mono
      - id: ulu-font-title
        title: title type
        type: variable-select
        allowempty: false
        default: monaspace
        options:
          - label: satoshi ࣪ ִֶָ☾.sans
            value: satoshi
          - label: getai ࣪ ִֶָ☾.sans
            value: getai
          - label: aspekta ࣪ ִֶָ☾.sans
            value: aspekta
          - label: general sans ࣪ ִֶָ☾.sans
            value: general sans
          - label: inter ࣪ ִֶָ☾.sans
            value: inter
          - label: space grotesk ࣪ ִֶָ☾.sans
            value: space grotesk
          - label: lexend ࣪ ִֶָ☾.sans
            value: lexend
          - label: dobbintextsf-roman ࣪ ִֶָ☾.sans
            value: dobbintextsf-roman
          - label: eurostile ࣪ ִֶָ☾.sans
            value: eurostile
          - label: fraunces ✦ serif
            value: fraunces
          - label: nightingale ✦ serif
            value: nightingale
          - label: instrument ✦ serif
            value: instrument
          - label: monaspace ‪‪❤︎‬ mono
            value: monaspace
          - label: iawriter ‪‪❤︎‬ mono
            value: iawriter
          - label: martian mono ‪‪❤︎‬ mono
            value: martian mono
      - id: responsive-text
        title: text adjuster
        description: 🚨 must be a whole / decimal number such as 1 or 1.1. further scale can be changed via slider in appearance
        type: variable-number
        default: 1
        format: em
      - id: ulu-list-distinct
        title: top level lists
        description: enable list header demarking 🚨 does not work in reading mode
        type: class-toggle
      - id: ulu-faintselect
        title: accent text selection
        type: class-toggle
      - id: ulu-accent-title
        title: accent titles
        type: class-toggle
      - id: ulu-headings
        title: ⌨️ .𖥔 ݁ ˖ heading settings ⊹ ࣪ ˖
        type: heading
        level: 2
        collapsed: true
      - id: ulu-colorfo-headings
        title: rainbow headers
        type: class-toggle
      - id: ulu-no-h2-line
        title: disable h2 underline
        description: removes the gradient underline from h2 headings
        type: class-toggle
      - id: ulu-h1-line-color
        title: header 1 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h1-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h2-line-color
        title: header 2 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h2-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h3-line-color
        title: header 3 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h3-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h4-line-color
        title: header 4 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h4-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h5-line-color
        title: header 5 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h5-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h6-line-color
        title: header 6 underline color
        type: variable-select
        allowempty: false
        default: var(--ulu-header-line-accent, var(--background-modifier-border))
        options:
          - label: follow global underline
            value: var(--ulu-header-line-accent, var(--background-modifier-border))
          - label: match header text color
            value: var(--ulu-h6-text-color, var(--ulu-header-line-accent, var(--background-modifier-border)))
          - label: monochrome
            value: var(--background-modifier-border)
          - label: accent
            value: var(--color-accent)
          - label: red
            value: var(--color-red)
          - label: orange
            value: var(--color-orange)
          - label: yellow
            value: var(--color-yellow)
          - label: green
            value: var(--color-green)
          - label: cyan
            value: var(--color-cyan)
          - label: blue
            value: var(--color-blue)
          - label: purple
            value: var(--color-purple)
          - label: pink
            value: var(--color-pink)
      - id: ulu-h1-weight
        title: header 1 weight
        description: nightingale looks best at weight >500
        type: variable-number
        default: 900
      - id: ulu-h2-weight
        title: header 2 weight
        type: variable-number
        default: 800
      - id: ulu-h3-weight
        title: header 3 weight
        type: variable-number
        default: 700
      - id: ulu-h4-weight
        title: header 4 weight
        type: variable-number
        default: 700
      - id: ulu-h5-weight
        title: header 5 weight
        type: variable-number
        default: 600
      - id: ulu-h6-weight
        title: header 6 weight
        type: variable-number
        default: 600
      - id: ulu-header-line-h1
        title: header 1 underline
        type: class-toggle
      - id: ulu-header-line-h2
        title: header 2 underline
        type: class-toggle
      - id: ulu-header-line-h3
        title: header 3 underline
        type: class-toggle
      - id: ulu-header-line-h4
        title: header 4 underline
        type: class-toggle
      - id: ulu-header-line-h5
        title: header 5 underline
        type: class-toggle
      - id: ulu-header-line-h6
        title: header 6 underline
        type: class-toggle
      - id: ulu-canvas
        title: 🖼️ .𖥔 ݁ ˖ canvas settings ⊹ ࣪ ˖
        type: heading
        level: 1
        collapsed: true
      - id: ulu-no-blur-canvas
        title: disable canvas blur
        description: removes the backdrop-filter blur effect from canvas nodes
        type: class-toggle
      - id: ulu-canvas-center
        title: center canvas text
        description: center align text in canvas cards
        type: class-toggle
      - id: ulu-canvas-border0
        title: disable border, red
        type: class-toggle
      - id: ulu-canvas-border1
        title: disable border, orange
        type: class-toggle
      - id: ulu-canvas-border2
        title: disable border, yellow
        type: class-toggle
      - id: ulu-canvas-border3
        title: disable border, green
        type: class-toggle
      - id: ulu-canvas-border4
        title: disable border, blue
        type: class-toggle
      - id: ulu-canvas-border5
        title: disable border, purple
        type: class-toggle
