- name: Vicious
  id: vicious
  settings:
    - id: generalSettings
      title: General Settings
      type: heading
      level: 2
    - id: scrollbar-hide
      type: class-toggle
      default: 'true'
      description: Turn on if you want to hide the scrollbar
    - id: vibrant-indents
      type: class-toggle
      default: 'false'
      description: Turn on if you want to hide the vibrant indent
    - id: disable-alternative-checkboxes
      description: Turn on if you are using your own implementation via a CSS Snippet.
      default: 'false'
      type: class-toggle
    - id: vibrant-folders
      type: class-toggle
      default: 'false'
      description: Turn on if you want to hide the vibrant folders
    - id: callout Style
      title: Callout Style
      description: Select your preferred callout style
      type: class-select
      allowEmpty: false
      default: callout-style-01
    - id: colors
      title: Colors
      type: heading
      level: 2
    - id: boldcolors
      title: Bold Color
      description: Select your preferred **BOLD** color
      type: class-select
      allowEmpty: false
      default: bold-C002
    - id: italicscolors
      title: Italics Color
      description: Select your preferred _ITALIC_ color
      type: class-select
      allowEmpty: false
      default: itl-C003
    - id: bold-italicscolors
      title: Bold + Italics Color
      description: Select your preferred **_BOLD+ITALIC_** color
      type: class-select
      allowEmpty: false
      default: bld-itl-C001
    - id: highlightcolors
      title: Highlight Color
      description: Select your preferred highlight color
      type: class-select
      allowEmpty: false
      default: highlight-C003
