mode: replace
sections:
  - name: Theme Settings
    id: theme-settings
    collapsed: false
    settings:
      - id: custom-wallpaper
        title: Custom Wallpaper URL
        description: Enter a direct image link e.g. url(https://i.postimg.cc/XXXXXX/image.png)
        type: variable-text
        default: none
      - id: toggle-glow
        title: Enable Glow
        description: Toggle glow effect on or off
        type: class-toggle
        default: true
      - id: glow-title
        title: Glow Daily Notes and General Notes
        type: heading
        level: 3
