name: Abyssal theme
id: at-theme-settings
settings:
  - id: at-colorful-headings
    title: Colorful headings
    description: Makes headings (H1 to H6) colorful
    type: class-toggle
  - id: at-line-height
    title: Increase line height (leading)
    description: Increases the line height (leading) of the body text
    type: class-toggle
