name: Theme Information
id: V1-Willemstad-Info
settings:
  - id: info-theme-documentation
    title: Theme Documentation
    type: info-text
    description: '[Website](https://willemstad.cc)'
    markdown: true
  - id: info-theme-repository
    title: Theme Repository
    type: info-text
    description: '[GitHub](https://github.com/tingmelvin/willemstad-x)'
    markdown: true
  - id: info-theme-mobile-support
    title: Mobile Support
    type: class-toggle
    description: Please note that Willemstad is not optimised for mobile devices at the moment.
    default: false
  - id: info-theme-macos-support
    title: macOS and iOS Support
    type: class-toggle
    description: Please note that the maintainer of Willemstad does not have access to either a Mac and/or an iOS device, which have slightly different styling in the core Obsidian app. Therefore, the theme has not been ensured to work properly with macOS and iOS. Bug reports are however very welcome to resolve these issues.
    default: false
