id: maple-basic
name: Maple Basic
settings:
  - id: setting-animation-time
    type: variable-number-slider
    title: Animation Duration (ms)
    title.zh: 动画时长（毫秒）
    default: 250
    min: 0
    max: 1000
    step: 50
    format: ms
  - id: setting-item-line-height
    type: variable-number-slider
    title: List Item Line Height
    title.zh: 列表行高
    description: Adjust the line height for items in file explorer, outline panel, and setting modal sidebar.
    description.zh: 调整文件管理器、大纲面板和设置面板侧边栏中行高。
    default: 1.5
    min: 1
    max: 2
    step: 0.1
  - id: setting-divider-color
    type: variable-themed-color
    title: Panel Divider Color
    title.zh: 面板分割线颜色
    format: hsl
    opacity: true
    default-light: '#'
    default-dark: '#'
  - id: title-colors
    title: Colors
    title.zh: 颜色
    type: heading
    level: 1
    collapsed: false
  - id: color-dark-dim-disable
    type: class-toggle
    title: Disable Opacity Reduction in Dark Mode
    title.zh: 深色模式下，颜色的不透明度不降低
  - id: color-highlight-only
    type: class-toggle
    title: '[Experimental] Only change highlight color'
    title.zh: 【实验性】只修改高亮颜色
    description: Not fully test. Feel free to report bugs
    description.zh: 没有经过完整测试，欢迎提交 bug
  - id: color-scheme
    type: class-select
    title: Color Scheme
    title.zh: 颜色方案
    allow-empty: false
    default: color-use-custom
    options:
      - label: Default
        value: color-use-default
      - label: Minimal
        value: color-use-minimal
      - label: Custom
        value: color-use-custom
  - id: title-light-mode
    title: Light Mode
    title.zh: 浅色模式
    type: heading
    level: 2
    collapsed: true
  - id: setting-accent-h-light
    type: variable-number-slider
    title: Base Color
    title.zh: 基础色
    default: 35
    min: 0
    max: 360
    step: 5
  - id: color-active-light
    type: class-select
    title: Highlight Color
    title.zh: 高亮色
    allow-empty: false
    default: color-active-default-light
    options:
      - label: Theme Color
        value: color-active-default-light
      - label: Theme Color Alt
        value: color-active-alt-light
      - label: Custom
        value: color-active-custom-light
  - id: setting-color-active-custom-light
    type: variable-color
    title: Custom Highlight Color (Active)
    title.zh: 自定义高亮色（激活状态）
    default: '#'
    format: hsl-split
    opacity: false
  - id: setting-color-inactive-custom-light
    type: variable-color
    title: Custom Highlight Color (Inactive)
    title.zh: 自定义高亮色（非激活状态）
    default: '#'
    format: hsl-split
    opacity: false
  - id: color-modify-bg-light
    type: class-toggle
    title: Modify Background Colors
    title.zh: 修改背景颜色
  - id: setting-bg-primary-light-hsl
    type: variable-color
    title: Primary Background Color
    title.zh: 主背景色
    description: Background color for main area, e.g. editor, setting panel
    description.zh: 主要区域的背景色，例如编辑器和设置面板
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-primary-alt-light-hsl
    type: variable-color
    title: Block Background Color
    title.zh: 块背景色
    description: Background color for blocks in main area, e.g. codeblock, blockquote
    description.zh: 主要区域内的块的背景色，例如代码块、引言块
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-secondary-light-hsl
    type: variable-color
    title: Secondary Background Color
    title.zh: 次背景色
    description: Background color in secondary area, e.g. sidebar
    description.zh: 次要区域的背景色，例如侧边栏
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-frame-light
    type: variable-color
    title: Top Bar Background Color
    title.zh: 顶栏背景色
    description: Background color in the top area, e.g. titlebar, tab container
    description.zh: 顶栏的背景色，例如标题栏、标签栏
    default: '#'
    format: hsl
    opacity: false
  - id: title-dark-mode
    title: Dark Mode
    title.zh: 暗色模式
    type: heading
    level: 2
    collapsed: true
  - id: setting-accent-h-dark
    type: variable-number-slider
    title: Base Color
    title.zh: 基础色
    default: 207
    min: 0
    max: 360
    step: 5
  - id: color-active-dark
    type: class-select
    title: Highlight Color
    title.zh: 高亮色
    allow-empty: false
    default: color-active-default-dark
    options:
      - label: Theme Color
        value: color-active-default-dark
      - label: Theme Color Alt
        value: color-active-alt-dark
      - label: Custom
        value: color-active-custom-dark
  - id: setting-bg-delta-dark
    type: variable-number-slider
    title: Background Brightness
    title.zh: 背景亮度
    description: Increase the brightness of background color
    description.zh: 增加背景色的亮度
    default: 0
    format: '%'
    min: 0
    max: 8
    step: 0.1
  - id: setting-color-active-custom-dark
    type: variable-color
    title: Custom Highlight Color (Active)
    title.zh: 自定义高亮色（激活状态）
    default: '#'
    format: hsl-split
    opacity: false
  - id: setting-color-inactive-custom-dark
    type: variable-color
    title: Custom Highlight Color (Inactive)
    title.zh: 自定义高亮色（非激活状态）
    default: '#'
    format: hsl-split
    opacity: false
  - id: color-modify-bg-dark
    type: class-toggle
    title: Modify Background Colors
    title.zh: 修改背景颜色
  - id: setting-bg-primary-dark-hsl
    type: variable-color
    title: Primary Background Color
    title.zh: 主背景色
    description: Background color for main area, e.g. editor, setting panel
    description.zh: 主要区域的背景色，例如编辑器和设置面板
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-primary-alt-dark-hsl
    type: variable-color
    title: Block Background Color
    title.zh: 块背景色
    description: Background color for blocks in main area, e.g. codeblock, blockquote
    description.zh: 主要区域内的块的背景色，例如代码块、引言块
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-secondary-dark-hsl
    type: variable-color
    title: Secondary Background Color
    title.zh: 次背景色
    description: Background color in secondary area, e.g. sidebar
    description.zh: 次要区域的背景色，例如侧边栏
    default: '#'
    format: hsl-values
    opacity: false
  - id: setting-bg-frame-dark
    type: variable-color
    title: Top Bar Background Color
    title.zh: 顶栏背景色
    description: Background color in the top area, e.g. titlebar, tab container
    description.zh: 顶栏的背景色，例如标题栏、标签栏
    default: '#'
    format: hsl
    opacity: false
  - id: title-layout
    title: Layout
    title.zh: 布局
    type: heading
    level: 1
    collapsed: false
  - id: app-layout-card
    type: class-toggle
    title: Enable Card Layout
    title.zh: 启用卡片布局
    description: Styles maybe broken when using stacked tabs
    description.zh: 当使用堆叠标签页时，样式可能不符合预期
    default: true
  - id: app-layout-card-border
    type: class-toggle
    title: Add Border to Cards
    title.zh: 为卡片添加边框
  - id: setting-app-layout-spacing
    type: variable-number-slider
    title: Card Spacing
    title.zh: 卡片间距
    default: 6
    max: 16
    min: 2
    step: 0.5
    format: px
  - id: app-layout-card-bg
    type: class-select
    title: Background Type
    title.zh: 背景类型
    description: '"gradient" is ineffective when the color scheme is "Minimal"'
    description.zh: 当颜色方案为 "Minimal" 时，"gradient" 不会生效
    allow-empty: false
    default: app-layout-card-gradient
    options:
      - label: Plain
        value: app-layout-card-plain
      - label: Gradient
        value: app-layout-card-gradient
      - label: Custom
        value: app-layout-card-custom
  - id: setting-layout-image-light
    type: variable-text
    title: Light Theme Background Image
    title.zh: 浅色主题背景图片
    description: Any CSS "background-image" value, e.g. url("/your/image/url")
    description.zh: 任何 CSS “background-image” 值，例如：url("图片链接地址")
    default: ''
  - id: setting-layout-opacity-light
    type: variable-number-slider
    title: Light Theme Background Opacity
    title.zh: 浅色主题背景不透明度
    default: 0.6
    max: 0.9
    min: 0.1
    step: 0.05
  - id: setting-layout-image-dark
    type: variable-text
    title: Dark Theme Background Image
    title.zh: 深色主题背景图片
    description: Any CSS "background-image" value, e.g. url("/your/image/url")
    description.zh: 任何 CSS “background-image” 值，例如：url("图片链接地址")
    default: ''
  - id: setting-layout-opacity-dark
    type: variable-number-slider
    title: Dark Theme Background Opacity
    title.zh: 深色主题背景不透明度
    default: 0.6
    max: 0.9
    min: 0.1
    step: 0.05
