mode: replace
sections:
  - name: Arzaba Theme
    id: arzaba-theme-settings
    collapsed: false
    settings:
      - id: arzaba-font-override
        title: 📏 Use recommended Font Sizes
        description: Forces recommended font sizes. Enabling this will override user font size !
        type: class-toggle
        default: false
        value: arzaba-font-override
