mode: replace
sections:
  - name: Dedication 2 Theme Settings
    id: dedication-2-theme
    collapsed: false
    settings:
      - id: color-presets
        title: Color Presets
        type: heading
        level: 1
        collapsed: false
      - id: typography-settings
        title: Typography
        type: heading
        level: 1
        collapsed: true
