import { QuartzTransformerPlugin } from "@quartz-community/types";
export {
  QuartzTransformerPlugin,
  StaticResources,
} from "@quartz-community/types";
import { ThemeOptions, ThemeMeta, ThemeData } from "./types.js";
export { AspectCSS, AspectKey, ThemeModule } from "./types.js";

/**
 * QuartzTheme — Transformer plugin that injects Obsidian theme CSS into Quartz sites.
 *
 * This is a pure transformer: no component needed. CSS is injected via externalResources()
 * and Quartz's built-in Darkmode() component handles light/dark switching via
 * :root.dark / :root.light CSS class toggles.
 */

/**
 * QuartzTheme transformer plugin.
 *
 * @example
 * ```ts
 * // Basic usage
 * QuartzTheme({ theme: "tokyo-night", mode: "both" })
 *
 * // With variation
 * QuartzTheme({ theme: "catppuccin", variation: "frappe", mode: "both" })
 *
 * // Mix-and-match aspects
 * QuartzTheme({
 *   theme: "tokyo-night",
 *   mode: "both",
 *   aspects: {
 *     callouts: "anuppuccin",
 *     tables: "minimal",
 *     code: false,
 *   },
 * })
 * ```
 */
declare const QuartzTheme: QuartzTransformerPlugin<Partial<ThemeOptions>>;

/**
 * Theme registry — imports and exposes theme data modules.
 *
 * Each theme is a lazily-importable module generated by scripts/generate.js.
 * The registry provides lookup by theme ID and variation discovery.
 */

/**
 * Map of theme ID → lazy import function.
 *
 * This will be populated by the generate script. Each entry points to a
 * generated module in ./themes/ that exports a `theme` object.
 *
 * At build time, tsup's tree-shaking ensures only imported themes end up
 * in the final bundle.
 */
/**
 * Resolve a theme + optional variation into a concrete theme ID.
 *
 * For themes with variations (e.g. catppuccin), the variation is appended:
 *   resolveThemeId("catppuccin", "frappe") → "catppuccin-frappe"
 *
 * For themes without variations, the base name is returned:
 *   resolveThemeId("tokyo-night") → "tokyo-night"
 */
declare function resolveThemeId(theme: string, variation?: string): string;
/**
 * Load a theme's full data (CSS strings per aspect per mode).
 */
declare function loadTheme(themeId: string): ThemeData;
/**
 * Get metadata for a theme without loading its CSS data.
 */
declare function getThemeMeta(themeId: string): ThemeMeta | undefined;
/**
 * Get all available theme IDs.
 */
declare function getAvailableThemes(): string[];
/**
 * Register a theme (called by generated theme modules at import time,
 * or by the generate script to populate the registry).
 */
declare function registerTheme(
  id: string,
  meta: ThemeMeta,
  loader: () => Promise<{ theme: ThemeData }>,
): void;

declare const CALLOUT_ICON_URIS: Record<string, string>;
declare const CALLOUT_ALIASES: Record<string, string>;
declare const CHECKBOX_ICON_URIS: Record<string, string>;

declare function generateCalloutIconCSS(): string;
declare function resolveCalloutIcon(calloutType: string): string | undefined;

declare function generateCheckboxIconCSS(): string;
declare function resolveCheckboxIcon(taskChar: string): string | undefined;

export {
  CALLOUT_ALIASES,
  CALLOUT_ICON_URIS as CALLOUT_ICON_MAP,
  CHECKBOX_ICON_URIS as CHECKBOX_ICON_MAP,
  QuartzTheme,
  QuartzTheme as QuartzThemes,
  ThemeData,
  ThemeMeta,
  ThemeOptions,
  QuartzTheme as default,
  generateCalloutIconCSS,
  generateCheckboxIconCSS,
  getAvailableThemes,
  getThemeMeta,
  loadTheme,
  QuartzTheme as quartzThemes,
  registerTheme,
  resolveCalloutIcon,
  resolveCheckboxIcon,
  resolveThemeId,
  QuartzTheme as transformer,
};
