name: Pxld
id: pxld-theme
settings:
  - id: my-title
    title: Theme Settings
    type: heading
    level: 3
  - id: interactive-accent
    title: Accent Color
    type: variable-color
    format: hex
    default: "#ff0000"
  - id: text-accent-hover
    title: Accent Hover Color
    type: variable-color
    format: hex
    default: "#5e0b11"
  - id: font-text
    title: Base Font
    type: variable-text
    default: "Pixel Square"
