name: Appearance
id: Appearance
settings:
  - id: colors
    title: Colors
    type: heading
    level: 1
    collapsed: true
  - id: accent
    title: Accent Color
    type: variable-themed-color
    format: hsl-split
    opacity: false
    default-light: '#0F87CC'
    default-dark: '#80D0FF'
  - id: Extended-colors
    title: Extended Colors
    type: heading
    level: 2
    collapsed: true
  - id: red
    title: Red
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(115, 42, 56)
    default-dark: rgb(219, 75, 75)
  - id: red1
    title: Red1
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(140, 67, 81)
    default-dark: rgb(255, 117, 127)
  - id: green
    title: Green
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(51, 99, 92)
    default-dark: rgb(158, 206, 106)
  - id: cyan
    title: Cyan
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(15, 75, 110)
    default-dark: rgb(125, 207, 255)
  - id: blue
    title: Blue
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(52, 84, 138)
    default-dark: rgb(122, 162, 247)
  - id: yellow
    title: Yellow
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(143, 94, 21)
    default-dark: rgb(224, 175, 104)
  - id: orange
    title: Orange
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(150, 80, 39)
    default-dark: rgb(255, 158, 100)
  - id: magenta
    title: Magenta
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(90, 74, 120)
    default-dark: rgb(187, 154, 247)
  - id: pink
    title: Pink
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(109, 74, 120)
    default-dark: rgb(217, 0, 105)
  - id: Background-colors
    title: Background Colors
    type: heading
    level: 1
    collapsed: true
  - id: bg
    title: Background Primary
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(213, 214, 219)
    default-dark: rgb(26, 27, 38)
  - id: bg_dark
    title: Background Dark
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(203, 204, 209)
    default-dark: rgb(22, 22, 30)
  - id: bg_highlight
    title: Background Highlight
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(220, 222, 226)
    default-dark: rgb(41, 46, 66)
  - id: bg_highlight_dark
    title: Background Highlight Dark
    description: Used for code bg
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(195, 197, 201)
    default-dark: rgb(36, 40, 59)
  - id: bg_dark2
    title: Background Dark2
    type: variable-themed-color
    format: rgb
    opacity: false
    default-light: rgb(188, 189, 194)
    default-dark: rgb(15, 15, 20)
  - id: foreground-header
    title: Foreground
    type: heading
    level: 2
    collapsed: true
  - id: text-color-heading
    title: Text / Icon Color
    type: heading
    level: 3
    collapsed: true
  - id: text-normal
    title: Text Normal
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-muted
    title: Text Muted
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-faint
    title: Text Faint
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-accent
    title: Text Accent
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-accent-hover
    title: Text Accent Hover
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-on-accent
    title: Text on Accent
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-on-accent-inverted
    title: Text on Accent Inverted
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-error
    title: Text Error
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-warning
    title: Text Warning
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: text-success
    title: Text Success
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: interactive-heading
    title: Interactive color
    type: heading
    level: 3
    collapsed: true
  - id: interactive-normal
    title: Interactive Normal
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: interactive-hover
    title: Interactive Hover
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: interactive-accent
    title: Interactive Accent
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: interactive-accent-hover
    title: Interactive Accent Hover
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - id: interactive-accent-hsl
    title: Interactive Accent HSL
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: '#'
    default-dark: '#'
  - null
