name: Vercel Theme
id: vercel-theme-settings
settings:
  - id: vercel-theme
    title: Theme variants
    description: Select your preferred theme appearance
    type: class-select
    allowEmpty: false
    default: vercel-dark
    options:
      - label: Vercel Dark
        value: vercel-dark
      - label: Vercel Light
        value: vercel-light
  - id: vercel-theme-accent
    title: Accent Color
    description: Select your preferred accent color
    type: class-select
    allowEmpty: false
    default: accent-blue
    options:
      - label: Blue
        value: accent-blue
      - label: Purple
        value: accent-purple
      - label: Cyan
        value: accent-cyan
