mode: replace
sections:
  - name: Colored Candy
    id: colored-candy-settings
    collapsed: false
    settings:
      - id: bg-l-modifier
        title: Background-to-text contrast
        description: The background lightness and saturation will be adjusted by this amount to give more contast to the text.
        type: variable-number-slider
        default: 0
        min: -10
        max: 10
        step: 1
        format: '%'
      - id: file-line-width
        title: Readable line length
        description: The maximum line length when "Readable line length" is enabled.
        type: variable-number
        default: 700
        format: px
