name: Colored Candy
id: colored-candy-settings
settings:
  - id: bg-l-modifier
    title: Background-to-text contrast
    description: The background lightness and saturation will be adjusted by this amount to give more contast to the text.
    type: variable-number-slider
    default: 0
    min: -10
    max: 10
    step: 1
    format: "%"
  - id: file-line-width
    title: Readable line length
    description: The maximum line length when "Readable line length" is enabled.
    type: variable-number
    default: 700
    format: px
  - description: "**Readable line length** can be enabled under **Settings → Editor → Readable line length**."
    type: info-text
    markdown: true
