name: Hide & move elements
id: hide-elements
settings:
  - id: safe-place-position
    title: Move top buttons
    description: 'Note: Only in case the top buttons cover the phone status bar'
    type: variable-number
    default: 35
    format: px
  - id: icon-settings
    title: Show icon settings
    type: variable-select
    default: none
    options:
      - label: Hide
        value: none
      - label: Show
        value: unset
  - id: num-of-notes
    title: Show number of notes
    type: variable-select
    default: none
    options:
      - label: Hide
        value: none
      - label: Show
        value: unset
  - id: show-explorer-buttons
    title: Show explorer buttons
    type: variable-select
    default: Hide
    options:
      - label: Hide
        value: none
      - label: Show
        value: block
  - id: explorer-bar-position
    title: Move explorer buttons
    type: variable-select
    default: Up
    options:
      - label: Up
        value: static
      - label: Down
        value: absolute
  - id: show-editor-text-bar
    title: Show editor bar
    type: variable-select
    default: Show
    options:
      - label: Hide
        value: none
      - label: Show
        value: unset
  - id: hide-navbar
    title: Hide navigation bar
    type: variable-select
    default: block
    options:
      - label: Hide
        value: none
      - label: Show
        value: block
  - id: files-bookmarks-search-bar
    title: Show menu files
    type: variable-select
    default: Hide
    options:
      - label: Hide
        value: none
      - label: Show
        value: block
  - id: files-bookmarks-search-bar-position
    title: Move menu files
    type: variable-select
    default: Top
    options:
      - label: Up
        value: 0
      - label: Down
        value: 1
  - id: show-vault-name
    title: Show vault
    type: variable-select
    default: none
    options:
      - label: Hide
        value: none
      - label: Show
        value: unset
  - id: vault-settings-position
    title: Move vault and settings
    type: variable-select
    default: Up
    options:
      - label: Up
        value: 0
      - label: Down
        value: 1
  - id: scrollbars
    title: Show scrollbars
    type: variable-select
    default: none
    options:
      - label: Hide
        value: none
      - label: Show
        value: unset
