name: Simply Colorful theme settings
id: simply-colorful-theme
settings:
  - id: bold-color
    title: Bold color
    description: Defines the color of bold text
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: italic-color
    title: Italic color
    description: Defines the color of italic text
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: text-accent
    title: Internal link color
    description: Defines the color of internal links
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: text-accent-hover
    title: Internal link hover color
    description: Defines the color of internal links while hovered
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: link-external-color
    title: External link color
    description: Defines the color of external links
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: link-external-color-hover
    title: External link hover color
    description: Defines the color of external links while hovered
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: text-highlight-bg
    title: Highlight color
    description: Defines the color of highlighted text
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: sc-headings
    title: Interface colors
    description: Defines the colors of all the headings
    type: heading
    level: 2
    collapsed: true
  - id: h1-color
    title: Heading 1 color
    description: Defines the color of heading 1
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: h2-color
    title: Heading 2 color
    description: Defines the color of heading 2
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: h3-color
    title: Heading 3 color
    description: Defines the color of heading 3
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: h4-color
    title: Heading 4 color
    description: Defines the color of heading 4
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: h5-color
    title: Heading 5 color
    description: Defines the color of heading 5
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
  - id: h6-color
    title: Heading 6 color
    description: Defines the color of heading 6
    type: variable-themed-color
    opacity: false
    format: rgb
    default-light: "#"
    default-dark: "#"
