mode: replace
sections:
  - name: Vauxhall
    id: vauxhall
    collapsed: false
    settings:
      - id: h1-accent
        title: Accent Color Main Header
        description: Apply the user's accent color to H1 headers.
        type: class-toggle
