name: Accent Color
id: accent-color
settings:
  - id: accent-color-for-light-theme
    title: Accent Color for Light Theme
    title.zh: 浅色模式主题色
    type: class-select
    allowEmpty: false
    default: accent-color-bw-light
    options:
      - label: Black & White
        value: accent-color-bw-light
      - label: Peach
        value: accent-color-peach-light
      - label: Beige
        value: accent-color-beige-light
      - label: Sage
        value: accent-color-sage-light
      - label: Blue
        value: accent-color-blue-light
      - label: Purple
        value: accent-color-purple-light
      - label: Pink
        value: accent-color-pink-light
  - id: accent-color-for-dark-theme
    title: Accent Color for Dark Theme
    title.zh: 深色模式主题色
    type: class-select
    allowEmpty: false
    default: accent-color-bw-dark
    options:
      - label: Black & White
        value: accent-color-bw-dark
      - label: Peach
        value: accent-color-peach-dark
      - label: Beige
        value: accent-color-beige-dark
      - label: Sage
        value: accent-color-sage-dark
      - label: Blue
        value: accent-color-blue-dark
      - label: Purple
        value: accent-color-purple-dark
      - label: Pink
        value: accent-color-pink-dark
  - id: custom-accent-color
    title: Custom Accent Color
    title.zh: 自定义主题色
    description: Selections above will be ignored if this toggle is on. (I know it's annoying but please bear with me.)
    description.zh: 如果开启，上面的选择将被忽略。（反复强调别嫌啰嗦）
    type: class-toggle
    default: false
  - id: custom-accent-color-for-light-theme
    title: Custom Accent Color for Light Theme
    title.zh: 浅色模式自定义主题色
    type: heading
    level: 1
    collapsed: true
  - id: accent-color-light-hue-default
    title: Accent Color Hue for Light Theme
    title.zh: 浅色模式主题色色相
    description: Hover to preview.
    description.zh: 鼠标悬停进行预览。
    type: variable-number-slider
    min: 0
    max: 360
    step: 1
    default: 254
  - id: accent-color-light-saturation-default
    title: Accent Color Saturation for Light Theme (%)
    title.zh: 浅色模式主题色饱和度（%）
    description: The higher the value, the more vivid the color.
    description.zh: 数值越高，颜色越鲜艳。
    type: variable-number-slider
    format: '%'
    min: 0
    max: 100
    step: 1
    default: 80
  - id: accent-color-light-lightness-default
    title: Accent Color Lightness for Light Theme (%)
    title.zh: 浅色模式主题色亮度（%）
    description: The higher the value, the lighter the color.
    description.zh: 数值越高，颜色越亮。
    type: variable-number-slider
    format: '%'
    min: 0
    max: 100
    step: 1
    default: 68
  - id: custom-accent-color-for-dark-theme
    title: Custom Accent Color for Dark Theme
    title.zh: 深色模式自定义主题色
    type: heading
    level: 1
    collapsed: true
  - id: accent-color-dark-hue-default
    title: Accent Color Hue for Dark Theme
    title.zh: 深色模式主题色色相
    description: Hover to preview.
    description.zh: 鼠标悬停进行预览。
    type: variable-number-slider
    min: 0
    max: 360
    step: 1
    default: 254
  - id: accent-color-dark-saturation-default
    title: Accent Color Saturation for Dark Theme (%)
    title.zh: 深色模式主题色饱和度（%）
    description: The higher the value, the more vivid the color.
    description.zh: 数值越高，颜色越鲜艳。
    type: variable-number-slider
    format: '%'
    min: 0
    max: 100
    step: 1
    default: 80
  - id: accent-color-dark-lightness-default
    title: Accent Color Lightness for Dark Theme (%)
    title.zh: 深色模式主题色亮度（%）
    description: The higher the value, the lighter the color.
    description.zh: 数值越高，颜色越亮。
    type: variable-number-slider
    format: '%'
    min: 0
    max: 100
    step: 1
    default: 68
