name: 'Catppuccin: Catppuccin Accents'
id: catppuccin-theme-settings
settings:
  - id: catppuccin-theme-dark
    title: Dark theme flavor
    description: Select your preferred dark mode flavor
    type: class-select
    allowEmpty: false
    default: ctp-mocha
    options:
      - label: Frappe
        value: ctp-frappe
      - label: Macchiato
        value: ctp-macchiato
      - label: Mocha
        value: ctp-mocha
  - id: catppuccin-theme-accents
    title: Theme accent
    description: Select your preferred accent
    type: class-select
    allowEmpty: false
    default: ctp-full-palette
    options:
      - label: Full palette
        value: ctp-full-palette
      - label: Rosewater
        value: ctp-accent-rosewater
      - label: Flamingo
        value: ctp-accent-flamingo
      - label: Pink
        value: ctp-accent-pink
      - label: Mauve
        value: ctp-accent-mauve
      - label: Red
        value: ctp-accent-red
      - label: Maroon
        value: ctp-accent-maroon
      - label: Peach
        value: ctp-accent-peach
      - label: Yellow
        value: ctp-accent-yellow
      - label: Green
        value: ctp-accent-green
      - label: Teal
        value: ctp-accent-teal
      - label: Sky
        value: ctp-accent-sky
      - label: Sapphire
        value: ctp-accent-sapphire
      - label: Blue
        value: ctp-accent-blue
      - label: Lavender
        value: ctp-accent-lavender
