name: Mado Miniflow
id: mado-miniflow
settings:
  - id: intro-section
    title: Introduction
    description: "The setting here covers only the very basic to avoid complexity fatigue. That being said, feel free to suggest anything by submitting a Github issue on: https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow"
    type: heading
    collapsed: true
    level: 3

  - id: theme-section
    title: Theme Section
    type: heading
    collapsed: true
    level: 3
  - id: theme-color
    title: Theme Color
    type: class-select
    allowEmpty: false
    default: theme-violette
    options:
      - label: Daisy Blue
        value: theme-daisy-blue
      - label: Red Sky
        value: theme-red-sky
      - label: Violette
        value: theme-violette
      - label: Greenery
        value: theme-greenery
      - label: Yellowish
        value: theme-yellowish
      - label: Orange Jist
        value: theme-orange-jist
      - label: Deep Blue
        value: theme-deep-blue
      - label: Tea Teal
        value: theme-tea-teal
      - label: Magenta Pink
        value: theme-magenta-pink
      - label: Grayscale
        value: theme-grayscale
  - id: accent
    title: Accent Color
    type: variable-themed-color
    opacity: false
    format: hsl-split
    default-light: "#"
    default-dark: "#"
  - id: bgcolor
    title: Background Color
    description: "*Background color is not dynamically coded. You may see off-colors if you wish to change this setting."
    type: variable-themed-color
    opacity: false
    format: hsl-split
    default-light: "#"
    default-dark: "#"
  - id: toggle-wave-background
    title: Hide Background Wave Design
    type: class-toggle
    default: false
  - id: toggle-tab-design
    title: Enable Alternative Tab Design
    type: class-toggle
    default: false
  - id: toggle-note-radius
    title: Enable All-Rounded Corner Note Pane
    type: class-toggle
    default: false
  - id: toggle-note-animation
    title: Enable sliding animation on main pane
    description: Animation is noticable when you switch to a new tab
    type: class-toggle
    default: true
  - id: layout-section
    title: Layout Section
    type: heading
    collapsed: true
    level: 3
  - id: toggle-tab-height
    title: Enable Compact Tab Header
    type: class-toggle
    default: false
  - id: toggle-tab-height-stacked
    title: Enable Compact Tab Header (Stacked)
    description: If you noticed a broken gap after the toggle, just refresh it by clicking on the panes (so that they can readjust themselves).
    type: class-toggle
    default: false
  - id: toggle-scrollbar-overlay
    title: Enable Overlay Scrollbar
    type: class-toggle
    description: Overlay will provide you wider field of contents, but in return, scrollbar will have to overlap onto it.
    default: true
  - id: hiding-section
    title: Hiding Elements
    type: heading
    description: Hide/Unhide the surrounding elements. Most can be hovered to reveal them.
    level: 4
    collapsed: true
  - id: toggle-titlebar-buttons
    title: Hide Window Titlebar Buttons
    type: class-toggle
    default: true
  - id: toggle-side-ribbons
    title: Hide Sidedock Ribbons
    type: class-toggle
    default: true
  - id: toggle-sidebar-toggle-left
    title: Hide Sidebar Toggle Button (Left)
    type: class-toggle
    default: true
  - id: toggle-sidebar-toggle-right
    title: Hide Sidebar Toggle Button (Right)
    type: class-toggle
    default: true
  - id: toggle-sidebar-buttons
    title: Hide Sidebar Tab Buttons
    type: class-toggle
    default: true
  - id: toggle-explorer-buttons
    title: Hide File Explorer Buttons
    type: class-toggle
    default: true
  - id: toggle-vault-title
    title: Hide File Explorer Vault Title (Unhoverable)
    type: class-toggle
    default: true
  - id: toggle-explorer-indent
    title: Hide File Explorer Indentation Guide (Unhoverable)
    type: class-toggle
    default: true
  - id: toggle-explorer-collapse
    title: Hide File Explorer Collapse Indicator (Unhoverable)
    type: class-toggle
    default: true
  - id: toggle-tab-section
    title: Hide Note Tab Section
    type: class-toggle
    default: false
  - id: toggle-note-header
    title: Hide Note Title Bar
    type: class-toggle
    default: false
  - id: toggle-status-bar
    title: Hide Status Bar (Unhoverable)
    type: class-toggle
    default: true
  - id: toggle-sync-button
    title: Show Sync Button Independently
    type: class-toggle
    description: Available when Status Bar is hidden.
    default: false
  - id: toggle-scrollbar
    title: Hide Scrollbar
    type: class-toggle
    default: true
  - id: sidebar-section
    title: Sidebar Section
    type: heading
    description: With a fixed width, the contents of sidebar will pull towards to the middle whenever you resize. This gives you a better focus at the center of a bigger screen.
    collapsed: true
    level: 4
  - id: toggle-sidebar-fixed-left
    title: Fixed Width (Left)
    type: class-toggle
    default: true
  - id: toggle-sidebar-fixed-right
    title: Fixed Width (Right)
    type: class-toggle
    default: true
  - id: toggle-sidebar-fixed-left-auto
    title: Auto Expand Width (Left)
    type: class-toggle
    default: false
  - id: toggle-sidebar-fixed-right-auto
    title: Auto Expand Width (Right)
    type: class-toggle
    default: false
  - id: sidebar-size-left
    title: Width size if fixed (Left)
    type: variable-number-slider
    default: 270
    format: px
    min: 200
    max: 1000
    step: 10
  - id: sidebar-size-right
    title: Width size if fixed (Right)
    type: variable-number-slider
    default: 270
    format: px
    min: 200
    max: 1000
    step: 10
  - id: toggle-sidebar-left-top
    title: Additional space on top of left sidebar
    type: class-toggle
    default: false
  - id: toggle-sidebar-right-top
    title: Additional space on top of right sidebar
    type: class-toggle
    default: true
  - id: markdown-section
    title: Markdown Section
    type: heading
    collapsed: true
    level: 3
  - id: file-line-width
    title: Readable Line Length
    type: variable-number-slider
    default: 700
    format: px
    min: 400
    max: 1200
    step: 10
  - id: text-normal
    title: Text Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: text-muted
    title: Muted Text Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: text-faint
    title: Faint Text Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: typography-section
    title: Typography Section
    type: heading
    collapsed: true
    level: 4
  - id: bold-color
    title: Bold Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: bold-weight
    title: Bold Weight
    type: variable-number-slider
    default: 700
    min: 100
    max: 1000
    step: 100
  - id: italic-color
    title: Italic Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: toggle-highlight-type
    title: Highlight Type
    type: class-select
    allowEmpty: false
    default: THT-underline-dark
    options:
      - label: Background-filled
        value: THT-background
      - label: Underlined
        value: THT-underline
      - label: Underlined (Light-mode only)
        value: THT-underline-light
      - label: Underlined (Dark-mode only)
        value: THT-underline-dark
  - id: color-highlight
    title: Highlight Color (Text)
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: text-highlight-bg
    title: Highlight Color (Background/Underline)
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: color-strikethrough
    title: Strikethrough Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: inline-code-color
    title: Inline Code Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: list-marker-color
    title: Listing Bullet/Marker Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: heading-section
    title: Heading Section
    description: "Not applicable to cssclass: mado-heading."
    type: heading
    collapsed: true
    level: 4

  - id: toggle-h1-margin-top
    title: Enable H1 Spacious Separator
    description: When an H1 is uncollapsed, it will create a big wide space below to distinguish from the next H1. Downside, however, is the first H1 will always have the wide space above it.
    type: class-toggle
    default: true
  - id: h1-size
    title: H1 Size
    type: variable-number
    format: em
    default: 2
  - id: h2-size
    title: H2 Size
    type: variable-number
    format: em
    default: 1.6
  - id: h3-size
    title: H3 Size
    type: variable-number
    format: em
    default: 1.37
  - id: h4-size
    title: H4 Size
    type: variable-number
    format: em
    default: 1.25
  - id: h5-size
    title: H5 Size
    type: variable-number
    format: em
    default: 1.12
  - id: h6-size
    title: H6 Size
    type: variable-number
    format: em
    default: 1.12
  - id: h1-color
    title: H1 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: h2-color
    title: H2 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: h3-color
    title: H3 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: h4-color
    title: H4 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: h5-color
    title: H5 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
  - id: h6-color
    title: H6 Color
    type: variable-themed-color
    format: hsl
    default-light: "#"
    default-dark: "#"
