/**
 * Theme registry — imports and exposes theme data modules.
 *
 * Each theme is a lazily-importable module generated by scripts/generate.js.
 * The registry provides lookup by theme ID and variation discovery.
 */

import type { ThemeData, ThemeMeta } from "./types";
import { themeData, themeMetas } from "./themes/_registry";

/**
 * Map of theme ID → lazy import function.
 *
 * This will be populated by the generate script. Each entry points to a
 * generated module in ./themes/ that exports a `theme` object.
 *
 * At build time, tsup's tree-shaking ensures only imported themes end up
 * in the final bundle.
 */

/**
 * Resolve a theme + optional variation into a concrete theme ID.
 *
 * For themes with variations (e.g. catppuccin), the variation is appended:
 *   resolveThemeId("catppuccin", "frappe") → "catppuccin-frappe"
 *
 * For themes without variations, the base name is returned:
 *   resolveThemeId("tokyo-night") → "tokyo-night"
 */
export function resolveThemeId(theme: string, variation?: string): string {
  if (variation) {
    const variantId = `${theme}-${variation}`;
    if (variantId in themeData) return variantId;
  }
  if (theme in themeData) return theme;
  throw new Error(
    `[QuartzTheme] Unknown theme: "${theme}"${variation ? ` (variation: "${variation}")` : ""}. ` +
      `Available themes: ${Object.keys(themeData).join(", ")}`,
  );
}

/**
 * Load a theme's full data (CSS strings per aspect per mode).
 */
export function loadTheme(themeId: string): ThemeData {
  const theme = themeData[themeId];
  if (!theme) {
    throw new Error(`[QuartzTheme] No theme data for "${themeId}".`);
  }
  return theme;
}

/**
 * Get metadata for a theme without loading its CSS data.
 */
export function getThemeMeta(themeId: string): ThemeMeta | undefined {
  return themeMetas[themeId];
}

/**
 * Get all available theme IDs.
 */
export function getAvailableThemes(): string[] {
  return Object.keys(themeData);
}

/**
 * Register a theme (called by generated theme modules at import time,
 * or by the generate script to populate the registry).
 */
export function registerTheme(
  id: string,
  meta: ThemeMeta,
  loader: () => Promise<{ theme: ThemeData }>,
): void {
  loader().then((mod) => {
    themeData[id] = mod.theme;
  });
  themeMetas[id] = meta;
}
