export type {
  BuildCtx,
  QuartzTransformerPlugin,
  QuartzTransformerPluginInstance,
  StaticResources,
} from "@quartz-community/types";

/** All available aspect keys that can be mixed and matched across themes. */
export type AspectKey =
  | "base"
  | "typography"
  | "callouts"
  | "tables"
  | "code"
  | "links"
  | "blockquotes"
  | "checkboxes"
  | "images"
  | "embeds"
  | "cards"
  | "search"
  | "scrollbars"
  | "explorer"
  | "toc"
  | "graph"
  | "popover"
  | "footer"
  | "recentNotes"
  | "listPage"
  | "darkmode"
  | "breadcrumbs"
  | "lists"
  | "canvas"
  | "bases"
  | "properties"
  | "stacked"
  | "misc";

/** Per-aspect CSS strings for a single mode (dark or light). */
export type AspectCSS = Partial<Record<AspectKey, string>>;

/** Theme data for a single theme, generated by the generate script. */
export interface ThemeData {
  meta: ThemeMeta;
  dark: AspectCSS;
  light: AspectCSS;
  /** Optional extra CSS to inject alongside the theme (e.g. CRT effects, snow animations). */
  extras?: string;
  /**
   * Pre-extracted CSS for class-toggle and class-select Style Settings.
   * Maps class name → mode-scoped CSS (with body.class selector stripped).
   * Generated at build time from the raw theme CSS.
   *
   * Each entry contains up to three CSS strings:
   * - `general`: CSS that applies regardless of mode
   * - `dark`: CSS that should only apply in dark mode
   * - `light`: CSS that should only apply in light mode
   */
  classSettings?: Record<string, ClassSettingCSS>;
  /**
   * Selector-impact graph derived from canonical Style Settings effects.
   * Maps selectors to the setting effects that can influence them.
   */
  selectorImpacts?: Record<string, SelectorImpactRecord>;
  /**
   * Broken var() chain map: targetVar → dependentVars[].
   * Records edges where the source CSS declared `--b: var(--a)` but the
   * generated theme CSS resolved it to a static value. Used by the runtime
   * to re-emit bridge declarations when a user overrides a target variable.
   */
  brokenVarLinks?: Record<string, string[]>;
}

/** Mode-scoped CSS for a single class-toggle or class-select setting. */
export interface ClassSettingCSS {
  general?: string;
  dark?: string;
  light?: string;
}

export interface SelectorImpactRecord {
  impacts: SelectorImpact[];
  interactionGroups: SelectorInteractionGroup[];
}

export interface SelectorImpact {
  settingId: string;
  sectionId: string;
  settingType: string;
  effectKind: string;
  targetKind: string;
  operation: string;
  mode: "both" | "dark" | "light";
  interactionGroup: string;
  interactionMode: string;
  pathKind:
    | "body-class"
    | "css-variable"
    | "derived-variable"
    | "gradient-variable";
  direct: boolean;
  selectorVariable?: string;
  /**
   * Variable traversal metadata for explainability.
   * Direct impact: variablePath=["--x"], variableChainLength=0, variableConsumerKind="direct".
   * Transitive bridge: variablePath=["--x","--y",...], chainLength>0, kind="transitive".
   */
  variablePath?: string[];
  variableChainLength?: number;
  variableConsumerKind?: "direct" | "transitive";
  /**
   * Per-hop nested at-rule context for variable bridges; bridgeAtRuleContexts[i] maps to variablePath[i+1].
   * Example: variablePath=["--a","--b","--c"] => bridgeAtRuleContexts[0] scopes the --a→--b hop.
   */
  bridgeAtRuleContexts?: string[][];
  /** Mode after intersecting effect mode, transitive bridge mode(s), and consumer mode. */
  resolvedMode?: "both" | "dark" | "light";
  /** Static nested at-rule relation between bridge context(s) and selector consumer context. */
  contextRelation?: "none" | "consumer-nested" | "bridge-nested" | "divergent";
  /**
   * Deterministic static precision level for this path under known mode/context constraints.
   * - exact: consumer scope is fully covered by bridge/effect scope
   * - conditional: valid only under narrower mode/bridge conditions
   * - possible: contexts diverge without static alignment
   */
  compatibility?: "exact" | "conditional" | "possible";
  /** Optional bounded runtime-observed evidence correlated to this static impact path. */
  runtimeEvidence?: RuntimeSelectorImpactEvidence;
  sourceVariable?: string;
  sourceVariables?: string[];
  derivedFrom?: "alt-format" | "gradient";
  className?: string;
  classValue?: string;
  /** Optional nested at-rule path that scoped the selector (e.g. @media → @supports). */
  atRuleContext?: string[];
}

export interface RuntimeSelectorImpactEvidence {
  observed: boolean;
  observedModes: Array<"both" | "dark" | "light">;
  observedKinds: Array<"body-class" | "css-variable" | "computed-style">;
  bodyClassChanges: { added: string[]; removed: string[] };
  cssVariableChanges: RuntimeCssVariableChange[];
  computedStyleChanges: RuntimeComputedStyleChange[];
}

export interface RuntimeCssVariableChange {
  name: string;
  before?: string;
  after?: string;
}

export interface RuntimeComputedStyleChange {
  selector: string;
  property: string;
  before?: string;
  after?: string;
}

export interface SelectorInteractionGroup {
  interactionGroup: string;
  interactionMode: string;
  mode: "both" | "dark" | "light";
  settingIds: string[];
  effectKinds: string[];
  note: string;
}

/** Metadata about a theme (modes, variations, fonts). */
export interface FontFileEntry {
  family: string;
  style: string;
  weight: string;
  file: string;
  format: string;
  unicodeRange?: string | null;
}

export interface ThemeMeta {
  /** Display name of the theme. */
  name: string;
  /** Available modes for this theme. */
  modes: Array<"dark" | "light">;
  /** Available variations (e.g. frappe, latte, mocha for catppuccin). */
  variations: string[];
  /** Fonts used by the theme (legacy: references keys in FONT_CSS record). */
  fonts: string[];
  /** Extracted font file metadata for jsDelivr delivery. */
  fontFiles?: FontFileEntry[];
  /** Base theme directory for font files (when variation references base theme's fonts). */
  fontDir?: string;
  /**
   * The Style Settings YAML root id(s) (e.g. "Appearance" for Tokyo Night).
   * Used as the key prefix in Style Settings JSON exports (`<id>@@<setting-id>`).
   * Themes with multiple `@settings` blocks have multiple ids.
   */
  styleSettingsId?: string | string[];
}

/** User-facing configuration for the QuartzTheme plugin. */
export interface ThemeOptions {
  /** Theme identifier (e.g. "tokyo-night", "catppuccin"). */
  theme: string;
  /** Which mode(s) to include: "dark", "light", or "both". */
  mode: "dark" | "light" | "both";
  /** Optional variation within a theme (e.g. "frappe" for catppuccin). */
  variation?: string;
  /**
   * Aspect overrides: pick specific aspects from different themes,
   * or set to `false` to exclude an aspect entirely.
   *
   * @example
   * ```ts
   * aspects: {
   *   callouts: "anuppuccin",   // use callouts from anuppuccin
   *   tables: "minimal",        // use tables from minimal
   *   code: false,              // omit code styling entirely
   * }
   * ```
   */
  aspects?: Partial<Record<AspectKey, string | false>>;
  /**
   * Explicit list of aspects to include. If provided, only these
   * aspects are included (plus any from `aspects` overrides).
   * Omit to include all available aspects.
   */
  include?: AspectKey[];
  /**
   * Callout style variant to apply (e.g. "glass", "draa", "glow").
   * These correspond to the extras/callouts/ SCSS files.
   */
  calloutStyle?: string;
  /** Font overrides. */
  fonts?: { header?: string; body?: string; code?: string };
  /**
   * Style Settings overrides — either a JSON export from Obsidian's Style Settings plugin,
   * or a path to a JSON file containing the export.
   *
   * Keys use the format `<style-settings-id>@@<setting-id>` (e.g. `"minimal-style@@bg1": "#1e1e2e"`).
   * Values can be strings, numbers, or booleans.
   */
  styleSettings?: Record<string, string | number | boolean> | string;
}

/** Shape of a theme's lazy-loadable module. */
export interface ThemeModule {
  theme: ThemeData;
}
