export type {
  BuildCtx,
  QuartzTransformerPlugin,
  QuartzTransformerPluginInstance,
  StaticResources,
} from "@quartz-community/types";

/** All available aspect keys that can be mixed and matched across themes. */
export type AspectKey =
  | "base"
  | "typography"
  | "callouts"
  | "tables"
  | "code"
  | "links"
  | "blockquotes"
  | "checkboxes"
  | "images"
  | "embeds"
  | "cards"
  | "search"
  | "scrollbars"
  | "explorer"
  | "toc"
  | "graph"
  | "popover"
  | "footer"
  | "recentNotes"
  | "listPage"
  | "darkmode"
  | "breadcrumbs"
  | "lists"
  | "misc";

/** Per-aspect CSS strings for a single mode (dark or light). */
export type AspectCSS = Partial<Record<AspectKey, string>>;

/** Theme data for a single theme, generated by the generate script. */
export interface ThemeData {
  meta: ThemeMeta;
  dark: AspectCSS;
  light: AspectCSS;
  /** Optional extra CSS to inject alongside the theme (e.g. CRT effects, snow animations). */
  extras?: string;
}

/** Metadata about a theme (modes, variations, fonts). */
export interface ThemeMeta {
  /** Display name of the theme. */
  name: string;
  /** Available modes for this theme. */
  modes: Array<"dark" | "light">;
  /** Available variations (e.g. frappe, latte, mocha for catppuccin). */
  variations: string[];
  /** Fonts used by the theme. */
  fonts: string[];
}

/** User-facing configuration for the QuartzTheme plugin. */
export interface ThemeOptions {
  /** Theme identifier (e.g. "tokyo-night", "catppuccin"). */
  theme: string;
  /** Which mode(s) to include: "dark", "light", or "both". */
  mode: "dark" | "light" | "both";
  /** Optional variation within a theme (e.g. "frappe" for catppuccin). */
  variation?: string;
  /**
   * Aspect overrides: pick specific aspects from different themes,
   * or set to `false` to exclude an aspect entirely.
   *
   * @example
   * ```ts
   * aspects: {
   *   callouts: "anuppuccin",   // use callouts from anuppuccin
   *   tables: "minimal",        // use tables from minimal
   *   code: false,              // omit code styling entirely
   * }
   * ```
   */
  aspects?: Partial<Record<AspectKey, string | false>>;
  /**
   * Explicit list of aspects to include. If provided, only these
   * aspects are included (plus any from `aspects` overrides).
   * Omit to include all available aspects.
   */
  include?: AspectKey[];
  /**
   * Callout style variant to apply (e.g. "glass", "draa", "glow").
   * These correspond to the extras/callouts/ SCSS files.
   */
  calloutStyle?: string;
  /** Font overrides. */
  fonts?: { header?: string; body?: string; code?: string };
}

/** Shape of a theme's lazy-loadable module. */
export interface ThemeModule {
  theme: ThemeData;
}
