mode: replace
sections:
  - name: Pomme Notes Settings
    id: pomme-notes-settings
    collapsed: false
    settings:
      - id: tinted
        title: Use accent-tinted interface
        type: class-toggle
        default: false
