name: Rosé Pine Themes
id: rosé-pine-theme-settings
settings:
  - id: rosé-pine-theme
    title: Theme variants
    description: Select your preferred theme, Rosé Pine Moon is enabled by setting light mode on
    type: class-select
    allowEmpty: false
    default: rose-norm
    options:
      - label: Rosé Pine
        value: rose-norm
      - label: Rosé Pine Moon
        value: rose-moon
  - id: rosé-pine-theme-accents
    title: Theme accent
    description: Select your preferred accent
    type: class-select
    allowEmpty: false
    default: rp-accent-full
    options:
      - label: Full palette
        value: rp-accent-full
      - label: Love
        value: rp-accent-love
      - label: Rose
        value: rp-accent-rose
      - label: Gold
        value: rp-accent-gold
      - label: Iris
        value: rp-accent-iris
      - label: Pine
        value: rp-accent-pine
      - label: Foam
        value: rp-accent-foam
