// src/extraction-config.js
// TODO: Fix background color mappings
// Probably needs to target the publish container div directly instead of body
const expansions = {
  borderStyle: [
    "border-left-style",
    "border-bottom-style",
    "border-right-style",
    "border-top-style",
  ],
  borderColor: [
    "border-left-color",
    "border-right-color",
    "border-top-color",
    "border-bottom-color",
  ],
  borderWidth: [
    "border-left-width",
    "border-right-width",
    "border-top-width",
    "border-bottom-width",
  ],
  borderRadius: [
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-start-start-radius",
    "border-start-end-radius",
    "border-end-start-radius",
    "border-end-end-radius",
  ],
};

const defaults = {
  border: [
    ...expansions.borderStyle,
    ...expansions.borderColor,
    ...expansions.borderWidth,
    ...expansions.borderRadius,
  ],
  margin: [
    "margin-top",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-block-end",
    "margin-block-start",
    "margin-inline-end",
    "margin-inline-start",
  ],
  padding: ["padding-top", "padding-bottom", "padding-left", "padding-right"],
  transition: [
    "transition-behavior",
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
  ],
  whiteSpace: [
    "white-space-collapse",
    "text-wrap-mode",
    //"white-space-trim", // not implemented in any browser at the moment.
  ],
};

const sets = {
  typography: [
    "color",
    "font-family",
    //"font-size",
    "font-weight",
    "line-height",
  ],
  text: [
    "background-color",
    "color",
    "cursor",
    "filter",
    "font-family",
    //"font-size",
    "font-weight",
    //"line-height",
    //"margin-block-end",
    //"margin-block-start",
    "outline",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-thickness",
    "transition",
    "user-select",
  ],
  // Tables
  table: [
    "background-color",
    "border-collapse",
    "border-spacing",
    "color",
    "font-family",
    "table-layout",
    "width",
    ...defaults.border,
    ...defaults.margin,
  ],
  tableCell: [
    "background-color",
    "color",
    "font-weight",
    "text-align",
    "vertical-align",
    ...defaults.border,
    ...defaults.padding,
  ],
  tableHeader: [
    "background-color",
    "color",
    "font-weight",
    "text-align",
    "vertical-align",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Images and Media
  image: [
    "border-radius",
    "box-shadow",
    "filter",
    "max-width",
    "object-fit",
    ...defaults.border,
    ...defaults.margin,
  ],
  figure: [
    "background-color",
    "text-align",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  figcaption: [
    "color",
    "font-family",
    "font-size",
    "font-style",
    "text-align",
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Embeds
  embed: [
    "background-color",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Frontmatter/Properties
  frontmatter: [
    "background-color",
    "color",
    "font-family",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Tooltips and Popovers
  tooltip: [
    "background-color",
    "box-shadow",
    "color",
    "font-family",
    "font-size",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Progress and Range
  progress: ["accent-color", "background-color", "height", ...defaults.border],
  // Details/Summary (Collapsible)
  details: [
    "background-color",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  summary: [
    "background-color",
    "color",
    "cursor",
    "font-weight",
    "list-style",
    ...defaults.padding,
  ],
  // Keyboard input
  kbd: [
    "background-color",
    "box-shadow",
    "color",
    "font-family",
    "font-size",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Definition lists
  definitionList: [...defaults.margin],
  definitionTerm: ["color", "font-weight", ...defaults.margin],
  definitionDesc: ["color", ...defaults.margin, ...defaults.padding],
  // Subscript/Superscript
  subSup: ["color", "font-size", "vertical-align"],
  // Backlinks
  backlinks: [
    "background-color",
    "color",
    ...defaults.border,
    ...defaults.padding,
  ],
  list: [
    "color",
    //"padding-top",
    //"padding-bottom",
    //"margin-inline-start",
    "text-align",
  ],
  pill: [
    "align-items",
    "background-color",
    "display",
    "font-family",
    //"font-size",
    "font-weight",
    //"line-height",
    "margin-inline-start",
    ...defaults.border,
  ],
  blockquote: [
    "background-color",
    "border-inline-start",
    "font-family",
    "font-style",
    "padding-bottom",
    "padding-top",
    "padding-inline-start",
    "margin-inline-start",
    "margin-inline-end",
  ],
  headings: ["color", "font-family", "text-shadow"],
  callouts: {
    container: [
      "--callout-color",
      //"--callout-icon",
      "background-color",
      //"border-style",
      //"border-color",
      //"border-width",
      //"border-radius",
      "mix-blend-mode",
      //"padding",
      ...defaults.border,
    ],
    content: ["background-color", ...defaults.padding],
    icon: [/*"color", */ "fill", "stroke"],
    title: [
      //"color",
      /*"font-size", */ "gap" /*, "line-height"*/,
      ...defaults.border,
      ...defaults.padding,
    ],
    titleInner: [/*"color",*/ "font-weight"],
  },
  background: ["background-color"],
  mermaid: ["stroke", "fill" /*"filter", "font-family", "font-size"*/],
  math: ["display", "text-align", ...defaults.whiteSpace, "font-family"],
  // ... other property groups
};

export const config = [
  {
    obsidianSelector: `div.quartz-icon-selector`,
    publishSelector: null,
    quartzSelector: "div#quartz-body",
    pseudoElement: "",
    properties: ["--quartz-icon-color"],
  },
  // {
  //   obsidianSelector: `div.mod-root.mod-vertical.workspace-split`,
  //   publishSelector: null,
  //   quartzSelector: "&[data-slug]",
  //   pseudoElement: "",
  //   properties: ["background-color", "color"],
  // },
  {
    obsidianSelector: `body`,
    publishSelector: null,
    quartzSelector: "div#quartz-root",
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  // center content
  {
    obsidianSelector: `div.mod-active.workspace-leaf`,
    publishSelector: null, //TODO
    quartzSelector: `&[data-slug], &[data-slug] .page > div#quartz-body, .page > div#quartz-body div.center, .page > div#quartz-body footer`,
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  // sidebars
  {
    obsidianSelector: `div.workspace-leaf`,
    publishSelector: null, //TODO
    quartzSelector: ".page > div#quartz-body div.sidebar",
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  {
    obsidianSelector: `div.mod-horizontal.mod-left-split.mod-sidedock.workspace-split`,
    publishSelector: null, //TODO
    quartzSelector:
      "&[data-slug] div#quartz-root.page, .page > div#quartz-body div.sidebar.left, .page > div#quartz-body div.sidebar.left:has(.explorer), .page > div#quartz-body div.sidebar.left .explorer .explorer-content",
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  {
    obsidianSelector: `div.mod-horizontal.mod-right-split.mod-sidedock.workspace-split`,
    publishSelector: null, //TODO
    quartzSelector: ".page > div#quartz-body div.sidebar.right",
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  // separators
  {
    obsidianSelector: `hr.workspace-leaf-resize-handle`,
    publishSelector: null, //TODO
    quartzSelector: ".page > div#quartz-body div.sidebar.left",
    pseudoElement: "",
    properties: [
      "border-right-color",
      "border-right-style",
      "border-right-width",
    ],
  },
  {
    obsidianSelector: `hr.workspace-leaf-resize-handle`,
    publishSelector: null, //TODO
    quartzSelector: ".page > div#quartz-body div.sidebar.right",
    pseudoElement: "",
    properties: ["border-left-color", "border-left-style", "border-left-width"],
  },
  // links
  // TODO: add external link to to markdown so it gets added
  {
    obsidianSelector: `a.external-link[data-tooltip-position=\"top\"]`,
    publishSelector: `.markdown-rendered a.external-link`,
    quartzSelector: "a.external, footer a",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `a.internal-link[data-href=\"callouts\"][data-tooltip-position=\"top\"]`,
    publishSelector: `.markdown-rendered a.internal-link`,
    quartzSelector: "a.internal, .breadcrumb-container .breadcrumb-element > a",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `a.internal-link.is-unresolved[data-href=\"https://example.com\"][data-tooltip-position=\"top\"]`,
    publishSelector: `.markdown-rendered a.internal-link.is-unresolved`,
    quartzSelector: "a.internal.broken",
    pseudoElement: "",
    properties: sets.text,
  },
  // link hover states
  {
    obsidianSelector: `a.external-link[data-tooltip-position=\"top\"]:hover`,
    publishSelector: `.markdown-rendered a.external-link:hover`,
    quartzSelector: "a.external:hover, footer a:hover",
    pseudoElement: "",
    properties: [
      "text-decoration",
      "text-decoration-color",
      "text-decoration-line",
      "text-decoration-style",
      "color",
    ],
  },
  {
    obsidianSelector: `a.internal-link[data-href=\"callouts\"][data-tooltip-position=\"top\"]:hover`,
    publishSelector: `.markdown-rendered a.internal-link:hover`,
    quartzSelector:
      "a.internal:hover, .breadcrumb-container .breadcrumb-element > a:hover",
    pseudoElement: "",
    properties: [
      "text-decoration",
      "text-decoration-color",
      "text-decoration-line",
      "text-decoration-style",
      "color",
    ],
  },
  // text
  {
    obsidianSelector: `p`,
    publishSelector: `.markdown-rendered p`,
    quartzSelector: "p",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `strong`,
    publishSelector: `strong`,
    quartzSelector: ".page article p > strong, strong",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `strong`,
    publishSelector: `b`,
    quartzSelector: ".page article p > b, b",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `em`,
    publishSelector: `em`,
    quartzSelector: ".page article p > em, em",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `em`,
    publishSelector: `i`,
    quartzSelector: ".page article p > i, i",
    pseudoElement: "",
    properties: sets.text,
  },
  /*
      {
        obsidianSelector: `u`,
        publishSelector: `u`,
        quartzSelector: ".page article p > u, u",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `s`,
        publishSelector: `s`,
        quartzSelector: ".page article p > s, s",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `strong > em`,
        publishSelector: `strong > em`,
        quartzSelector: ".page article p > strong > em, strong > em",
        pseudoElement: "",
        properties: sets.text,
      },
      */
  {
    obsidianSelector: `mark`,
    publishSelector: `.markdown-rendered mark`,
    quartzSelector: ".text-highlight",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `del`,
    publishSelector: `del`,
    quartzSelector: "del",
    pseudoElement: "",
    properties: sets.text,
  },

  // Selected state for search
  {
    obsidianSelector: `div.is-selected.mod-complex.suggestion-item`,
    publishSelector: `.suggestion-item.is-selected`,
    quartzSelector:
      ".search>.search-container>.search-space>.search-layout>.results-container .result-card:hover, .search>.search-container>.search-space>.search-layout>.results-container .result-card:focus, .search>.search-container>.search-space>.search-layout>.results-container .result-card.focus:not(:has(~ .result-card:hover, ~ .result-card:focus))",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border-radius",
      ...expansions.borderRadius,
      "color",
    ],
  },
  {
    obsidianSelector: `div.mod-complex.suggestion-item`,
    publishSelector: `div.suggestion-item`,
    quartzSelector:
      ".search>.search-container>.search-space>.search-layout>.results-container .result-card:has(~ .result-card.focus:not(:has(~ .result-card:hover, ~ .result-card:focus)), ~ .result-card:focus, ~ .result-card:hover)",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border-radius",
      ...defaults.border,
      "color",
    ],
  },
  {
    obsidianSelector: `hr`,
    publishSelector: `.markdown-rendered hr`,
    quartzSelector: "hr",
    pseudoElement: "",
    properties: [
      //"border",
      //"border-color",
      //"border-style",
      //"border-top",
      ...defaults.border,
      "box-shadow",
      //"margin",
      ...defaults.margin,
    ],
  },
  // tag pills
  {
    obsidianSelector: `div.multi-select-pill`,
    publishSelector: `div.multi-select-pill`,
    quartzSelector:
      "a.internal.tag-link, .search > .search-container > .search-space > .search-layout > .results-container .result-card > ul > li > .match-tag",
    pseudoElement: "",
    properties: sets.pill,
  },
  {
    obsidianSelector: `div.multi-select-pill-content`,
    publishSelector: `div.multi-select-pill > div.multi-select-pill-content`,
    quartzSelector: "a.internal.tag-link::before",
    pseudoElement: "",
    properties: ["color"],
  },
  // list items
  {
    obsidianSelector: `li[data-line=\"0\"]`,
    publishSelector: `.markdown-rendered ul > li`,
    quartzSelector: "ul > li",
    pseudoElement: "",
    properties: sets.list,
  },
  {
    obsidianSelector: `span.list-bullet::after`,
    publishSelector: `.markdown-rendered ul > li::marker`,
    quartzSelector: "ul > li::marker",
    pseudoElement: "::after",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "color",
      // "content",
      "pointer-events",
      "transform",
      "transition",
    ],
  },
  {
    obsidianSelector: `li[data-line=\"0\"]`,
    publishSelector: `.markdown-rendered ol > li`,
    quartzSelector: "ol > li",
    pseudoElement: "",
    properties: sets.list,
  },
  {
    // TODO: add ::marker to pseudoElements
    obsidianSelector: `span.list-bullet::after`,
    publishSelector: `.markdown-rendered ol > li::marker`,
    quartzSelector: "ol > li::marker",
    pseudoElement: "::marker",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "color",
      // "content",
      "pointer-events",
      "transform",
      "transition",
    ],
  },
  // code blocks
  {
    obsidianSelector: `code`,
    publishSelector: `.markdown-rendered code`,
    quartzSelector: "code",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "color",
      "font-family",
      //"font-size",
      //"padding",
      ...defaults.padding,
    ],
  },
  {
    obsidianSelector: `pre.language-js`,
    publishSelector: `.markdown-rendered pre > code`,
    quartzSelector: "pre > code, pre:has(> code)",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "overflow-x",
      //"padding",
      ...defaults.padding,
      //"white-space",
      ...defaults.whiteSpace,
    ],
  },
  {
    obsidianSelector: `pre`,
    publishSelector: `:not(pre) > code[class*="language-"], pre[class*="language-"]`,
    quartzSelector: "pre:has(> code)",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "overflow-x",
      //"padding",
      ...defaults.padding,
      //"white-space",
      ...defaults.whiteSpace,
    ],
  },
  // checkboxes
  {
    obsidianSelector: `input.task-list-item-checkbox[data-line=\"0\"]`,
    publishSelector: `ul.contains-task-list > li.task-list-item > .task-list-item-checkbox`,
    quartzSelector: "input[type=checkbox]",
    pseudoElement: "",
    properties: [
      "appearance",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      //"padding",
      ...defaults.padding,
      //"margin",
      ...defaults.margin,
      "width",
      //"margin-inline-start",
      //"margin-inline-end",
      "transition",
      "position",
      "top",
    ],
  },
  {
    obsidianSelector: `li.task-list-item[data-line=\"0\"][data-task=\"\"]`,
    publishSelector: `ul.contains-task-list > li.task-list-item`,
    quartzSelector: "ul > li.task-list-item",
    pseudoElement: "",
    properties: ["list-style", "text-align", "display"],
  },
  {
    obsidianSelector: `li.is-checked.task-list-item[data-line=\"1\"][data-task=\"x\"]::after`,
    publishSelector: `ul.contains-task-list > li.task-list-item > input[type=checkbox]:checked`,
    quartzSelector: "input[type=checkbox]:checked:after",
    pseudoElement: "::after",
    properties: [
      "content",
      "top",
      "inset-inline-start",
      "position",
      "width",
      "display",
      "background-color",
      "-webkit-mask-position",
      "-webkit-mask-size",
      "-webkit-mask-repeat",
      "-webkit-mask-image",
    ],
  },
  {
    obsidianSelector: `li.is-checked.task-list-item[data-line=\"1\"][data-task=\"x\"]`,
    publishSelector: `ul > li.task-list-item[data-task="x"]`,
    quartzSelector: ".page article li:has(>input[type=checkbox]:checked)",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  // blockquote
  {
    obsidianSelector: `blockquote`,
    publishSelector: `.markdown-rendered blockquote`,
    quartzSelector: "blockquote",
    pseudoElement: "",
    properties: sets.blockquote,
  },
  // footnotes
  {
    obsidianSelector: `a.footnote-backref.footnote-link`,
    publishSelector: `.footnote-backref`,
    quartzSelector: ".data-footnote-backref",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  // search
  {
    obsidianSelector: `input[type=\"search\"]`,
    publishSelector: `.site-body-left-column input.search-bar`,
    quartzSelector: ".search > .search-button",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      "color",
      "font-family",
      //"font-size",
      //"padding",
    ],
  },
  {
    obsidianSelector: `div.prompt`,
    publishSelector: `.search-results`,
    quartzSelector: ".search > .search-container > .search-space",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-radius",
      ...defaults.border,
      "box-shadow",
    ],
  },
  {
    obsidianSelector: `input.prompt-input[type=\"text\"]`,
    publishSelector: null,
    quartzSelector: ".search > .search-container > .search-space > input",
    pseudoElement: "",
    properties: [
      "background-color",
      //"border",
      //"border-bottom",
      //"border-radius",
      ...defaults.border,
      "box-shadow",
    ],
  },
  {
    obsidianSelector: `div.prompt-results`,
    publishSelector: `.search-results > *`,
    quartzSelector: ".search > .search-container > .search-space > *",
    pseudoElement: "",
    properties: sets.text,
  },
  {
    obsidianSelector: `div.prompt`,
    publishSelector: `div.search-results`,
    quartzSelector:
      ".search > .search-container > .search-space > .search-layout, .search > .search-container > .search-space > .search-layout.display-results",
    pseudoElement: "",
    properties: [
      //"border-color"
      ...defaults.border,
    ],
  },
  {
    obsidianSelector: `div.mod-complex.suggestion-item`,
    publishSelector: `.search-results .suggestion-item`,
    quartzSelector:
      ".search > .search-container > .search-space > .search-layout > .results-container",
    pseudoElement: "",
    properties: ["color"],
  },
  {
    obsidianSelector: `div.mod-complex.suggestion-item`,
    publishSelector: `div.search-results .suggestion-item`,
    quartzSelector:
      ".search > .search-container > .search-space > .search-layout > .results-container .result-card",
    pseudoElement: "",
    properties: [
      //"border-color"
      ...defaults.border,
    ],
  },
  {
    obsidianSelector: `div.is-selected.mod-complex.suggestion-item`,
    publishSelector: `.search-results .suggestion-item.is-selected`,
    quartzSelector:
      ".search > .search-container > .search-space > .search-layout > .results-container > .result-card:hover, .search > .search-container > .search-space > .search-layout > .results-container > .result-card:focus, .search > .search-container > .search-space > .search-layout > .results-container > .result-card.focus:not(:has(~ .result-card:hover, ~ .result-card:focus))",
    pseudoElement: "",
    properties: ["color", "font-weight", "background-color"],
  },
  {
    obsidianSelector: `div.is-selected.mod-complex.suggestion-item`,
    publishSelector: `div.search-results .suggestion-item.is-selected`,
    quartzSelector:
      ".search > .search-container > .search-space > .search-layout > .results-container > .result-card:hover .card-title, .search > .search-container > .search-space > .search-layout > .results-container > .result-card:hover .card-description, .search > .search-container > .search-space > .search-layout > .results-container > .result-card:focus .card-title, .search > .search-container > .search-space > .search-layout > .results-container > .result-card:focus .card-description, .search > .search-container > .search-space > .search-layout > .results-container > .result-card.focus:not(:has(~ .result-card:hover, ~ .result-card:focus)) .card-title, .search > .search-container > .search-space > .search-layout > .results-container > .result-card.focus:not(:has(~ .result-card:hover, ~ .result-card:focus)) .card-description",
    pseudoElement: "",
    properties: ["color"],
  },
  {
    obsidianSelector: `h1[data-heading=\"This is a heading 1\"]`,
    publishSelector: `.published-container .markdown-rendered h1`,
    quartzSelector: "h1",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `h2[data-heading=\"This is a heading 2\"]`,
    publishSelector: `.published-container .markdown-rendered h2`,
    quartzSelector: "h2",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `h3[data-heading=\"This is a heading 3\"]`,
    publishSelector: `.published-container .markdown-rendered h3`,
    quartzSelector: "h3",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `h4[data-heading=\"This is a heading 4\"]`,
    publishSelector: `.published-container .markdown-rendered h4`,
    quartzSelector: "h4",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `h5[data-heading=\"This is a heading 5\"]`,
    publishSelector: `.published-container .markdown-rendered h5`,
    quartzSelector: "h5",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `h6[data-heading=\"This is a heading 6\"]`,
    publishSelector: `.published-container .markdown-rendered h6`,
    quartzSelector: "h6",
    pseudoElement: "",
    properties: sets.headings,
  },
  {
    obsidianSelector: `div.inline-title`,
    publishSelector: null, //TODO
    quartzSelector: "h2.page-title, h2.page-title a",
    pseudoElement: "",
    properties: sets.headings,
  },
  // outline
  {
    obsidianSelector: `div.is-clickable.mod-collapsible.tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-0",
    pseudoElement: "",
    properties: [/*"font-size", "line-height", */ "font-weight"],
  },
  {
    obsidianSelector: `div.tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item > .tree-item-children`,
    quartzSelector: null /*"li.depth-0 + li.depth-1"*/,
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  /*
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item > .tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-1",
    pseudoElement: "",
    properties: ["font-weight"],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item > .tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item > .tree-item-children`,
    quartzSelector: "li.depth-1 + li.depth-2",
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item > .tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-2",
    pseudoElement: "",
    properties: ["font-weight"],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item > .tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item > .tree-item-children`,
    quartzSelector: "li.depth-2 + li.depth-3",
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-3",
    pseudoElement: "",
    properties: ["font-weight"],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    quartzSelector: "li.depth-3 + li.depth-4",
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-4",
    pseudoElement: "",
    properties: ["font-weight"],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    quartzSelector: "li.depth-4 + li.depth-5",
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
    quartzSelector: "li.depth-5",
    pseudoElement: "",
    properties: ["font-weight"],
  },
  {
    obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    publishSelector: `.outline-view-outer .outline-view .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
    quartzSelector: "li.depth-5 + li.depth-6",
    pseudoElement: "",
    properties: [
      "margin-inline-start",
      "padding-inline-start",
      "border-inline-start",
    ],
  },
  */
  // table
  // scrollbars
  // TODO: add ::scrollbar to pseudoElements
  {
    obsidianSelector: `div.markdown-preview-section.markdown-preview-sizer`,
    publishSelector: `.markdown-preview-sizer`,
    quartzSelector: "::-webkit-scrollbar",
    pseudoElement: "::-webkit-scrollbar",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `div.markdown-preview-section.markdown-preview-sizer`,
    publishSelector: `.markdown-preview-sizer`,
    quartzSelector: "::-webkit-scrollbar-thumb",
    pseudoElement: "::-webkit-scrollbar-thumb",
    properties: [
      "background-color",
      //"border-radius",
      //"border-width",
      //"border",
      //"border-color",
      ...defaults.border,
      "box-shadow",
    ],
  },
  // note
  // FIXME: fixed up until here
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"note\"]`,
    publishSelector: `.callout[data-callout="note"]`,
    // quartzSelector: ".callout[data-callout]",
    quartzSelector: ".callout",
    pseudoElement: "",
    properties: [
      "--callout-color",
      //"--callout-icon",
      //"background-color",
      //"border-style",
      //"border-color",
      //"border-width",
      //"border-radius",
      ...defaults.border,
      "mix-blend-mode",
      //"padding",
      ...defaults.padding,
    ],
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="note"] > .callout-title`,
    // quartzSelector: ".callout[data-callout] .callout-title",
    quartzSelector: ".callout .callout-title",
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `.callout[data-callout="note"] > .callout-title > .callout-icon > svg.svg-icon`,
    publishSelector: `.callout[data-callout="note"] > .callout-title > .callout-icon > svg.svg-icon`,
    // quartzSelector: ".callout[data-callout] .callout-title .callout-icon",
    quartzSelector: ".callout .callout-title .callout-icon",
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    // quartzSelector:
    // ".callout[data-callout] .callout-title > .callout-title-inner > p",
    quartzSelector: ".callout .callout-title > .callout-title-inner > p",
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    // quartzSelector: ".callout[data-callout] > .callout-content",
    quartzSelector: ".callout > .callout-content",
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  // note
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"note\"]`,
    publishSelector: `.callout[data-callout="note"]`,
    quartzSelector: `.callout[data-callout="note"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-pencil.svg-icon`,
    publishSelector: `.callout[data-callout="note"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="note"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // abstract
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"abstract\"]`,
    publishSelector: `.callout[data-callout="abstract"]`,
    quartzSelector: `.callout[data-callout="abstract"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-clipboard-list.svg-icon`,
    publishSelector: `.callout[data-callout="abstract"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="abstract"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // info
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"info\"]`,
    publishSelector: `.callout[data-callout="info"]`,
    quartzSelector: `.callout[data-callout="info"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-info.svg-icon`,
    publishSelector: `.callout[data-callout="info"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="info"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // todo
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"todo\"]`,
    publishSelector: `.callout[data-callout="todo"]`,
    quartzSelector: `.callout[data-callout="todo"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-check-circle-2.svg-icon`,
    publishSelector: `.callout[data-callout="todo"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="todo"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // tip
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"tip\"]`,
    publishSelector: `.callout[data-callout="tip"]`,
    quartzSelector: `.callout[data-callout="tip"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-flame.svg-icon`,
    publishSelector: `.callout[data-callout="tip"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="tip"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // success
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"success\"]`,
    publishSelector: `.callout[data-callout="success"]`,
    quartzSelector: `.callout[data-callout="success"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-check.svg-icon`,
    publishSelector: `.callout[data-callout="success"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="success"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // question
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"question\"]`,
    publishSelector: `.callout[data-callout="question"]`,
    quartzSelector: `.callout[data-callout="question"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-help-circle.svg-icon`,
    publishSelector: `.callout[data-callout="question"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="question"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // warning
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"warning\"]`,
    publishSelector: `.callout[data-callout="warning"]`,
    quartzSelector: `.callout[data-callout="warning"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-alert-triangle.svg-icon`,
    publishSelector: `.callout[data-callout="warning"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="warning"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // danger
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"danger\"]`,
    publishSelector: `.callout[data-callout="danger"]`,
    quartzSelector: `.callout[data-callout="danger"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-zap.svg-icon`,
    publishSelector: `.callout[data-callout="danger"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="danger"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // failure
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"failure\"]`,
    publishSelector: `.callout[data-callout="failure"]`,
    quartzSelector: `.callout[data-callout="failure"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-x.svg-icon`,
    publishSelector: `.callout[data-callout="failure"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="failure"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // bug
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"bug\"]`,
    publishSelector: `.callout[data-callout="bug"]`,
    quartzSelector: `.callout[data-callout="bug"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-bug.svg-icon`,
    publishSelector: `.callout[data-callout="bug"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="bug"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // example
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"example\"]`,
    publishSelector: `.callout[data-callout="example"]`,
    quartzSelector: `.callout[data-callout="example"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-list.svg-icon`,
    publishSelector: `.callout[data-callout="example"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="example"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // quote
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"quote\"]`,
    publishSelector: `.callout[data-callout="quote"]`,
    quartzSelector: `.callout[data-callout="quote"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-quote.svg-icon`,
    publishSelector: `.callout[data-callout="quote"] > .callout-title > .callout-icon > svg.svg-icon`,
    quartzSelector: `.callout[data-callout="quote"] .callout-title .callout-icon`,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  // === TABLES ===
  {
    obsidianSelector: `table`,
    publishSelector: `.markdown-rendered table`,
    quartzSelector: "table",
    pseudoElement: "",
    properties: sets.table,
  },
  {
    obsidianSelector: `thead`,
    publishSelector: `.markdown-rendered thead`,
    quartzSelector: "thead",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `tbody`,
    publishSelector: `.markdown-rendered tbody`,
    quartzSelector: "tbody",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `th`,
    publishSelector: `.markdown-rendered th`,
    quartzSelector: "th",
    pseudoElement: "",
    properties: sets.tableHeader,
  },
  {
    obsidianSelector: `td`,
    publishSelector: `.markdown-rendered td`,
    quartzSelector: "td",
    pseudoElement: "",
    properties: sets.tableCell,
  },
  {
    obsidianSelector: `tr`,
    publishSelector: `.markdown-rendered tr`,
    quartzSelector: "tr",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `tbody tr:nth-child(even)`,
    publishSelector: `.markdown-rendered tbody tr:nth-child(even)`,
    quartzSelector: "tbody tr:nth-child(even)",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `tbody tr:nth-child(odd)`,
    publishSelector: `.markdown-rendered tbody tr:nth-child(odd)`,
    quartzSelector: "tbody tr:nth-child(odd)",
    pseudoElement: "",
    properties: ["background-color"],
  },
  // === IMAGES AND MEDIA ===
  {
    obsidianSelector: `img`,
    publishSelector: `.markdown-rendered img`,
    quartzSelector: "img",
    pseudoElement: "",
    properties: sets.image,
  },
  {
    obsidianSelector: `figure`,
    publishSelector: `.markdown-rendered figure`,
    quartzSelector: "figure",
    pseudoElement: "",
    properties: sets.figure,
  },
  {
    obsidianSelector: `figcaption`,
    publishSelector: `.markdown-rendered figcaption`,
    quartzSelector: "figcaption",
    pseudoElement: "",
    properties: sets.figcaption,
  },
  {
    obsidianSelector: `video`,
    publishSelector: `.markdown-rendered video`,
    quartzSelector: "video",
    pseudoElement: "",
    properties: sets.image,
  },
  {
    obsidianSelector: `audio`,
    publishSelector: `.markdown-rendered audio`,
    quartzSelector: "audio",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border, ...defaults.padding],
  },
  // === EMBEDS / TRANSCLUSIONS ===
  {
    obsidianSelector: `.internal-embed`,
    publishSelector: `.internal-embed`,
    quartzSelector: ".transclude",
    pseudoElement: "",
    properties: sets.embed,
  },
  {
    obsidianSelector: `.markdown-embed`,
    publishSelector: `.markdown-embed`,
    quartzSelector: ".transclude-inner",
    pseudoElement: "",
    properties: sets.embed,
  },
  {
    obsidianSelector: `.file-embed`,
    publishSelector: `.file-embed`,
    quartzSelector: ".file-embed",
    pseudoElement: "",
    properties: sets.embed,
  },
  // === FRONTMATTER / PROPERTIES ===
  {
    obsidianSelector: `.frontmatter-container`,
    publishSelector: `.frontmatter-container`,
    quartzSelector: ".frontmatter",
    pseudoElement: "",
    properties: sets.frontmatter,
  },
  {
    obsidianSelector: `.metadata-container`,
    publishSelector: `.metadata-container`,
    quartzSelector: ".metadata",
    pseudoElement: "",
    properties: sets.frontmatter,
  },
  {
    obsidianSelector: `.metadata-properties`,
    publishSelector: `.metadata-properties`,
    quartzSelector: ".metadata-properties",
    pseudoElement: "",
    properties: sets.frontmatter,
  },
  // === TOOLTIPS AND POPOVERS ===
  {
    obsidianSelector: `.tooltip`,
    publishSelector: `.tooltip`,
    quartzSelector: ".tooltip",
    pseudoElement: "",
    properties: sets.tooltip,
  },
  {
    obsidianSelector: `.popover`,
    publishSelector: `.popover`,
    quartzSelector: ".popover",
    pseudoElement: "",
    properties: sets.tooltip,
  },
  // === PROGRESS AND INPUT ELEMENTS ===
  {
    obsidianSelector: `progress`,
    publishSelector: `progress`,
    quartzSelector: "progress",
    pseudoElement: "",
    properties: sets.progress,
  },
  {
    obsidianSelector: `input[type="range"]`,
    publishSelector: `input[type="range"]`,
    quartzSelector: "input[type=range]",
    pseudoElement: "",
    properties: ["accent-color", "background-color", ...defaults.border],
  },
  {
    obsidianSelector: `input[type="text"]`,
    publishSelector: `input[type="text"]`,
    quartzSelector: "input[type=text]",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "font-family",
      ...defaults.border,
      ...defaults.padding,
    ],
  },
  // === DETAILS / SUMMARY (COLLAPSIBLE) ===
  {
    obsidianSelector: `details`,
    publishSelector: `details`,
    quartzSelector: "details",
    pseudoElement: "",
    properties: sets.details,
  },
  {
    obsidianSelector: `summary`,
    publishSelector: `summary`,
    quartzSelector: "summary",
    pseudoElement: "",
    properties: sets.summary,
  },
  {
    obsidianSelector: `details[open]`,
    publishSelector: `details[open]`,
    quartzSelector: "details[open]",
    pseudoElement: "",
    properties: sets.details,
  },
  // === KEYBOARD INPUT ===
  {
    obsidianSelector: `kbd`,
    publishSelector: `kbd`,
    quartzSelector: "kbd",
    pseudoElement: "",
    properties: sets.kbd,
  },
  // === DEFINITION LISTS ===
  {
    obsidianSelector: `dl`,
    publishSelector: `dl`,
    quartzSelector: "dl",
    pseudoElement: "",
    properties: sets.definitionList,
  },
  {
    obsidianSelector: `dt`,
    publishSelector: `dt`,
    quartzSelector: "dt",
    pseudoElement: "",
    properties: sets.definitionTerm,
  },
  {
    obsidianSelector: `dd`,
    publishSelector: `dd`,
    quartzSelector: "dd",
    pseudoElement: "",
    properties: sets.definitionDesc,
  },
  // === SUBSCRIPT / SUPERSCRIPT ===
  {
    obsidianSelector: `sub`,
    publishSelector: `sub`,
    quartzSelector: "sub",
    pseudoElement: "",
    properties: sets.subSup,
  },
  {
    obsidianSelector: `sup`,
    publishSelector: `sup`,
    quartzSelector: "sup",
    pseudoElement: "",
    properties: sets.subSup,
  },
  // === ABBREVIATIONS ===
  {
    obsidianSelector: `abbr`,
    publishSelector: `abbr`,
    quartzSelector: "abbr",
    pseudoElement: "",
    properties: ["color", "cursor", "text-decoration", "text-decoration-style"],
  },
  // === BACKLINKS PANEL ===
  {
    obsidianSelector: `.backlink-pane`,
    publishSelector: `.backlink-pane`,
    quartzSelector: ".backlinks",
    pseudoElement: "",
    properties: sets.backlinks,
  },
  {
    obsidianSelector: `.backlink-pane .tree-item`,
    publishSelector: `.backlink-pane .tree-item`,
    quartzSelector: ".backlinks ul li",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      ...defaults.border,
      ...defaults.padding,
    ],
  },
  {
    obsidianSelector: `.backlink-pane .tree-item-self`,
    publishSelector: `.backlink-pane .tree-item-self`,
    quartzSelector: ".backlinks ul li a",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  // === EXTENDED CHECKBOX STATES ===
  {
    obsidianSelector: `li.task-list-item[data-task="-"]`,
    publishSelector: `li.task-list-item[data-task="-"]`,
    quartzSelector: "li.task-list-item[data-task='-']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task=">"]`,
    publishSelector: `li.task-list-item[data-task=">"]`,
    quartzSelector: "li.task-list-item[data-task='>']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="/"]`,
    publishSelector: `li.task-list-item[data-task="/"]`,
    quartzSelector: "li.task-list-item[data-task='/']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="?"]`,
    publishSelector: `li.task-list-item[data-task="?"]`,
    quartzSelector: "li.task-list-item[data-task='?']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="!"]`,
    publishSelector: `li.task-list-item[data-task="!"]`,
    quartzSelector: "li.task-list-item[data-task='!']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="*"]`,
    publishSelector: `li.task-list-item[data-task="*"]`,
    quartzSelector: "li.task-list-item[data-task='*']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="l"]`,
    publishSelector: `li.task-list-item[data-task="l"]`,
    quartzSelector: "li.task-list-item[data-task='l']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="b"]`,
    publishSelector: `li.task-list-item[data-task="b"]`,
    quartzSelector: "li.task-list-item[data-task='b']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="i"]`,
    publishSelector: `li.task-list-item[data-task="i"]`,
    quartzSelector: "li.task-list-item[data-task='i']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="S"]`,
    publishSelector: `li.task-list-item[data-task="S"]`,
    quartzSelector: "li.task-list-item[data-task='S']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="I"]`,
    publishSelector: `li.task-list-item[data-task="I"]`,
    quartzSelector: "li.task-list-item[data-task='I']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="p"]`,
    publishSelector: `li.task-list-item[data-task="p"]`,
    quartzSelector: "li.task-list-item[data-task='p']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="c"]`,
    publishSelector: `li.task-list-item[data-task="c"]`,
    quartzSelector: "li.task-list-item[data-task='c']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="f"]`,
    publishSelector: `li.task-list-item[data-task="f"]`,
    quartzSelector: "li.task-list-item[data-task='f']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="k"]`,
    publishSelector: `li.task-list-item[data-task="k"]`,
    quartzSelector: "li.task-list-item[data-task='k']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="u"]`,
    publishSelector: `li.task-list-item[data-task="u"]`,
    quartzSelector: "li.task-list-item[data-task='u']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="d"]`,
    publishSelector: `li.task-list-item[data-task="d"]`,
    quartzSelector: "li.task-list-item[data-task='d']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="w"]`,
    publishSelector: `li.task-list-item[data-task="w"]`,
    quartzSelector: "li.task-list-item[data-task='w']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `::selection`,
    publishSelector: `::selection`,
    quartzSelector: "::selection",
    pseudoElement: "::selection",
    properties: ["background-color", "color"],
  },
  {
    obsidianSelector: `input::placeholder`,
    publishSelector: `input::placeholder`,
    quartzSelector: "input::placeholder",
    pseudoElement: "::placeholder",
    properties: ["color", "opacity"],
  },

  {
    obsidianSelector: `mjx-container.MathJax`,
    publishSelector: `.math-block > mjx-container.MathJax`,
    quartzSelector: ".katex-display > .katex",
    pseudoElement: "",
    properties: sets.math,
  },
  {
    obsidianSelector: `mjx-container.MathJax`,
    publishSelector: `div.math-block > mjx-container.MathJax`,
    quartzSelector: ".katex-display > .katex > .katex-html",
    pseudoElement: "",
    properties: ["font-family"],
  },
  {
    obsidianSelector: `mjx-math.MJX-TEX`,
    publishSelector: `.math-inline > mjx-container.MathJax > mjx-math`,
    quartzSelector: ".katex > .katex-html",
    pseudoElement: "",
    properties: ["font-family"],
  },
  // graph
  // TODO: add Publish selector + colors
  /*
  {
    obsidianSelector: `span.quartz-graph-target`,
    publishSelector: null,
    quartzSelector: "div.graph",
    pseudoElement: "",
    properties: [
      "--quartz-graph-text",
      "--quartz-graph-line",
      "--quartz-graph-node",
      "--quartz-graph-node-unresolved",
      "--quartz-graph-node-focused",
      "--quartz-graph-node-tag",
      "--quartz-graph-node-attachment",
    ],
  },
  */
  // explorer
  {
    obsidianSelector: `div.is-clickable.nav-file-title.tappable.tree-item-self[data-path=\"callouts.md\"]`,
    publishSelector: `.nav-view-outer .tree-item-self a`,
    quartzSelector: ".explorer .explorer-content ul.explorer-ul li a",
    pseudoElement: "",
    properties: [
      "color",
      "cursor",
      "font-family",
      //"font-size",
      "font-weight",
      //"line-height",
      "text-decoration",
    ],
  },
  {
    // active
    obsidianSelector: `div.is-active.is-clickable.nav-file-title.tappable.tree-item-self[data-path=\"integrations.md\"]`,
    publishSelector: `.nav-view-outer .tree-item-self.mod-active`,
    quartzSelector:
      ".explorer .explorer-content ul.explorer-ul li:has(> .active)",
    pseudoElement: "",
    properties: [
      "background-color",
      ...defaults.border,
      "color",
      "cursor",
      ...defaults.transition,
    ],
  },
  {
    // closed
    obsidianSelector: `div.is-clickable.mod-collapsible.nav-folder-title.tree-item-self[data-path=\"folder/collapsed\"]`,
    publishSelector: `.nav-view-outer .nav-view > .tree-item.is-collapsed > .tree-item-children > .tree-item > .tree-item-self`,
    quartzSelector:
      ".explorer .explorer-content li:has(> .folder-outer:not(.open)) > .folder-container",
    pseudoElement: "",
    properties: [
      "color",
      "cursor",
      "font-family",
      //"font-size",
      "font-weight",
      //"line-height",
      "text-decoration",
    ],
  },
  {
    // open
    obsidianSelector: `div.is-clickable.mod-collapsible.nav-folder-title.tree-item-self[data-path=\"folder\"]`,
    publishSelector: `.nav-view-outer .nav-view > .tree-item > .tree-item-children > .tree-item > .tree-item-self`,
    quartzSelector:
      ".explorer .explorer-content li:has(> .folder-outer.open) > .folder-container",
    pseudoElement: "",
    properties: [
      "color",
      "cursor",
      "font-family",
      //"font-size",
      "font-weight",
      //"line-height",
      "text-decoration",
    ],
  },
  // === TABLE OF CONTENTS ===
  {
    obsidianSelector: `.outline-view-outer .outline-view`,
    publishSelector: `.outline-view-outer .outline-view`,
    quartzSelector: ".toc",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.outline-view-outer .tree-item-self`,
    publishSelector: `.outline-view-outer .tree-item-self`,
    quartzSelector: "button.toc-header",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "cursor",
      "font-family",
      "font-weight",
    ],
  },
  {
    obsidianSelector: `.outline-view-outer .tree-item-self`,
    publishSelector: `.outline-view-outer .tree-item-self`,
    quartzSelector: "button.toc-header h3",
    pseudoElement: "",
    properties: ["color", "font-family", "font-weight"],
  },
  {
    obsidianSelector: `.outline-view-outer .tree-item-inner`,
    publishSelector: `.outline-view-outer .tree-item-inner`,
    quartzSelector: "ul.toc-content.overflow > li > a",
    pseudoElement: "",
    properties: ["color", "font-family", "font-weight", "text-decoration"],
  },
  {
    obsidianSelector: `.outline-view-outer .tree-item-inner:hover`,
    publishSelector: `.outline-view-outer .tree-item-inner:hover`,
    quartzSelector: "ul.toc-content.overflow > li > a:hover",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  // === GRAPH COMPONENT ===
  {
    obsidianSelector: `.graph-view-container`,
    publishSelector: `.graph-view-container`,
    quartzSelector: ".graph",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `.graph-view-container`,
    publishSelector: `.graph-view-container`,
    quartzSelector: ".graph > h3",
    pseudoElement: "",
    properties: ["color", "font-family", "font-weight"],
  },
  {
    obsidianSelector: `.graph-view-container .graph-controls`,
    publishSelector: `.graph-view-container`,
    quartzSelector: ".graph > .graph-outer",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.clickable-icon.graph-controls-button`,
    publishSelector: `.clickable-icon`,
    quartzSelector: ".graph > .graph-outer > .global-graph-icon",
    pseudoElement: "",
    properties: ["background-color", "color", "cursor", ...defaults.border],
  },
  {
    obsidianSelector: `.clickable-icon.graph-controls-button:hover`,
    publishSelector: `.clickable-icon:hover`,
    quartzSelector: ".graph > .graph-outer > .global-graph-icon:hover",
    pseudoElement: "",
    properties: ["background-color", "color"],
  },
  {
    obsidianSelector: `.graph-view-container`,
    publishSelector: `.graph-view-container`,
    quartzSelector: ".graph > .global-graph-outer",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `.graph-view-container .graph-controls`,
    publishSelector: `.graph-view-container`,
    quartzSelector: ".graph > .global-graph-outer > .global-graph-container",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  // === POPOVER COMPONENT ===
  {
    obsidianSelector: `.popover.hover-popover`,
    publishSelector: `.popover`,
    quartzSelector: ".popover",
    pseudoElement: "",
    properties: sets.tooltip,
  },
  {
    obsidianSelector: `.popover.hover-popover .markdown-preview-view`,
    publishSelector: `.popover .markdown-preview-view`,
    quartzSelector: ".popover > .popover-inner",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "font-family",
      "box-shadow",
      ...defaults.border,
    ],
  },
  // === FOOTER COMPONENT ===
  {
    obsidianSelector: `.status-bar`,
    publishSelector: `.site-footer`,
    quartzSelector: "footer",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "font-family",
      ...defaults.border,
    ],
  },
  {
    obsidianSelector: `.status-bar-item`,
    publishSelector: `.site-footer a`,
    quartzSelector: "footer ul li a",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  // === RECENT NOTES COMPONENT ===
  {
    obsidianSelector: `.nav-header`,
    publishSelector: `.nav-header`,
    quartzSelector: ".recent-notes > h3",
    pseudoElement: "",
    properties: ["color", "font-family", "font-weight"],
  },
  {
    obsidianSelector: `.nav-files-container .tree-item`,
    publishSelector: `.nav-files-container .tree-item`,
    quartzSelector: ".recent-notes > ul.recent-ul > li",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  {
    obsidianSelector: `.nav-file-title`,
    publishSelector: `.nav-file-title`,
    quartzSelector:
      ".recent-notes > ul.recent-ul > li .section > .desc > h3 > a",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  {
    obsidianSelector: `.nav-file-title-content`,
    publishSelector: `.nav-file-title-content`,
    quartzSelector: ".recent-notes > ul.recent-ul > li .section > .meta",
    pseudoElement: "",
    properties: ["color", "font-family"],
  },
  // === LIST PAGE COMPONENT ===
  {
    obsidianSelector: `.nav-files-container`,
    publishSelector: `.nav-files-container`,
    quartzSelector: "ul.section-ul",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.nav-files-container .tree-item`,
    publishSelector: `.nav-files-container .tree-item`,
    quartzSelector: "li.section-li",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.nav-file-title`,
    publishSelector: `.nav-file-title`,
    quartzSelector: "li.section-li > .section > .desc > h3 > a",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  {
    obsidianSelector: `.nav-file-title-content`,
    publishSelector: `.nav-file-title-content`,
    quartzSelector: "li.section-li > .section .meta",
    pseudoElement: "",
    properties: ["color", "font-family"],
  },
  // === DARKMODE BUTTON ===
  {
    obsidianSelector: `.clickable-icon`,
    publishSelector: `.site-body-left-column-site-theme-toggle`,
    quartzSelector: ".darkmode",
    pseudoElement: "",
    properties: ["background-color", "color", "cursor", ...defaults.border],
  },
  {
    obsidianSelector: `.clickable-icon svg`,
    publishSelector: `.site-body-left-column-site-theme-toggle svg`,
    quartzSelector: ".darkmode svg",
    pseudoElement: "",
    properties: ["fill", "stroke", "color"],
  },
  // === BREADCRUMBS COMPONENT ===
  {
    obsidianSelector: `.view-header-breadcrumb`,
    publishSelector: `.view-header-breadcrumb`,
    quartzSelector: ".breadcrumb-container",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  {
    obsidianSelector: `.view-header-breadcrumb-separator`,
    publishSelector: `.view-header-breadcrumb-separator`,
    quartzSelector: ".breadcrumb-element p",
    pseudoElement: "",
    properties: ["color", "font-family"],
  },
  // === NAVIGATION PROGRESS BAR ===
  {
    obsidianSelector: `.status-bar`,
    publishSelector: null,
    quartzSelector: ".navigation-progress",
    pseudoElement: "",
    properties: ["background-color"],
  },
  // === PAGE TITLE ===
  {
    obsidianSelector: `.view-header-title`,
    publishSelector: `.page-header .page-title`,
    quartzSelector: ".page-header h2.page-title",
    pseudoElement: "",
    properties: sets.headings,
  },
  // === TRANSCLUDE / EMBED ===
  {
    obsidianSelector: `.internal-embed.is-loaded`,
    publishSelector: `.internal-embed`,
    quartzSelector: ".transclude",
    pseudoElement: "",
    properties: sets.embed,
  },
  {
    obsidianSelector: `.internal-embed.is-loaded .markdown-embed`,
    publishSelector: `.internal-embed .markdown-embed`,
    quartzSelector: ".transclude ul",
    pseudoElement: "",
    properties: ["padding-left", "color"],
  },
  // === KATEX / MATH DISPLAY ===
  {
    obsidianSelector: `.math-block`,
    publishSelector: `.math-block`,
    quartzSelector: ".katex-display",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  // === EXTERNAL EMBED (YouTube, PDF) ===
  {
    obsidianSelector: `.external-embed`,
    publishSelector: `.external-embed`,
    quartzSelector: ".external-embed.youtube",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.external-embed`,
    publishSelector: `.external-embed`,
    quartzSelector: "iframe.pdf",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  // === FOOTNOTES SECTION ===
  {
    obsidianSelector: `.footnotes`,
    publishSelector: `.footnotes`,
    quartzSelector: ".footnotes",
    pseudoElement: "",
    properties: [
      "background-color",
      "border-top-color",
      "border-top-style",
      "border-top-width",
      "color",
    ],
  },
  // === TABLE CONTAINER ===
  {
    obsidianSelector: `.table-wrapper`,
    publishSelector: `.table-wrapper`,
    quartzSelector: ".table-container",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  // === SPACER ELEMENT ===
  {
    obsidianSelector: `.workspace-leaf-content`,
    publishSelector: null,
    quartzSelector: ".spacer",
    pseudoElement: "",
    properties: ["background-color"],
  },
  // === OVERFLOW LISTS ===
  {
    obsidianSelector: `.view-content`,
    publishSelector: `.view-content`,
    quartzSelector: "ul.overflow",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `.view-content`,
    publishSelector: `.view-content`,
    quartzSelector: "ol.overflow",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  // === CODE BLOCK WITH TITLE ===
  {
    obsidianSelector: `pre.language-js`,
    publishSelector: `figure[data-rehype-pretty-code-figure]`,
    quartzSelector: "figure[data-rehype-pretty-code-figure]",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  {
    obsidianSelector: `pre.language-js`,
    publishSelector: `figure[data-rehype-pretty-code-figure] > [data-rehype-pretty-code-title]`,
    quartzSelector:
      "figure[data-rehype-pretty-code-figure] > [data-rehype-pretty-code-title]",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "font-family",
      ...defaults.border,
    ],
  },
  // === CODE LINE NUMBERS AND HIGHLIGHTING ===
  {
    obsidianSelector: `pre.language-js code span`,
    publishSelector: `pre > code [data-line]`,
    quartzSelector: "pre > code > [data-line]",
    pseudoElement: "",
    properties: [
      "background-color",
      "border-left-color",
      "border-left-style",
      "border-left-width",
    ],
  },
  {
    obsidianSelector: `pre.language-js code span`,
    publishSelector: `pre > code [data-highlighted-line]`,
    quartzSelector: "pre > code > [data-line][data-highlighted-line]",
    pseudoElement: "",
    properties: ["background-color", "border-left-color"],
  },
  {
    obsidianSelector: `pre.language-js code span`,
    publishSelector: `pre > code [data-highlighted-chars]`,
    quartzSelector: "pre > code [data-highlighted-chars]",
    pseudoElement: "",
    properties: ["background-color", ...defaults.border],
  },
  // === MERMAID DIAGRAMS ===
  {
    obsidianSelector: `pre:has(> code.mermaid)`,
    publishSelector: `pre:has(> code.mermaid)`,
    quartzSelector: "pre:has(> code.mermaid)",
    pseudoElement: "",
    properties: ["background-color", "border"],
  },
  // === TAGS LIST ===
  {
    obsidianSelector: `.tag-container`,
    publishSelector: `.tag-container`,
    quartzSelector: "ul.tags",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `.tag`,
    publishSelector: `.tag`,
    quartzSelector: "ul.tags > li",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  // === TEXT HIGHLIGHT ===
  {
    obsidianSelector: `mark.search-result-highlight`,
    publishSelector: `.search-highlight`,
    quartzSelector: ".text-highlight",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  // === STRONG TEXT COLOR ===
  {
    obsidianSelector: `article p > strong`,
    publishSelector: `.markdown-rendered p > strong`,
    quartzSelector: ".page article p > strong",
    pseudoElement: "",
    properties: ["color", "font-weight"],
  },
];
