// src/extraction-config.js
const sets = {
  typography: [
    "color",
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
  ],
  text: [
    "background-color",
    "color",
    "cursor",
    "filter",
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
    "margin-block-end",
    "margin-block-start",
    "outline",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-thickness",
    "transition",
    "user-select",
  ],
  list: [
    "color",
    "padding-top",
    "padding-bottom",
    "margin-inline-start",
    "text-align",
  ],
  pill: [
    "align-items",
    "background-color",
    "border-bottom-color",
    "border-left-color",
    "border-right-color",
    "border-top-color",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-style",
    "border-left-style",
    "border-right-style",
    "border-top-style",
    "display",
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
    "margin-inline-start",
  ],
  blockquote: [
    "background-color",
    "border-inline-start",
    "font-style",
    "padding-bottom",
    "padding-top",
    "padding-inline-start",
    "margin-inline-start",
    "margin-inline-end",
  ],
  headings: ["color", "font-family", "text-shadow"],
  callouts: {
    container: [
      "--callout-color",
      "--callout-icon",
      "background-color",
      "border-style",
      "border-color",
      "border-width",
      "border-radius",
      "mix-blend-mode",
      "padding",
    ],
    content: ["background-color", "padding"],
    icon: ["color"],
    title: ["color", "font-size", "gap", "line-height", "padding"],
    titleInner: ["color", "font-weight"],
  },
  background: ["background-color"],
  mermaid: ["stroke", "fill", "filter", "font-family", "font-size"],
  math: ["display", "text-align", "white-space", "font"],
  // ... other property groups
};

const body =
  "body > div.app-container > div.horizontal-main-container > div > div.workspace-split.mod-vertical.mod-root > div > div.workspace-tab-container > div > div > div.view-content";

export const extractionTargets = {
  general: {
    file: "general.md",
    selectors: [
      {
        obsidianSelector: null,
        quartzSelector: "div#quartz-root",
        pseudoElement: "",
        properties: ["background-color", "color", "font-family", "font-size"],
      },
      // links
      {
        obsidianSelector: `a.external-link`,
        quartzSelector: "a",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `a.internal-link`,
        quartzSelector: "a.internal-link",
        pseudoElement: "",
        properties: sets.text,
      },
      // text
      {
        obsidianSelector: `p`,
        quartzSelector: "p",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `strong`,
        quartzSelector: ".page article p > strong",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `b`,
        quartzSelector: ".page article p > b",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `em`,
        quartzSelector: ".page article p > em",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `i`,
        quartzSelector: ".page article p > i",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `u`,
        quartzSelector: ".page article p > u",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `s`,
        quartzSelector: ".page article p > s",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `mark`,
        quartzSelector: ".text-highlight",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `del`,
        quartzSelector: "del",
        pseudoElement: "",
        properties: sets.text,
      },
      {
        obsidianSelector: `hr`,
        quartzSelector: "hr",
        pseudoElement: "",
        properties: [
          "border",
          "border-color",
          "border-style",
          "border-top",
          "box-shadow",
          "margin",
        ],
      },
      // tag pills
      {
        obsidianSelector: `div.multi-select-pill`,
        quartzSelector: "a.internal.tag-link",
        pseudoElement: "",
        properties: sets.pill,
      },
      {
        obsidianSelector: `div.multi-select-pill > div.multi-select-pill-content`,
        quartzSelector: "a.internal.tag-link::before",
        pseudoElement: "",
        properties: ["color"],
      },
      // list items
      {
        obsidianSelector: `ul.has-list-bullet > li`,
        quartzSelector: "ul > li",
        pseudoElement: "",
        properties: sets.list,
      },
      {
        obsidianSelector: `ul.has-list-bullet > li > .list-bullet`,
        quartzSelector: "ul > li::marker",
        pseudoElement: "::after",
        properties: [
          "background-color",
          "border",
          "border-radius",
          "color",
          "content",
          "pointer-events",
          "transform",
          "transition",
        ],
      },
      {
        obsidianSelector: `ol > li`,
        quartzSelector: "ol > li",
        pseudoElement: "",
        properties: sets.list,
      },
      {
        obsidianSelector: `ol > li`,
        quartzSelector: "ol > li::marker",
        pseudoElement: "::marker",
        properties: ["color"],
      },
      // code blocks
      {
        obsidianSelector: `p > code`,
        quartzSelector: "code",
        pseudoElement: "",
        properties: [
          "background-color",
          "border",
          "border-radius",
          "color",
          "font-family",
          "font-size",
          "padding",
        ],
      },
      {
        obsidianSelector: `pre > code`,
        quartzSelector: "pre > code",
        pseudoElement: "",
        properties: [
          "background-color",
          "border",
          "border-radius",
          "overflow-x",
          "padding",
          "white-space",
        ],
      },
      // checkboxes
      {
        obsidianSelector: `ul.contains-task-list > li.task-list-item > .task-list-item-checkbox`,
        quartzSelector: "body input[type=checkbox]",
        pseudoElement: "",
        properties: [
          "appearance",
          "border",
          "border-radius",
          "padding",
          "margin",
          "width",
          "height",
          "margin-inline-start",
          "margin-inline-end",
          "transition",
          "position",
          "top",
        ],
      },
      {
        obsidianSelector: `ul.contains-task-list > li.task-list-item`,
        quartzSelector: "ul > li.task-list-item",
        pseudoElement: "",
        properties: ["list-style", "text-align", "display"],
      },
      {
        obsidianSelector: `ul.contains-task-list > li.task-list-item > input[type=checkbox]:checked`,
        quartzSelector: "body input[type=checkbox]:checked:after",
        pseudoElement: "::after",
        properties: [
          "content",
          "top",
          "inset-inline-start",
          "position",
          "width",
          "height",
          "display",
          "background-color",
          "-webkit-mask-position",
          "-webkit-mask-size",
          "-webkit-mask-repeat",
          "-webkit-mask-image",
        ],
      },
      {
        obsidianSelector: `ul > li.task-list-item[data-task="x"]`,
        quartzSelector: ".page article li:has(>input[type=checkbox]:checked)",
        pseudoElement: "",
        properties: ["color", "text-decoration", "text-decoration-color"],
      },
      // blockquote
      {
        obsidianSelector: `blockquote`,
        quartzSelector: "blockquote",
        pseudoElement: "",
        properties: sets.blockquote,
      },
      // footnotes
      {
        obsidianSelector: `.footnote-backref`,
        quartzSelector: ".data-footnote-backref",
        pseudoElement: "",
        properties: ["color", "text-decoration"],
      },
      // search
      {
        obsidianSelector: `.block-language-dataviewjs input[type="search"]`,
        quartzSelector: ".search > .search-button",
        pseudoElement: "",
        properties: [
          "background",
          "border",
          "border-radius",
          "color",
          "font-family",
          "font-size",
          "padding",
        ],
      },
    ],
  },
  headings: {
    file: "headings.md",
    selectors: [
      {
        obsidianSelector: `h1`,
        quartzSelector: "h1",
        pseudoElement: "",
        properties: sets.headings,
      },
      {
        obsidianSelector: `h2`,
        quartzSelector: "h2",
        pseudoElement: "",
        properties: sets.headings,
      },
      {
        obsidianSelector: `h3`,
        quartzSelector: "h3",
        pseudoElement: "",
        properties: sets.headings,
      },
      {
        obsidianSelector: `h4`,
        quartzSelector: "h4",
        pseudoElement: "",
        properties: sets.headings,
      },
      {
        obsidianSelector: `h5`,
        quartzSelector: "h5",
        pseudoElement: "",
        properties: sets.headings,
      },
      {
        obsidianSelector: `h6`,
        quartzSelector: "h6",
        pseudoElement: "",
        properties: sets.headings,
      },
      // outline
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-0",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-0 + li.depth-1",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-1",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-1 + li.depth-2",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-2",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-2 + li.depth-3",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-3",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-3 + li.depth-4",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-4",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-4 + li.depth-5",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-self`,
        quartzSelector: "li.depth-5",
        pseudoElement: "",
        properties: ["font-size", "line-height", "font-weight"],
      },
      {
        obsidianSelector: `.block-language-dataviewjs .view-content .tree-item .tree-item .tree-item .tree-item .tree-item .tree-item > .tree-item-children`,
        quartzSelector: "li.depth-5 + li.depth-6",
        pseudoElement: "",
        properties: [
          "margin-inline-start",
          "padding-inline-start",
          "border-inline-start",
        ],
      },
      // table
    ],
  },
  callouts: {
    file: "callouts.md",
    selectors: [
      // note
      {
        obsidianSelector: `.callout[data-callout="note"]`,
        quartzSelector: ".callout[data-callout]",
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="note"] > .callout-title`,
        quartzSelector: ".callout[data-callout] .callout-title",
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="note"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: ".callout[data-callout] .callout-title .callout-icon",
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="note"] > .callout-title > .callout-inner`,
        quartzSelector:
          ".callout[data-callout] .callout-title > .callout-title-inner > p",
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="note"] > .callout-content`,
        quartzSelector: ".callout[data-callout] > .callout-content",
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // abstract
      {
        obsidianSelector: `.callout[data-callout="abstract"]`,
        quartzSelector: `.callout[data-callout="abstract"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="abstract"] > .callout-title`,
        quartzSelector: `.callout[data-callout="abstract"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="abstract"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="abstract"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="abstract"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="abstract"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="abstract"] > .callout-content`,
        quartzSelector: `.callout[data-callout="abstract"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // info
      {
        obsidianSelector: `.callout[data-callout="info"]`,
        quartzSelector: `.callout[data-callout="info"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="info"] > .callout-title`,
        quartzSelector: `.callout[data-callout="info"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="info"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="info"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="info"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="info"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="info"] > .callout-content`,
        quartzSelector: `.callout[data-callout="info"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // todo
      {
        obsidianSelector: `.callout[data-callout="todo"]`,
        quartzSelector: `.callout[data-callout="todo"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="todo"] > .callout-title`,
        quartzSelector: `.callout[data-callout="todo"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="todo"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="todo"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="todo"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="todo"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="todo"] > .callout-content`,
        quartzSelector: `.callout[data-callout="todo"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // tip
      {
        obsidianSelector: `.callout[data-callout="tip"]`,
        quartzSelector: `.callout[data-callout="tip"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="tip"] > .callout-title`,
        quartzSelector: `.callout[data-callout="tip"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="tip"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="tip"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="tip"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="tip"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="tip"] > .callout-content`,
        quartzSelector: `.callout[data-callout="tip"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // success
      {
        obsidianSelector: `.callout[data-callout="success"]`,
        quartzSelector: `.callout[data-callout="success"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="success"] > .callout-title`,
        quartzSelector: `.callout[data-callout="success"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="success"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="success"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="success"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="success"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="success"] > .callout-content`,
        quartzSelector: `.callout[data-callout="success"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // question
      {
        obsidianSelector: `.callout[data-callout="question"]`,
        quartzSelector: `.callout[data-callout="question"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="question"] > .callout-title`,
        quartzSelector: `.callout[data-callout="question"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="question"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="question"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="question"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="question"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="question"] > .callout-content`,
        quartzSelector: `.callout[data-callout="question"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // warning
      {
        obsidianSelector: `.callout[data-callout="warning"]`,
        quartzSelector: `.callout[data-callout="warning"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="warning"] > .callout-title`,
        quartzSelector: `.callout[data-callout="warning"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="warning"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="warning"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="warning"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="warning"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="warning"] > .callout-content`,
        quartzSelector: `.callout[data-callout="warning"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // danger
      {
        obsidianSelector: `.callout[data-callout="danger"]`,
        quartzSelector: `.callout[data-callout="danger"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="danger"] > .callout-title`,
        quartzSelector: `.callout[data-callout="danger"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="danger"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="danger"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="danger"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="danger"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="danger"] > .callout-content`,
        quartzSelector: `.callout[data-callout="danger"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // failure
      {
        obsidianSelector: `.callout[data-callout="failure"]`,
        quartzSelector: `.callout[data-callout="failure"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="failure"] > .callout-title`,
        quartzSelector: `.callout[data-callout="failure"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="failure"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="failure"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="failure"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="failure"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="failure"] > .callout-content`,
        quartzSelector: `.callout[data-callout="failure"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // bug
      {
        obsidianSelector: `.callout[data-callout="bug"]`,
        quartzSelector: `.callout[data-callout="bug"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="bug"] > .callout-title`,
        quartzSelector: `.callout[data-callout="bug"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="bug"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="bug"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="bug"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="bug"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="bug"] > .callout-content`,
        quartzSelector: `.callout[data-callout="bug"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // example
      {
        obsidianSelector: `.callout[data-callout="example"]`,
        quartzSelector: `.callout[data-callout="example"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="example"] > .callout-title`,
        quartzSelector: `.callout[data-callout="example"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="example"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="example"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="example"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="example"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="example"] > .callout-content`,
        quartzSelector: `.callout[data-callout="example"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
      // quote
      {
        obsidianSelector: `.callout[data-callout="quote"]`,
        quartzSelector: `.callout[data-callout="quote"]`,
        pseudoElement: "",
        properties: sets.callouts.container,
      },
      {
        obsidianSelector: `.callout[data-callout="quote"] > .callout-title`,
        quartzSelector: `.callout[data-callout="quote"] .callout-title`,
        pseudoElement: "",
        properties: sets.callouts.title,
      },
      {
        obsidianSelector: `.callout[data-callout="quote"] > .callout-title > .callout-icon > svg.svg-icon`,
        quartzSelector: `.callout[data-callout="quote"] .callout-title .callout-icon`,
        pseudoElement: "",
        properties: sets.callouts.icon,
      },
      {
        obsidianSelector: `.callout[data-callout="quote"] > .callout-title > .callout-inner`,
        quartzSelector: `.callout[data-callout="quote"] .callout-title > .callout-title-inner > p`,
        pseudoElement: "",
        properties: sets.callouts.titleInner,
      },
      {
        obsidianSelector: `.callout[data-callout="quote"] > .callout-content`,
        quartzSelector: `.callout[data-callout="quote"] > .callout-content`,
        pseudoElement: "",
        properties: sets.callouts.content,
      },
    ],
  },
  integrations: {
    file: "integrations.md",
    selectors: [
      // mermaid
      {
        obsidianSelector: `.mermaid > svg`,
        quartzSelector: "code.mermaid > svg",
        pseudoElement: "",
        properties: sets.mermaid,
      },
      // mathjax
      {
        obsidianSelector: `.math-block > mjx-container.MathJax`,
        quartzSelector: ".katex-display > .katex",
        pseudoElement: "",
        properties: sets.math,
      },
      {
        obsidianSelector: `.math-block > mjx-container.MathJax`,
        quartzSelector: ".katex-display > .katex > .katex-html",
        pseudoElement: "",
        properties: ["font-family"],
      },
      {
        obsidianSelector: `.math-inline > mjx-container.MathJax > mjx-math`,
        quartzSelector: ".katex > .katex-html",
        pseudoElement: "",
        properties: ["font-family"],
      },
      // graph
      {
        obsidianSelector: `span.quartz-graph-target`,
        quartzSelector: "div.graph",
        pseudoElement: "",
        properties: [
          "--quartz-graph-text",
          "--quartz-graph-line",
          "--quartz-graph-node",
          "--quartz-graph-node-unresolved",
          "--quartz-graph-node-focused",
          "--quartz-graph-node-tag",
          "--quartz-graph-node-attachment",
        ],
      },
      // explorer
      {
        obsidianSelector: `.block-language-dataviewjs .nav-files-container .nav-file-title[data-path="callouts.md"]`,
        quartzSelector: "body .explorer .explorer-content ul.explorer-ul li a",
        pseudoElement: "",
        properties: [
          "color",
          "cursor",
          "font-family",
          "font-size",
          "font-weight",
          "line-height",
          "text-decoration",
        ],
      },
      {
        // closed
        obsidianSelector: `.block-language-dataviewjs .nav-files-container .nav-folder-title[data-path="folder/collapsed"]`,
        quartzSelector:
          "body .explorer .explorer-content li:has(> .folder-outer:not(.open)) > .folder-container",
        pseudoElement: "",
        properties: [
          "color",
          "cursor",
          "font-family",
          "font-size",
          "font-weight",
          "line-height",
          "text-decoration",
        ],
      },
      {
        // open
        obsidianSelector: `.block-language-dataviewjs .nav-files-container .nav-folder-title[data-path="folder"]`,
        quartzSelector:
          "body .explorer .explorer-content li:has(> .folder-outer.open) > .folder-container",
        pseudoElement: "",
        properties: [
          "color",
          "cursor",
          "font-family",
          "font-size",
          "font-weight",
          "line-height",
          "text-decoration",
        ],
      },
    ],
  },
  // ... more targets
};
