- name: Velocity - Configurator
  id: obsidian-velocity-config
  settings:
    - id: ss-section-heading
      title: Disable  features
      type: heading
      level: 1
      collapsed: true
    - id: disable-list-styling
      title: Restore bullet-style list markers
      type: class-toggle
    - id: disable-callout-styling
      title: Restore default Callout styling
      type: class-toggle
    - id: disable-custom-icons
      title: Restore default icon styling
      type: class-toggle
    - id: restore-table-scroll
      title: Restore table scrolling behavior
      type: class-toggle
    - id: restore-indent-guide
      title: Restore indentation guides
      type: class-toggle
    - id: disable-hover-header
      title: Disable Compact Panels in the sidebar
      type: class-toggle
    - id: disable-naked-embeds
      title: Disable Naked Embed styling
      type: class-toggle
    - id: disable-autohide
      title: Disable Sidebar Auto-Hide™ feature
      type: class-toggle
    - id: disable-status-fade
      title: Disable Status Bar fade until hover
      type: class-toggle
    - id: disable-title-h1
      title: Disable title style for H1 Headings
      type: class-toggle
    - id: ss-section-heading
      title: Enable optional features
      type: heading
      level: 1
      collapsed: true
    - id: prevent-exit
      title: Accidental exit prevention for tabs
      description: Disables the exit button when hovering over inactive tabs.
      type: class-toggle
    - id: active-line-highlight
      title: Active line highlighting
      description: Highlights the active line with slight backdrop for easier text navigation.
      type: class-toggle
    - id: hide-bases-header
      title: Cleaner Bases display
      description: Hides the filter toolbar options for embedded Bases in Reading mode.
      type: class-toggle
    - id: enable-dim-img
      title: Image dimming in Dark mode
      description: Reduces the brightness of images in Dark mode except when hovered.
      type: class-toggle
    - id: improve-pinned-tabs
      title: Improved pinned tabs appearance
      description: Forces pinned workspace tabs to the start of the tabs list, and hides their titles to save space.
      type: class-toggle
    - id: ss-section-heading
      title: Debug
      type: heading
      level: 1
      collapsed: true
    - id: disable-corner-smoothing
      title: Turn off Electron corner-smoothing
      description: Enable to fix visual bugs with tab containers and other rounded shapes.
      type: class-toggle
    - id: disable-performance-tweaks
      title: Disable performance tweaks
      description: Deactivates special CSS hacks which typically improve editor performance.
      type: class-toggle
    - null
