import { expansions, defaults, sets } from "./shared.js";

export const aspect = "callouts";

export const entries = [
  {
    obsidianSelector: `.callout[data-callout="note"] > .callout-title > .callout-icon > svg.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="note"] > .callout-title`,
    quartzSelector: ".callout .callout-title",
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: ".callout .callout-title > .callout-title-inner > p",
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: ".callout > .callout-content",
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"note\"]`,
    publishSelector: `.callout[data-callout="note"]`,
    quartzSelector: `.callout[data-callout="note"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-pencil.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="note"] > .callout-title`,
    quartzSelector: `.callout[data-callout="note"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="note"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="note"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"abstract\"]`,
    publishSelector: `.callout[data-callout="abstract"]`,
    quartzSelector: `.callout[data-callout="abstract"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-clipboard-list.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="abstract"] > .callout-title`,
    quartzSelector: `.callout[data-callout="abstract"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="abstract"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="abstract"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"info\"]`,
    publishSelector: `.callout[data-callout="info"]`,
    quartzSelector: `.callout[data-callout="info"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-info.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="info"] > .callout-title`,
    quartzSelector: `.callout[data-callout="info"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="info"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="info"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"todo\"]`,
    publishSelector: `.callout[data-callout="todo"]`,
    quartzSelector: `.callout[data-callout="todo"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-check-circle-2.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="todo"] > .callout-title`,
    quartzSelector: `.callout[data-callout="todo"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="todo"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="todo"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"tip\"]`,
    publishSelector: `.callout[data-callout="tip"]`,
    quartzSelector: `.callout[data-callout="tip"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-flame.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="tip"] > .callout-title`,
    quartzSelector: `.callout[data-callout="tip"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="tip"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="tip"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"success\"]`,
    publishSelector: `.callout[data-callout="success"]`,
    quartzSelector: `.callout[data-callout="success"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-check.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="success"] > .callout-title`,
    quartzSelector: `.callout[data-callout="success"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="success"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="success"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"question\"]`,
    publishSelector: `.callout[data-callout="question"]`,
    quartzSelector: `.callout[data-callout="question"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-help-circle.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="question"] > .callout-title`,
    quartzSelector: `.callout[data-callout="question"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="question"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="question"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"warning\"]`,
    publishSelector: `.callout[data-callout="warning"]`,
    quartzSelector: `.callout[data-callout="warning"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-alert-triangle.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="warning"] > .callout-title`,
    quartzSelector: `.callout[data-callout="warning"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="warning"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="warning"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"danger\"]`,
    publishSelector: `.callout[data-callout="danger"]`,
    quartzSelector: `.callout[data-callout="danger"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-zap.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="danger"] > .callout-title`,
    quartzSelector: `.callout[data-callout="danger"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="danger"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="danger"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"failure\"]`,
    publishSelector: `.callout[data-callout="failure"]`,
    quartzSelector: `.callout[data-callout="failure"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-x.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="failure"] > .callout-title`,
    quartzSelector: `.callout[data-callout="failure"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="failure"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="failure"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"bug\"]`,
    publishSelector: `.callout[data-callout="bug"]`,
    quartzSelector: `.callout[data-callout="bug"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-bug.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="bug"] > .callout-title`,
    quartzSelector: `.callout[data-callout="bug"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="bug"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="bug"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"example\"]`,
    publishSelector: `.callout[data-callout="example"]`,
    quartzSelector: `.callout[data-callout="example"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-list.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="example"] > .callout-title`,
    quartzSelector: `.callout[data-callout="example"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="example"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="example"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
  {
    obsidianSelector: `div.callout[data-callout-fold=\"\"][data-callout-metadata=\"\"][data-callout=\"quote\"]`,
    publishSelector: `.callout[data-callout="quote"]`,
    quartzSelector: `.callout[data-callout="quote"]`,
    pseudoElement: "",
    properties: sets.callouts.container,
  },
  {
    obsidianSelector: `svg.lucide-quote.svg-icon`,
    publishSelector: null,
    quartzSelector: null,
    pseudoElement: "",
    properties: sets.callouts.icon,
  },
  {
    obsidianSelector: `div.callout-title`,
    publishSelector: `.callout[data-callout="quote"] > .callout-title`,
    quartzSelector: `.callout[data-callout="quote"] .callout-title`,
    pseudoElement: "",
    properties: sets.callouts.title,
  },
  {
    obsidianSelector: `div.callout-title-inner`,
    publishSelector: `.callout > .callout-title > .callout-title-inner`,
    quartzSelector: `.callout[data-callout="quote"] .callout-title > .callout-title-inner > p`,
    pseudoElement: "",
    properties: sets.callouts.titleInner,
  },
  {
    obsidianSelector: `div.callout-content`,
    publishSelector: `.callout > .callout-content`,
    quartzSelector: `.callout[data-callout="quote"] > .callout-content`,
    pseudoElement: "",
    properties: sets.callouts.content,
  },
];
