import { expansions, defaults, sets } from "./shared.js";

export const aspect = "checkboxes";

export const entries = [
  {
    obsidianSelector: `input.task-list-item-checkbox[data-line=\"0\"]`,
    publishSelector: `ul.contains-task-list > li.task-list-item > .task-list-item-checkbox`,
    quartzSelector: "input[type=checkbox]",
    pseudoElement: "",
    properties: [
      "appearance",
      //"border",
      //"border-color",
      //"border-radius",
      ...defaults.border,
      //"padding",
      ...defaults.padding,
      //"margin",
      ...defaults.margin,
      "width",
      //"margin-inline-start",
      //"margin-inline-end",
      "transition",
      "position",
      "top",
    ],
  },
  {
    obsidianSelector: `li.task-list-item[data-line=\"0\"][data-task=\"\"]`,
    publishSelector: `ul.contains-task-list > li.task-list-item`,
    quartzSelector: "ul > li.task-list-item",
    pseudoElement: "",
    properties: ["list-style", "text-align", "display"],
  },
  {
    obsidianSelector: `li.is-checked.task-list-item[data-line=\"1\"][data-task=\"x\"]::after`,
    publishSelector: `ul.contains-task-list > li.task-list-item > input[type=checkbox]:checked`,
    quartzSelector: "input[type=checkbox]:checked:after",
    pseudoElement: "::after",
    properties: [
      "content",
      "top",
      "inset-inline-start",
      "position",
      "width",
      "display",
      "background-color",
      "-webkit-mask-position",
      "-webkit-mask-size",
      "-webkit-mask-repeat",
      "-webkit-mask-image",
    ],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="-"]`,
    publishSelector: `li.task-list-item[data-task="-"]`,
    quartzSelector: "li.task-list-item[data-task='-']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task=">"]`,
    publishSelector: `li.task-list-item[data-task=">"]`,
    quartzSelector: "li.task-list-item[data-task='>']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="/"]`,
    publishSelector: `li.task-list-item[data-task="/"]`,
    quartzSelector: "li.task-list-item[data-task='/']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="?"]`,
    publishSelector: `li.task-list-item[data-task="?"]`,
    quartzSelector: "li.task-list-item[data-task='?']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="!"]`,
    publishSelector: `li.task-list-item[data-task="!"]`,
    quartzSelector: "li.task-list-item[data-task='!']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="*"]`,
    publishSelector: `li.task-list-item[data-task="*"]`,
    quartzSelector: "li.task-list-item[data-task='*']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="l"]`,
    publishSelector: `li.task-list-item[data-task="l"]`,
    quartzSelector: "li.task-list-item[data-task='l']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="b"]`,
    publishSelector: `li.task-list-item[data-task="b"]`,
    quartzSelector: "li.task-list-item[data-task='b']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="i"]`,
    publishSelector: `li.task-list-item[data-task="i"]`,
    quartzSelector: "li.task-list-item[data-task='i']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="S"]`,
    publishSelector: `li.task-list-item[data-task="S"]`,
    quartzSelector: "li.task-list-item[data-task='S']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="I"]`,
    publishSelector: `li.task-list-item[data-task="I"]`,
    quartzSelector: "li.task-list-item[data-task='I']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="p"]`,
    publishSelector: `li.task-list-item[data-task="p"]`,
    quartzSelector: "li.task-list-item[data-task='p']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="c"]`,
    publishSelector: `li.task-list-item[data-task="c"]`,
    quartzSelector: "li.task-list-item[data-task='c']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="f"]`,
    publishSelector: `li.task-list-item[data-task="f"]`,
    quartzSelector: "li.task-list-item[data-task='f']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="k"]`,
    publishSelector: `li.task-list-item[data-task="k"]`,
    quartzSelector: "li.task-list-item[data-task='k']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="u"]`,
    publishSelector: `li.task-list-item[data-task="u"]`,
    quartzSelector: "li.task-list-item[data-task='u']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="d"]`,
    publishSelector: `li.task-list-item[data-task="d"]`,
    quartzSelector: "li.task-list-item[data-task='d']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
  {
    obsidianSelector: `li.task-list-item[data-task="w"]`,
    publishSelector: `li.task-list-item[data-task="w"]`,
    quartzSelector: "li.task-list-item[data-task='w']",
    pseudoElement: "",
    properties: ["color", "text-decoration", "text-decoration-color"],
  },
];
