import { expansions, defaults, sets } from "./shared.js";

export const aspect = "misc";

export const entries = [
  {
    obsidianSelector: `a.footnote-backref.footnote-link`,
    publishSelector: `.footnote-backref`,
    quartzSelector: ".data-footnote-backref",
    pseudoElement: "",
    properties: ["color", "text-decoration"],
  },
  {
    obsidianSelector: `progress`,
    publishSelector: `progress`,
    quartzSelector: "progress",
    pseudoElement: "",
    properties: sets.progress,
  },
  {
    obsidianSelector: `input[type="range"]`,
    publishSelector: `input[type="range"]`,
    quartzSelector: "input[type=range]",
    pseudoElement: "",
    properties: ["accent-color", "background-color", ...defaults.border],
  },
  {
    obsidianSelector: `input[type="text"]`,
    publishSelector: `input[type="text"]`,
    quartzSelector: "input[type=text]",
    pseudoElement: "",
    properties: [
      "background-color",
      "color",
      "font-family",
      ...defaults.border,
      ...defaults.padding,
    ],
  },
  {
    obsidianSelector: `details`,
    publishSelector: `details`,
    quartzSelector: "details",
    pseudoElement: "",
    properties: sets.details,
  },
  {
    obsidianSelector: `summary`,
    publishSelector: `summary`,
    quartzSelector: "summary",
    pseudoElement: "",
    properties: sets.summary,
  },
  {
    obsidianSelector: `details[open]`,
    publishSelector: `details[open]`,
    quartzSelector: "details[open]",
    pseudoElement: "",
    properties: sets.details,
  },
  {
    obsidianSelector: `kbd`,
    publishSelector: `kbd`,
    quartzSelector: "kbd",
    pseudoElement: "",
    properties: sets.kbd,
  },
  {
    obsidianSelector: `sub`,
    publishSelector: `sub`,
    quartzSelector: "sub",
    pseudoElement: "",
    properties: sets.subSup,
  },
  {
    obsidianSelector: `sup`,
    publishSelector: `sup`,
    quartzSelector: "sup",
    pseudoElement: "",
    properties: sets.subSup,
  },
  {
    obsidianSelector: `abbr`,
    publishSelector: `abbr`,
    quartzSelector: "abbr",
    pseudoElement: "",
    properties: ["color", "cursor", "text-decoration", "text-decoration-style"],
  },
  {
    obsidianSelector: `::selection`,
    publishSelector: `::selection`,
    quartzSelector: "::selection",
    pseudoElement: "::selection",
    properties: ["background-color", "color"],
  },
  {
    obsidianSelector: `input::placeholder`,
    publishSelector: `input::placeholder`,
    quartzSelector: "input::placeholder",
    pseudoElement: "::placeholder",
    properties: ["color", "opacity"],
  },
  {
    obsidianSelector: `mjx-container.MathJax`,
    publishSelector: `.math-block > mjx-container.MathJax`,
    quartzSelector: ".katex-display > .katex",
    pseudoElement: "",
    properties: sets.math,
  },
  {
    obsidianSelector: `mjx-container.MathJax`,
    publishSelector: `div.math-block > mjx-container.MathJax`,
    quartzSelector: ".katex-display > .katex > .katex-html",
    pseudoElement: "",
    properties: ["font-family"],
  },
  {
    obsidianSelector: `mjx-math.MJX-TEX`,
    publishSelector: `.math-inline > mjx-container.MathJax > mjx-math`,
    quartzSelector: ".katex > .katex-html",
    pseudoElement: "",
    properties: ["font-family"],
  },
  {
    obsidianSelector: `.status-bar`,
    publishSelector: null,
    quartzSelector: ".navigation-progress",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `.view-header-title`,
    publishSelector: `.page-header .page-title`,
    quartzSelector: ".page-header h2.page-title",
    pseudoElement: "",
    properties: sets.headings.default,
  },
  {
    obsidianSelector: `.math-block`,
    publishSelector: `.math-block`,
    quartzSelector: ".katex-display",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  {
    obsidianSelector: `.footnotes`,
    publishSelector: `.footnotes`,
    quartzSelector: ".footnotes",
    pseudoElement: "",
    properties: [
      "background-color",
      "border-top-color",
      "border-top-style",
      "border-top-width",
      "color",
    ],
  },
  {
    obsidianSelector: `.workspace-leaf-content`,
    publishSelector: null,
    quartzSelector: ".spacer",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `pre:has(> code.mermaid)`,
    publishSelector: `pre:has(> code.mermaid)`,
    quartzSelector: "pre:has(> code.mermaid)",
    pseudoElement: "",
    properties: ["background-color", "border"],
  },
  {
    obsidianSelector: `.tag-container`,
    publishSelector: `.tag-container`,
    quartzSelector: "ul.tags",
    pseudoElement: "",
    properties: ["background-color"],
  },
  {
    obsidianSelector: `.tag`,
    publishSelector: `.tag`,
    quartzSelector: "ul.tags > li",
    pseudoElement: "",
    properties: ["background-color", "color", ...defaults.border],
  },
  {
    obsidianSelector: `input[type="checkbox"]`,
    publishSelector: null,
    quartzSelector: 'li.task-list-item input[type="checkbox"]',
    pseudoElement: "",
    properties: [
      "border-color",
      "border-radius",
      "border-width",
      "background-color",
    ],
  },
  {
    obsidianSelector: `input[type="checkbox"]:checked`,
    publishSelector: null,
    quartzSelector: 'li.task-list-item input[type="checkbox"]:checked',
    pseudoElement: "",
    properties: ["background-color", "border-color"],
  },
  {
    obsidianSelector: `.status-bar`,
    publishSelector: null,
    quartzSelector: "footer",
    pseudoElement: "",
    properties: ["opacity"],
  },
  {
    obsidianSelector: `.frontmatter-container`,
    publishSelector: null,
    quartzSelector: ".content-meta",
    pseudoElement: "",
    properties: ["color", "font-size"],
  },
];
