// src/extraction-config.js
// TODO: Fix background color mappings
// Probably needs to target the publish container div directly instead of body
export const expansions = {
  borderStyle: [
    "border-left-style",
    "border-bottom-style",
    "border-right-style",
    "border-top-style",
  ],
  borderColor: [
    "border-left-color",
    "border-right-color",
    "border-top-color",
    "border-bottom-color",
  ],
  borderWidth: [
    "border-left-width",
    "border-right-width",
    "border-top-width",
    "border-bottom-width",
  ],
  borderRadius: [
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-start-start-radius",
    "border-start-end-radius",
    "border-end-start-radius",
    "border-end-end-radius",
  ],
};

export const defaults = {
  border: [
    ...expansions.borderStyle,
    ...expansions.borderColor,
    ...expansions.borderWidth,
    ...expansions.borderRadius,
  ],
  margin: [
    "margin-top",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-block-end",
    "margin-block-start",
    "margin-inline-end",
    "margin-inline-start",
  ],
  padding: [
    "padding-top",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-block-end",
    "padding-block-start",
    "padding-inline-end",
    "padding-inline-start",
  ],
  transition: [
    "transition-behavior",
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
  ],
  animation: [
    "animation-name",
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "animation-fill-mode",
    "animation-play-state",
  ],
  whiteSpace: [
    "white-space-collapse",
    "text-wrap-mode",
    //"white-space-trim", // not implemented in any browser at the moment.
  ],
};

export const sets = {
  typography: [
    "color",
    "font-family",
    //"font-size",
    "font-weight",
    "line-height",
  ],
  text: [
    "background-color",
    "color",
    "cursor",
    "filter",
    "backdrop-filter",
    "box-shadow",
    "font-family",
    //"font-size",
    "font-weight",
    //"line-height",
    //"margin-block-end",
    //"margin-block-start",
    "outline",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-thickness",
    "transition",
    "transform",
    "user-select",
    ...defaults.animation,
  ],
  // Tables
  table: [
    "background-color",
    "border-collapse",
    "border-spacing",
    "color",
    "font-family",
    "table-layout",
    "text-align",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  tableCell: [
    "background-color",
    "color",
    "font-weight",
    "text-align",
    "vertical-align",
    "box-shadow",
    "text-decoration",
    ...defaults.border,
    ...defaults.padding,
  ],
  tableHeader: [
    "background-color",
    "color",
    "font-weight",
    "text-align",
    "vertical-align",
    "box-shadow",
    "text-decoration",
    "letter-spacing",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Images and Media
  image: [
    "border-radius",
    "box-shadow",
    "filter",
    "max-width",
    "object-fit",
    ...defaults.border,
    ...defaults.margin,
  ],
  figure: [
    "background-color",
    "text-align",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  figcaption: [
    "color",
    "font-family",
    "font-size",
    "font-style",
    "text-align",
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Embeds
  embed: [
    "background-color",
    "color",
    "box-shadow",
    "border-radius",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Frontmatter/Properties
  frontmatter: [
    "background-color",
    "color",
    "font-family",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  // Tooltips and Popovers
  tooltip: [
    "background-color",
    "box-shadow",
    "color",
    "font-family",
    "font-size",
    "max-width",
    "width",
    "opacity",
    "border-radius",
    "z-index",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Progress and Range
  progress: ["accent-color", "background-color", "height", ...defaults.border],
  // Details/Summary (Collapsible)
  details: [
    "background-color",
    ...defaults.border,
    ...defaults.margin,
    ...defaults.padding,
  ],
  summary: [
    "background-color",
    "color",
    "cursor",
    "font-weight",
    "list-style",
    ...defaults.padding,
  ],
  // Keyboard input
  kbd: [
    "background-color",
    "box-shadow",
    "color",
    "font-family",
    "font-size",
    ...defaults.border,
    ...defaults.padding,
  ],
  // Definition lists
  definitionList: [...defaults.margin, "list-style", ...defaults.padding],
  definitionTerm: [
    "color",
    "font-weight",
    ...defaults.margin,
    "font-size",
    "font-family",
    ...defaults.padding,
    ...defaults.border,
  ],
  definitionDesc: [
    "color",
    "font-size",
    "font-family",
    ...defaults.margin,
    ...defaults.padding,
    ...defaults.border,
  ],
  // Subscript/Superscript
  subSup: ["color", "font-size", "vertical-align"],
  // Backlinks
  backlinks: [
    "background-color",
    "color",
    ...defaults.border,
    ...defaults.padding,
  ],
  list: [
    "color",
    //"padding-top",
    //"padding-bottom",
    //"margin-inline-start",
    "text-align",
    // list-style-type, list-style-position, and list-style-image are intentionally
    // excluded. Obsidian suppresses native markers (setting list-style-type to a
    // zero-width space) because it renders bullets via span.list-bullet::after.
    // Copying those values into Quartz hides native ::marker bullets/numbers.
    ...defaults.padding,
    "margin-top",
    "margin-bottom",
    // "margin-left",
    "margin-right",
    "margin-block-end",
    "margin-block-start",
    "margin-inline-end",
    // "margin-inline-start",
  ],
  pill: [
    "align-items",
    "background-color",
    "color",
    "display",
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
    "text-decoration",
    "margin-inline-start",
    ...defaults.border,
  ],
  blockquote: [
    "background-color",
    "border-inline-start",
    "color",
    "font-family",
    "font-weight",
    "font-style",
    "line-height",
    "padding-bottom",
    "padding-top",
    "padding-inline-start",
    "margin-inline-start",
    "margin-inline-end",
    "text-decoration",
    "letter-spacing",
  ],
  headings: {
    default: [
      "color",
      "font-family",
      "font-size",
      "font-weight",
      "line-height",
      "text-shadow",
      "text-decoration",
      "letter-spacing",
      "background-color",
      "background-image",
      "background",
      ...defaults.padding,
      ...defaults.margin,
      ...defaults.border,
    ],
    after: [
      ...defaults.border,
      ...defaults.margin,
      "width",
      "height",
      "background-color",
      "background-image",
      "background",
      "content",
      "display",
      "color",
    ],
  },

  callouts: {
    container: [
      "--callout-color",
      "--callout-icon",
      "background-color",
      "background-image",
      "background",
      "color",
      //"border-style",
      //"border-color",
      //"border-width",
      //"border-radius",
      "mix-blend-mode",
      //"padding",
      ...defaults.border,
    ],
    content: [
      "background-color",
      "background-image",
      "background",
      "color",
      ...defaults.padding,
    ],
    icon: ["fill", "stroke"],
    title: [
      "--callout-color",
      "color",
      /*"font-size", */ "gap" /*, "line-height"*/,
      ...defaults.border,
      ...defaults.padding,
      "background-color",
      "background-image",
      "background",
    ],
    titleInner: ["color", "font-weight"],
  },
  background: ["background-color"],
  mermaid: [
    "stroke",
    "fill",
    "filter",
    "font-family",
    "font-size",
    "color",
    "background-color",
    ...defaults.border,
  ],
  math: ["display", "text-align", ...defaults.whiteSpace, "font-family"],
  // ... other property groups
};
